/*
 * JSP generated by Resin 2.0.5 (built Thu Jan 10 21:43:38 PST 2002)
 */

package _admin._inc;
import javax.servlet.*;
import javax.servlet.jsp.*;
import javax.servlet.http.*;
import tengry.cms.core.Admin;

public class _page_0header__jsp extends com.caucho.jsp.JavaPage{
  private boolean _caucho_isDead;
  
  public void
  _jspService(javax.servlet.http.HttpServletRequest request,
              javax.servlet.http.HttpServletResponse response)
    throws java.io.IOException, javax.servlet.ServletException
  {
    com.caucho.jsp.QPageContext pageContext = (com.caucho.jsp.QPageContext) com.caucho.jsp.QJspFactory.create().getPageContext(this, request, response, null, true, 8192, true);
    javax.servlet.jsp.JspWriter out = (javax.servlet.jsp.JspWriter) pageContext.getOut();
    javax.servlet.ServletConfig config = getServletConfig();
    javax.servlet.Servlet page = this;
    javax.servlet.http.HttpSession session = pageContext.getSession();
    javax.servlet.ServletContext application = pageContext.getServletContext();
    response.setContentType("text/html; charset=windows-1251");
    request.setCharacterEncoding("CP1251");
    try {
      pageContext.write(_jsp_string0, 0, _jsp_string0.length);
      pageContext.write(_jsp_string0, 0, _jsp_string0.length);
      pageContext.write(_jsp_string0, 0, _jsp_string0.length);
      
    response.setHeader( "Pragma", "no-cache" );
    String title = request .getParameter("title");
    if(title == null)
		title = "Административная зона";
	Admin admin = (Admin)session.getValue("admin.user");

      pageContext.write(_jsp_string1, 0, _jsp_string1.length);
      out.print((title));
      pageContext.write(_jsp_string2, 0, _jsp_string2.length);
      	if(admin != null)
	{

      pageContext.write(_jsp_string3, 0, _jsp_string3.length);
      	} 
      pageContext.write(_jsp_string4, 0, _jsp_string4.length);
      	if(admin != null)
	{

      pageContext.write(_jsp_string5, 0, _jsp_string5.length);
      out.print((admin.getLogin()));
      pageContext.write(_jsp_string6, 0, _jsp_string6.length);
      	} 
      pageContext.write(_jsp_string7, 0, _jsp_string7.length);
    } catch (java.lang.Throwable _jsp_e) {
      pageContext.handlePageException(_jsp_e);
    } finally {
      JspFactory.getDefaultFactory().releasePageContext(pageContext);
    }
  }

  private com.caucho.java.LineMap _caucho_line_map;
  private java.util.ArrayList _caucho_depends = new java.util.ArrayList();

  public boolean _caucho_isModified()
  {
    if (_caucho_isDead)
      return true;
    if (com.caucho.util.CauchoSystem.getVersionId() != 2058990002)
      return true;
    for (int i = _caucho_depends.size() - 1; i >= 0; i--) {
      com.caucho.vfs.Depend depend;
      depend = (com.caucho.vfs.Depend) _caucho_depends.get(i);
      if (depend.isModified())
        return true;
    }
    return false;
  }

  public long _caucho_lastModified()
  {
    return 0;
  }

  public com.caucho.java.LineMap _caucho_getLineMap()
  {
    return _caucho_line_map;
  }

  public void destroy()
  {
      _caucho_isDead = true;
      super.destroy();
  }

  public void init(com.caucho.java.LineMap lineMap,
                   com.caucho.vfs.Path appDir)
    throws javax.servlet.ServletException
  {
    com.caucho.vfs.Path resinHome = com.caucho.util.CauchoSystem.getResinHome();
    com.caucho.vfs.MergePath mergePath = new com.caucho.vfs.MergePath();
    mergePath.addMergePath(appDir);
    mergePath.addMergePath(resinHome);
    mergePath.addClassPath(getClass().getClassLoader());
    _caucho_line_map = new com.caucho.java.LineMap("_page_0header__jsp.java", "/admin/inc/page_header.jsp");
    _caucho_line_map.add(1, 1);
    _caucho_line_map.add(1, 28);
    _caucho_line_map.add(18, 39);
    _caucho_line_map.add(26, 41);
    _caucho_line_map.add(32, 45);
    _caucho_line_map.add(39, 47);
    com.caucho.vfs.Depend depend;
    depend = new com.caucho.vfs.Depend(mergePath.lookup("file:/usr/local/apache/htdocs/ntvmir/admin/inc/page_header.jsp"), 1038498148000L, 1198L);
    _caucho_depends.add(depend);
  }

  private static byte []_jsp_string3;
  private static byte []_jsp_string4;
  private static byte []_jsp_string5;
  private static byte []_jsp_string6;
  private static byte []_jsp_string7;
  private static byte []_jsp_string2;
  private static byte []_jsp_string1;
  private static byte []_jsp_string0;
  static {
    try {
      _jsp_string3 = "\r\n<TD WIDTH=\"1%\">\r\n<A HREF=\"/admin/xt_logout.jsp\">Выход</A>\r\n</TD>\r\n".getBytes("Cp1251");
      _jsp_string4 = "\r\n\r\n<TD ALIGN=\"center\">\r\n<SPAN CLASS=\"tit\">\r\nНТВ Мир - административная часть\r\n</SPAN>\r\n</TD>\r\n".getBytes("Cp1251");
      _jsp_string5 = "\r\n<TD WIDTH=\"1%\">\r\n&nbsp;администратор:&nbsp;<B>".getBytes("Cp1251");
      _jsp_string6 = "</B>&nbsp;\r\n</TD>\r\n".getBytes("Cp1251");
      _jsp_string7 = "\r\n</TR>\r\n</TABLE>\r\n".getBytes("Cp1251");
      _jsp_string2 = "</TITLE>\r\n\r\n<LINK REL=\"STYLESHEET\" TYPE=\"text/css\" HREF=\"/admin/css.css\">\r\n</HEAD>\r\n<BODY BGCOLOR=\"#FFFFFF\" MARGINHEIGHT=5 MARGINWIDTH=5 LEFTMARGIN=5 TOPMARGIN=5>\r\n\r\n<TABLE WIDTH=\"100%\" BORDER=\"0\" CELLPADDING=\"2\" CELLSPACING=\"0\" CLASS=\"title\">\r\n<TR>\r\n".getBytes("Cp1251");
      _jsp_string1 = "\r\n<HTML>\r\n<HEAD>\r\n<META HTTP-EQUIV=Content-type CONTENT=\"text/html; charset=windows-1251\">\r\n<META HTTP-EQUIV=Content-language CONTENT=RU>\r\n<META NAME=description CONTENT=\"\">\r\n<META NAME=keywords CONTENT=\"\">\r\n<META NAME=autor CONTENT=\"\">\r\n<TITLE>".getBytes("Cp1251");
      _jsp_string0 = "\r\n".getBytes("Cp1251");
    } catch (java.io.UnsupportedEncodingException e) {
      e.printStackTrace();
    }
  }
}
