/*
 * JSP generated by Resin 2.0.5 (built Thu Jan 10 21:43:38 PST 2002)
 */

package _admin._inc;
import javax.servlet.*;
import javax.servlet.jsp.*;
import javax.servlet.http.*;
import java.util.Hashtable;
import tengry.cms.core.*;
import tengry.cms.press.*;
import tengry.cms.dict.*;
import tengry.cms.user.*;
import tengry.cms.vote.*;
import tengry.cms.forum.*;
import tengry.cms.faq.*;
import tengry.ntvmir.tvschedule.*;
import tengry.ntvmir.*;
import tengry.cms.CMSApplication;

public class _page_0start__jsp extends com.caucho.jsp.JavaPage{
  private boolean _caucho_isDead;
  
    public void printService(JspWriter out, Service srv, Admin admin) throws Exception
    {
        if(srv == null)
            return;
        if(admin != null && admin.isR(srv.getId()))
    		out.print("<A HREF=\"" + srv.getUrl() + "\">" + srv.getName() + "</A>");
    	else
    		out.print("<B STYLE=\"color: #888888;\">" + srv.getName() + "</B>");
    	out.println("<BR>");
    }

  
  public void
  _jspService(javax.servlet.http.HttpServletRequest request,
              javax.servlet.http.HttpServletResponse response)
    throws java.io.IOException, javax.servlet.ServletException
  {
    com.caucho.jsp.QPageContext pageContext = (com.caucho.jsp.QPageContext) com.caucho.jsp.QJspFactory.create().getPageContext(this, request, response, null, true, 8192, true);
    javax.servlet.jsp.JspWriter out = (javax.servlet.jsp.JspWriter) pageContext.getOut();
    javax.servlet.ServletConfig config = getServletConfig();
    javax.servlet.Servlet page = this;
    javax.servlet.http.HttpSession session = pageContext.getSession();
    javax.servlet.ServletContext application = pageContext.getServletContext();
    response.setContentType("text/html; charset=windows-1251");
    request.setCharacterEncoding("CP1251");
    try {
      pageContext.write(_jsp_string0, 0, _jsp_string0.length);
      pageContext.write(_jsp_string0, 0, _jsp_string0.length);
      pageContext.write(_jsp_string0, 0, _jsp_string0.length);
      pageContext.write(_jsp_string0, 0, _jsp_string0.length);
      pageContext.write(_jsp_string0, 0, _jsp_string0.length);
      pageContext.write(_jsp_string0, 0, _jsp_string0.length);
      pageContext.write(_jsp_string0, 0, _jsp_string0.length);
      pageContext.write(_jsp_string0, 0, _jsp_string0.length);
      pageContext.write(_jsp_string0, 0, _jsp_string0.length);
      pageContext.write(_jsp_string0, 0, _jsp_string0.length);
      pageContext.write(_jsp_string0, 0, _jsp_string0.length);
      pageContext.write(_jsp_string0, 0, _jsp_string0.length);
      pageContext.write(_jsp_string0, 0, _jsp_string0.length);
      
    response.setHeader( "Pragma", "no-cache" );
    String title = request .getParameter("title");
    String header = request.getParameter("header");
    String message = request.getParameter("message");
    String width = request.getParameter("width");
    
    if(title == null)
		title = "Административная зона";
	
	if("".equals(header))
		header = null;
	
	if("".equals(message))
		message = null;
	
	if(width == null || "".equals(width))
		width = "100%";
	
	Admin admin = (Admin)session.getValue("admin.user");
	java.util.Enumeration services = CMSApplication.getApplication().getServices();
	Hashtable serviceHash = new Hashtable();
	while(services.hasMoreElements())
	{
	    Service srv = (Service)services.nextElement();
	    serviceHash.put(srv.getCode(), srv);
	}

      pageContext.write(_jsp_string0, 0, _jsp_string0.length);
      pageContext.write(_jsp_string1, 0, _jsp_string1.length);
      out.flush();
      pageContext.include("/admin/inc/page_header.jsp"+ '?'+ "title="+ (title));
      pageContext.write(_jsp_string2, 0, _jsp_string2.length);
      printService(out, (Service)serviceHash.get(WebTreeNode.SERVICE_CODE), admin);
      pageContext.write(_jsp_string3, 0, _jsp_string3.length);
      printService(out, (Service)serviceHash.get(HomePage.SERVICE_CODE), admin);
      pageContext.write(_jsp_string3, 0, _jsp_string3.length);
      printService(out, (Service)serviceHash.get(Vote.SERVICE_CODE), admin);
      pageContext.write(_jsp_string4, 0, _jsp_string4.length);
      printService(out, (Service)serviceHash.get(Forum.SERVICE_CODE), admin);
      pageContext.write(_jsp_string3, 0, _jsp_string3.length);
      printService(out, (Service)serviceHash.get(News.SERVICE_CODE), admin);
      pageContext.write(_jsp_string3, 0, _jsp_string3.length);
      printService(out, (Service)serviceHash.get(Article.SERVICE_CODE), admin);
      pageContext.write(_jsp_string3, 0, _jsp_string3.length);
      //printService(out, (Service)serviceHash.get(Release.SERVICE_CODE), admin);
      pageContext.write(_jsp_string5, 0, _jsp_string5.length);
      pageContext.write(_jsp_string4, 0, _jsp_string4.length);
      printService(out, (Service)serviceHash.get(Tvschedule.SERVICE_CODE), admin);
      pageContext.write(_jsp_string3, 0, _jsp_string3.length);
      printService(out, (Service)serviceHash.get(Tvannounce.SERVICE_CODE), admin);
      pageContext.write(_jsp_string3, 0, _jsp_string3.length);
      printService(out, (Service)serviceHash.get(FaqCategory.SERVICE_CODE), admin);
      pageContext.write(_jsp_string4, 0, _jsp_string4.length);
      printService(out, (Service)serviceHash.get(User.SERVICE_CODE), admin);
      pageContext.write(_jsp_string3, 0, _jsp_string3.length);
      printService(out, (Service)serviceHash.get("message"), admin);
      pageContext.write(_jsp_string3, 0, _jsp_string3.length);
      printService(out, (Service)serviceHash.get("mailer"), admin);
      pageContext.write(_jsp_string4, 0, _jsp_string4.length);
      printService(out, (Service)serviceHash.get(FileObject.SERVICE_CODE), admin);
      pageContext.write(_jsp_string3, 0, _jsp_string3.length);
      printService(out, (Service)serviceHash.get(Admin.SERVICE_CODE), admin);
      pageContext.write(_jsp_string3, 0, _jsp_string3.length);
      printService(out, (Service)serviceHash.get(Journal.SERVICE_CODE), admin);
      pageContext.write(_jsp_string6, 0, _jsp_string6.length);
      	
	try
	{
		int PAGE_ERROR = -1;
		try
		{ 
			PAGE_ERROR = Integer.parseInt( request.getParameter( "err" )); 
		}
		catch( Exception e )
		{
			PAGE_ERROR = -1;
		}
		
		if( PAGE_ERROR >= 0 )
		{

      pageContext.write(_jsp_string7, 0, _jsp_string7.length);
      
			switch( PAGE_ERROR )
			{
				case tengry.cms.CMSApplication.PAGE_ERROR_NO_PERMISSIONS:
					out.println( "Нет прав для выполнения данной операции." ); break;
				case tengry.cms.CMSApplication.PAGE_ERROR_WHILE_SAVING:
					out.println( "Ошибка при сохранении." ); break;
				case tengry.cms.CMSApplication.PAGE_ERROR_WHILE_REMOVING:
					out.println( "Ошибка при удалении." ); break;
				case tengry.cms.CMSApplication.PAGE_ERROR_ACCESS_DENIED:
					out.println( "Доступ закрыт." ); break;
				default:
					out.println( "Ошибка." ); break;
			}

      pageContext.write(_jsp_string8, 0, _jsp_string8.length);
      
		} 
	}
	catch( Exception e ){}

      pageContext.write(_jsp_string9, 0, _jsp_string9.length);
      out.print((width));
      pageContext.write(_jsp_string10, 0, _jsp_string10.length);
      	
	if(header != null)
	{

      pageContext.write(_jsp_string11, 0, _jsp_string11.length);
      out.print((header));
      pageContext.write(_jsp_string12, 0, _jsp_string12.length);
      	}
	if(message != null)
	{

      pageContext.write(_jsp_string13, 0, _jsp_string13.length);
      out.print((message));
      pageContext.write(_jsp_string14, 0, _jsp_string14.length);
      
	}

      pageContext.write(_jsp_string15, 0, _jsp_string15.length);
    } catch (java.lang.Throwable _jsp_e) {
      pageContext.handlePageException(_jsp_e);
    } finally {
      JspFactory.getDefaultFactory().releasePageContext(pageContext);
    }
  }

  private com.caucho.java.LineMap _caucho_line_map;
  private java.util.ArrayList _caucho_depends = new java.util.ArrayList();

  public boolean _caucho_isModified()
  {
    if (_caucho_isDead)
      return true;
    if (com.caucho.util.CauchoSystem.getVersionId() != 2058990002)
      return true;
    for (int i = _caucho_depends.size() - 1; i >= 0; i--) {
      com.caucho.vfs.Depend depend;
      depend = (com.caucho.vfs.Depend) _caucho_depends.get(i);
      if (depend.isModified())
        return true;
    }
    return false;
  }

  public long _caucho_lastModified()
  {
    return 0;
  }

  public com.caucho.java.LineMap _caucho_getLineMap()
  {
    return _caucho_line_map;
  }

  public void destroy()
  {
      _caucho_isDead = true;
      super.destroy();
  }

  public void init(com.caucho.java.LineMap lineMap,
                   com.caucho.vfs.Path appDir)
    throws javax.servlet.ServletException
  {
    com.caucho.vfs.Path resinHome = com.caucho.util.CauchoSystem.getResinHome();
    com.caucho.vfs.MergePath mergePath = new com.caucho.vfs.MergePath();
    mergePath.addMergePath(appDir);
    mergePath.addMergePath(resinHome);
    mergePath.addClassPath(getClass().getClassLoader());
    _caucho_line_map = new com.caucho.java.LineMap("_page_0start__jsp.java", "/usr/local/apache/htdocs/ntvmir/admin/inc/page_start.jsp");
    _caucho_line_map.add("/admin/inc/page_start.jsp", 1, 1);
    _caucho_line_map.add(42, 23);
    _caucho_line_map.add(1, 50);
    _caucho_line_map.add(42, 92);
    _caucho_line_map.add(55, 93);
    _caucho_line_map.add(65, 96);
    _caucho_line_map.add(66, 98);
    _caucho_line_map.add(67, 100);
    _caucho_line_map.add(72, 102);
    _caucho_line_map.add(73, 104);
    _caucho_line_map.add(74, 106);
    _caucho_line_map.add(75, 108);
    _caucho_line_map.add(89, 111);
    _caucho_line_map.add(90, 113);
    _caucho_line_map.add(91, 115);
    _caucho_line_map.add(96, 117);
    _caucho_line_map.add(97, 119);
    _caucho_line_map.add(98, 121);
    _caucho_line_map.add(103, 123);
    _caucho_line_map.add(104, 125);
    _caucho_line_map.add(105, 127);
    _caucho_line_map.add(116, 129);
    _caucho_line_map.add("/admin/inc/error.jsp", 1, 129);
    _caucho_line_map.add("/usr/local/apache/htdocs/ntvmir/admin/inc/page_start.jsp", 117, 168);
    _caucho_line_map.add(125, 175);
    _caucho_line_map.add(128, 177);
    _caucho_line_map.add(134, 182);
    _caucho_line_map.add(137, 184);
    com.caucho.vfs.Depend depend;
    depend = new com.caucho.vfs.Depend(mergePath.lookup("file:/usr/local/apache/htdocs/ntvmir/admin/inc/error.jsp"), 1018519612000L, 876L);
    _caucho_depends.add(depend);
    depend = new com.caucho.vfs.Depend(mergePath.lookup("file:/usr/local/apache/htdocs/ntvmir/admin/inc/page_start.jsp"), 1043337136000L, 4839L);
    _caucho_depends.add(depend);
  }

  private static byte []_jsp_string4;
  private static byte []_jsp_string14;
  private static byte []_jsp_string9;
  private static byte []_jsp_string5;
  private static byte []_jsp_string6;
  private static byte []_jsp_string2;
  private static byte []_jsp_string0;
  private static byte []_jsp_string3;
  private static byte []_jsp_string11;
  private static byte []_jsp_string10;
  private static byte []_jsp_string15;
  private static byte []_jsp_string12;
  private static byte []_jsp_string13;
  private static byte []_jsp_string1;
  private static byte []_jsp_string7;
  private static byte []_jsp_string8;
  static {
    try {
      _jsp_string4 = "\r\n    </TD>\r\n    <TD WIDTH=\"20\"><IMG SRC=\"/admin/img/blank.gif\" WIDTH=\"20\" HEIGHT=\"1\"><BR></TD>\r\n\r\n    <TD VALIGN=\"bottom\">\r\n    ".getBytes("Cp1251");
      _jsp_string14 = "</SPAN><BR><IMG SRC=\"/admin/img/blank.gif\" WIDTH=\"1\" HEIGHT=\"10\">\r\n</TD>\r\n</TR>\r\n".getBytes("Cp1251");
      _jsp_string9 = "\r\n\r\n\r\n<TABLE WIDTH=\"".getBytes("Cp1251");
      _jsp_string5 = "\r\n    </TD>\r\n    <TD WIDTH=\"20\"><IMG SRC=\"/admin/img/blank.gif\" WIDTH=\"20\" HEIGHT=\"1\"><BR></TD>\r\n\r\n".getBytes("Cp1251");
      _jsp_string6 = "\r\n    </TD>\r\n    </TR>\r\n    </TABLE>\r\n</TD>\r\n</TR>\r\n<!--TR>\r\n<TD CLASS=\"c2\" COLSPAN=\"11\"></TD>\r\n</TR-->\r\n</TABLE>\r\n\r\n".getBytes("Cp1251");
      _jsp_string2 = "\r\n\r\n<TABLE WIDTH=\"100%\" BORDER=\"0\" CELLPADDING=\"0\" CELLSPACING=\"0\">\r\n<TR>\r\n<TD>\r\n    <TABLE WIDTH=\"100%\" BORDER=\"0\" CELLPADDING=\"5\" CELLSPACING=\"0\">\r\n    <TR>\r\n    <TD VALIGN=\"bottom\">\r\n    ".getBytes("Cp1251");
      _jsp_string0 = "\r\n".getBytes("Cp1251");
      _jsp_string3 = "\r\n    ".getBytes("Cp1251");
      _jsp_string11 = "\r\n<TR>\r\n<TD ALIGN=\"center\">\r\n<DIV CLASS=\"page_header\">".getBytes("Cp1251");
      _jsp_string10 = "\" BORDER=\"0\" CELLPADDING=\"0\" CELLSPACING=\"0\">\r\n<!-- ADMIN PAGE HEADER -->\r\n".getBytes("Cp1251");
      _jsp_string15 = "\r\n<TR>\r\n<TD>\r\n".getBytes("Cp1251");
      _jsp_string12 = "</DIV>\r\n</TD>\r\n</TR>\r\n".getBytes("Cp1251");
      _jsp_string13 = "\r\n<TR>\r\n<TD ALIGN=\"center\">\r\n<SPAN CLASS=\"page_error\">".getBytes("Cp1251");
      _jsp_string1 = "\r\n\r\n".getBytes("Cp1251");
      _jsp_string7 = "\r\n<B STYLE=\"color: red\">\r\n".getBytes("Cp1251");
      _jsp_string8 = "\r\n</B><BR><BR><BR>\r\n".getBytes("Cp1251");
    } catch (java.io.UnsupportedEncodingException e) {
      e.printStackTrace();
    }
  }
}
