/*
 * JSP generated by Resin 2.0.5 (built Thu Jan 10 21:43:38 PST 2002)
 */

package _tvschedule;
import javax.servlet.*;
import javax.servlet.jsp.*;
import javax.servlet.http.*;
import java.io.*;
import java.util.*;
import tengry.ntvmir.tvschedule.*;
import tengry.cms.*;
import tengry.cms.db.*;
import tengry.cms.core.*;
import tengry.cms.user.*;
import tengry.cms.mailer.*;

public class _tvschedule__jsp extends com.caucho.jsp.JavaPage{
  private boolean _caucho_isDead;
  
public String nodePath(WebTreeNode node)
{
    if(node == null)
        return "/pages";
    return nodePath(node.getParent()) + "/" + node.getCode();
}

public String nodePath(String nodeId)
{
    return nodePath(CMSApplication.getApplication().lookup(nodeId));
}

  
    private static final String [] MONTHS = new String[] {
        "Января", "Февраля", "Марта", "Апреля", "Мая", "Июня",
        "Июля", "Авгуса", "Сентября", "Октября", "Ноября", "Декабря"
    };
    private static final String [] DAYS = new String[] {
        "--", "Воскресенье", "Понедельник", "Вторник", "Среда", "Четверг", "Пятница", "Суббота"
    };
    public String toString(Date date, int offset)
    {
        Calendar cal = Calendar.getInstance();
        cal.setTime(date);
        if(offset != 0)
            cal.add(Calendar.DATE, offset);
        return  "" + cal.get(Calendar.DATE) + " " + MONTHS[cal.get(Calendar.MONTH)] + 
                    ", <b>" + DAYS[cal.get(Calendar.DAY_OF_WEEK)] + "</b>";
    }

  
  public void
  _jspService(javax.servlet.http.HttpServletRequest request,
              javax.servlet.http.HttpServletResponse response)
    throws java.io.IOException, javax.servlet.ServletException
  {
    com.caucho.jsp.QPageContext pageContext = (com.caucho.jsp.QPageContext) com.caucho.jsp.QJspFactory.create().getPageContext(this, request, response, null, true, 8192, true);
    javax.servlet.jsp.JspWriter out = (javax.servlet.jsp.JspWriter) pageContext.getOut();
    javax.servlet.ServletConfig config = getServletConfig();
    javax.servlet.Servlet page = this;
    javax.servlet.http.HttpSession session = pageContext.getSession();
    javax.servlet.ServletContext application = pageContext.getServletContext();
    response.setContentType("text/html; charset=windows-1251");
    request.setCharacterEncoding("CP1251");
    try {
      pageContext.write(_jsp_string0, 0, _jsp_string0.length);
      pageContext.write(_jsp_string0, 0, _jsp_string0.length);
      pageContext.write(_jsp_string0, 0, _jsp_string0.length);
      pageContext.write(_jsp_string0, 0, _jsp_string0.length);
      pageContext.write(_jsp_string0, 0, _jsp_string0.length);
      pageContext.write(_jsp_string0, 0, _jsp_string0.length);
      pageContext.write(_jsp_string0, 0, _jsp_string0.length);
      pageContext.write(_jsp_string0, 0, _jsp_string0.length);
      pageContext.write(_jsp_string0, 0, _jsp_string0.length);
      pageContext.write(_jsp_string0, 0, _jsp_string0.length);
      
	String      langCode        = null;
	String      pageId          = null;
	String      des             = null;
    User        user            = null;

    langCode = request.getParameter("lang_code");
    if(langCode == null || langCode.trim().length() == 0)
        langCode = CMSApplication.getApplication().getPrimaryLangCode();

	des = CMSApplication.getApplication().getCurrentDesignPath() + "/" + langCode;

	pageId = request.getParameter("id");
	if("".equals(pageId))
		pageId = null;
		
    user = (User)session.getAttribute("ntvmir.user");
    if(user == null)
    {
        String usrid = CMSApplication.getCookie(request, "user.id");
        if(usrid != null && usrid.length() > 0)
        {
            try
            {
                user = User.quickAuthorize(usrid);
            }catch(Exception e){}
        }
    }

	boolean     adminPreview    = false;
	Hashtable   previewInfo     = null;
	adminPreview = (session.getValue("admin.user") != null && "1".equals(request.getParameter("preview")));
	
	previewInfo = (Hashtable)session.getAttribute("admin.previewinfo");
	if(!adminPreview)
		previewInfo = null;

      pageContext.write(_jsp_string1, 0, _jsp_string1.length);
      pageContext.write(_jsp_string0, 0, _jsp_string0.length);
        response.setHeader("Pragma","no-cache"); 
      pageContext.write(_jsp_string0, 0, _jsp_string0.length);
      
    String  sDate   = request.getParameter("date");
    Date    date    = null;
    Date    nextDate    = null;
    Date    prevDate    = null;
    java.text.SimpleDateFormat sdf = new java.text.SimpleDateFormat("dd.MM.yyyy");

try{

    try{
        date = sdf.parse(sDate);
    } catch(Exception e) {
        date = sdf.parse(sdf.format(new Date()));
    }
    
    Calendar cal = Calendar.getInstance();
    cal.setTime(date);
    cal.add(Calendar.DATE, -1);
    prevDate = cal.getTime();
    cal.add(Calendar.DATE, +2);
    nextDate = cal.getTime();

    String showPlaceId = request.getParameter("show_place_id");
    ShowPlace showPlace = null;
    int gmtShift = 0;
    
    if(showPlaceId != null && showPlaceId.length() > 0)
    {
        try
        {
            showPlace = ShowPlace.getShowPlace(langCode, showPlaceId);
        }
        catch(Exception e)
        {
            showPlace = null;
        }
    }

    if(showPlace == null)
    {
        String spId = CMSApplication.getCookie(request, "tvschedule.showplace");
        if(spId != null && spId.length() > 0)
        {
            try{
                showPlace = ShowPlace.getShowPlace(langCode, spId);
            }catch(Exception e)
            {
                showPlace = null;
            }
        }
    }
    
    if(showPlace == null)
    {
        showPlace = ShowPlace.getDefaultShowPlace(langCode);
    }
    
    if(showPlace == null)
        showPlaceId = "";
    else
    {
        showPlaceId = showPlace.getId();
        gmtShift = showPlace.getTimeZone().getGmtShift();
    }

    Enumeration spEnum = ShowPlace.getShowPlaces(langCode);
    Enumeration enum = Tvschedule.getItems(langCode, date, 1, true).elements();
    Enumeration tvaEnum = Tvannounce.getTvannounces(langCode, date, 2, 6).elements();

      pageContext.write(_jsp_string0, 0, _jsp_string0.length);
      pageContext.write(_jsp_string2, 0, _jsp_string2.length);
      
	Vector pagePath = new Vector();
	String sectionImg = "company";
	String sectionName = "О компании";
	if(pageId != null)
	{
	    WebTreeNode treeNode = CMSApplication.getApplication().lookup(pageId);
	    while(treeNode != null && treeNode.getParent() != null)
	    {
	        pagePath.insertElementAt(treeNode, 0);
	        sectionImg = treeNode.getCode();
	        sectionName = treeNode.getName();
	        treeNode = treeNode.getParent();
	    }
	}
	if(adminPreview && previewInfo != null)
	{
	    sectionImg = (String)previewInfo.get("section");
	    if(sectionImg == null)
	        sectionImg = "about";
	    
	}
	if("about".equals(sectionImg))
	    sectionImg = "company";
	else if("tvschedule".equals(sectionImg))
	    sectionImg = "tvprogram";
	else if("auth".equals(sectionImg))
	    sectionImg = "authorization";

      pageContext.write(_jsp_string3, 0, _jsp_string3.length);
      
    if(pagePath.size() > 1)
    {

      pageContext.write(_jsp_string4, 0, _jsp_string4.length);
        
        for(int i = 0; i < pagePath.size(); i++)
        {
            WebTreeNode treeNode = (WebTreeNode)pagePath.elementAt(i);
            if(i+1 == pagePath.size())
                out.println(CMSApplication.toHTML(treeNode.getName()));
            else
            {

      pageContext.write(_jsp_string5, 0, _jsp_string5.length);
      out.print((nodePath(treeNode)));
      pageContext.write(_jsp_string6, 0, _jsp_string6.length);
      out.print((CMSApplication.toHTML(treeNode.getName())));
      pageContext.write(_jsp_string7, 0, _jsp_string7.length);
      
            }
        }

      pageContext.write(_jsp_string8, 0, _jsp_string8.length);
        } 
      pageContext.write(_jsp_string9, 0, _jsp_string9.length);
      out.print((des));
      pageContext.write(_jsp_string10, 0, _jsp_string10.length);
      out.print((sectionImg));
      pageContext.write(_jsp_string11, 0, _jsp_string11.length);
      out.print((sectionName));
      pageContext.write(_jsp_string12, 0, _jsp_string12.length);
      pageContext.write(_jsp_string13, 0, _jsp_string13.length);
      out.print((des));
      pageContext.write(_jsp_string14, 0, _jsp_string14.length);
      out.print((des));
      pageContext.write(_jsp_string15, 0, _jsp_string15.length);
      out.print((des));
      pageContext.write(_jsp_string16, 0, _jsp_string16.length);
      out.print((des));
      pageContext.write(_jsp_string17, 0, _jsp_string17.length);
      pageContext.write(_jsp_string18, 0, _jsp_string18.length);
      out.print((langCode));
      pageContext.write(_jsp_string19, 0, _jsp_string19.length);
      out.print((des));
      pageContext.write(_jsp_string20, 0, _jsp_string20.length);
      out.print((sdf.format(date)));
      pageContext.write(_jsp_string21, 0, _jsp_string21.length);
      out.print((des));
      pageContext.write(_jsp_string22, 0, _jsp_string22.length);
      out.print((sdf.format(date)));
      pageContext.write(_jsp_string23, 0, _jsp_string23.length);
      out.print((pageId));
      pageContext.write(_jsp_string24, 0, _jsp_string24.length);
        while(spEnum.hasMoreElements())
    {
        ShowPlace sp = (ShowPlace)spEnum.nextElement();

      pageContext.write(_jsp_string25, 0, _jsp_string25.length);
      out.print((sp.getId()));
      pageContext.write(_jsp_string26, 0, _jsp_string26.length);
      out.print((sp.getId().equals(showPlaceId) ? " SELECTED" : ""));
      pageContext.write(_jsp_string27, 0, _jsp_string27.length);
      out.print((sp.getTimeZone().getName()));
      pageContext.write(_jsp_string28, 0, _jsp_string28.length);
      out.print((CMSApplication.toHTML(sp.getName())));
      pageContext.write(_jsp_string29, 0, _jsp_string29.length);
      	} 
      pageContext.write(_jsp_string30, 0, _jsp_string30.length);
      out.print((des));
      pageContext.write(_jsp_string31, 0, _jsp_string31.length);
      out.print((des));
      pageContext.write(_jsp_string32, 0, _jsp_string32.length);
      out.print((sdf.format(date)));
      pageContext.write(_jsp_string33, 0, _jsp_string33.length);
      out.print((des));
      pageContext.write(_jsp_string34, 0, _jsp_string34.length);
      out.print((des));
      pageContext.write(_jsp_string35, 0, _jsp_string35.length);
      out.print((toString(date, 0)));
      pageContext.write(_jsp_string36, 0, _jsp_string36.length);
      
    String sCurDate = sdf.format(date);
    while(tvaEnum.hasMoreElements())
    {
        Tvannounce tva = (Tvannounce)tvaEnum.nextElement();
        String sTvaDate = sdf.format(tva.getTvDate(langCode));
        if(!sCurDate.equals(sTvaDate))
        {

      pageContext.write(_jsp_string37, 0, _jsp_string37.length);
      out.print((des));
      pageContext.write(_jsp_string38, 0, _jsp_string38.length);
      
        }
        sCurDate = sTvaDate;

      pageContext.write(_jsp_string0, 0, _jsp_string0.length);
      pageContext.write(_jsp_string39, 0, _jsp_string39.length);
      out.print((des));
      pageContext.write(_jsp_string40, 0, _jsp_string40.length);
      out.print((langCode));
      pageContext.write(_jsp_string41, 0, _jsp_string41.length);
      out.print((tva.getId()));
      pageContext.write(_jsp_string42, 0, _jsp_string42.length);
      out.print((tva.getImg()));
      pageContext.write(_jsp_string43, 0, _jsp_string43.length);
      out.print((langCode));
      pageContext.write(_jsp_string41, 0, _jsp_string41.length);
      out.print((tva.getId()));
      pageContext.write(_jsp_string44, 0, _jsp_string44.length);
      out.print((tva.getTime(gmtShift)));
      pageContext.write(_jsp_string45, 0, _jsp_string45.length);
      out.print((CMSApplication.toHTML(tva.getName())));
      pageContext.write(_jsp_string46, 0, _jsp_string46.length);
      out.print((CMSApplication.toHTML(tva.getBrief())));
      pageContext.write(_jsp_string47, 0, _jsp_string47.length);
      out.print((des));
      pageContext.write(_jsp_string48, 0, _jsp_string48.length);
      pageContext.write(_jsp_string49, 0, _jsp_string49.length);
        } 
      pageContext.write(_jsp_string50, 0, _jsp_string50.length);
      pageContext.write(_jsp_string51, 0, _jsp_string51.length);
      
    while(enum.hasMoreElements())
    {
        Tvschedule item = (Tvschedule)enum.nextElement();

      pageContext.write(_jsp_string52, 0, _jsp_string52.length);
      out.print((des));
      pageContext.write(_jsp_string53, 0, _jsp_string53.length);
      out.print((item.getTime(gmtShift)));
      pageContext.write(_jsp_string54, 0, _jsp_string54.length);
      out.print((CMSApplication.toHTML(item.getName())));
      pageContext.write(_jsp_string55, 0, _jsp_string55.length);
      out.print((CMSApplication.toHTML(item.getDescription())));
      pageContext.write(_jsp_string56, 0, _jsp_string56.length);
      out.print((des));
      pageContext.write(_jsp_string57, 0, _jsp_string57.length);
        } 
      pageContext.write(_jsp_string58, 0, _jsp_string58.length);
      pageContext.write(_jsp_string1, 0, _jsp_string1.length);
      pageContext.write(_jsp_string59, 0, _jsp_string59.length);
      out.print((langCode));
      pageContext.write(_jsp_string60, 0, _jsp_string60.length);
      out.print((sdf.format(prevDate)));
      pageContext.write(_jsp_string61, 0, _jsp_string61.length);
      out.print((des));
      pageContext.write(_jsp_string62, 0, _jsp_string62.length);
      out.print((toString(date, -1)));
      pageContext.write(_jsp_string63, 0, _jsp_string63.length);
      out.print((langCode));
      pageContext.write(_jsp_string60, 0, _jsp_string60.length);
      out.print((sdf.format(nextDate)));
      pageContext.write(_jsp_string64, 0, _jsp_string64.length);
      out.print((toString(date, +1)));
      pageContext.write(_jsp_string65, 0, _jsp_string65.length);
      out.print((des));
      pageContext.write(_jsp_string66, 0, _jsp_string66.length);
      pageContext.write(_jsp_string67, 0, _jsp_string67.length);
      pageContext.write(_jsp_string0, 0, _jsp_string0.length);
        }catch(Exception e){} 
    } catch (java.lang.Throwable _jsp_e) {
      pageContext.handlePageException(_jsp_e);
    } finally {
      JspFactory.getDefaultFactory().releasePageContext(pageContext);
    }
  }

  private com.caucho.java.LineMap _caucho_line_map;
  private java.util.ArrayList _caucho_depends = new java.util.ArrayList();

  public boolean _caucho_isModified()
  {
    if (_caucho_isDead)
      return true;
    if (com.caucho.util.CauchoSystem.getVersionId() != 2058990002)
      return true;
    for (int i = _caucho_depends.size() - 1; i >= 0; i--) {
      com.caucho.vfs.Depend depend;
      depend = (com.caucho.vfs.Depend) _caucho_depends.get(i);
      if (depend.isModified())
        return true;
    }
    return false;
  }

  public long _caucho_lastModified()
  {
    return 0;
  }

  public com.caucho.java.LineMap _caucho_getLineMap()
  {
    return _caucho_line_map;
  }

  public void destroy()
  {
      _caucho_isDead = true;
      super.destroy();
  }

  public void init(com.caucho.java.LineMap lineMap,
                   com.caucho.vfs.Path appDir)
    throws javax.servlet.ServletException
  {
    com.caucho.vfs.Path resinHome = com.caucho.util.CauchoSystem.getResinHome();
    com.caucho.vfs.MergePath mergePath = new com.caucho.vfs.MergePath();
    mergePath.addMergePath(appDir);
    mergePath.addMergePath(resinHome);
    mergePath.addClassPath(getClass().getClassLoader());
    _caucho_line_map = new com.caucho.java.LineMap("_tvschedule__jsp.java", "/usr/local/apache/htdocs/ntvmir/tvschedule/tvschedule.jsp");
    _caucho_line_map.add("/tvschedule/tvschedule.jsp", 1, 1);
    _caucho_line_map.add("/inc/init_global.jsp", 1, 1);
    _caucho_line_map.add(44, 20);
    _caucho_line_map.add("/usr/local/apache/htdocs/ntvmir/tvschedule/tvschedule.jsp", 77, 33);
    _caucho_line_map.add("/tvschedule/tvschedule.jsp", 1, 66);
    _caucho_line_map.add("/inc/init_global.jsp", 1, 71);
    _caucho_line_map.add("/usr/local/apache/htdocs/ntvmir/tvschedule/tvschedule.jsp", 7, 115);
    _caucho_line_map.add(8, 117);
    _caucho_line_map.add(77, 187);
    _caucho_line_map.add(99, 188);
    _caucho_line_map.add("/inc/path_init.jsp", 1, 188);
    _caucho_line_map.add("/usr/local/apache/htdocs/ntvmir/tvschedule/tvschedule.jsp", 104, 218);
    _caucho_line_map.add(118, 233);
    _caucho_line_map.add(118, 235);
    _caucho_line_map.add(119, 237);
    _caucho_line_map.add(126, 246);
    _caucho_line_map.add(126, 248);
    _caucho_line_map.add(132, 251);
    _caucho_line_map.add(134, 255);
    _caucho_line_map.add(135, 257);
    _caucho_line_map.add(143, 260);
    _caucho_line_map.add(143, 262);
    _caucho_line_map.add(144, 264);
    _caucho_line_map.add(144, 266);
    _caucho_line_map.add(150, 268);
    _caucho_line_map.add(151, 270);
    _caucho_line_map.add(155, 272);
    _caucho_line_map.add(159, 277);
    _caucho_line_map.add(159, 279);
    _caucho_line_map.add(159, 281);
    _caucho_line_map.add(159, 283);
    _caucho_line_map.add(160, 285);
    _caucho_line_map.add(161, 287);
    _caucho_line_map.add(170, 289);
    _caucho_line_map.add(173, 291);
    _caucho_line_map.add(173, 293);
    _caucho_line_map.add(174, 295);
    _caucho_line_map.add(174, 297);
    _caucho_line_map.add(182, 299);
    _caucho_line_map.add(193, 309);
    _caucho_line_map.add(197, 311);
    _caucho_line_map.add(203, 319);
    _caucho_line_map.add(203, 321);
    _caucho_line_map.add(203, 323);
    _caucho_line_map.add(207, 325);
    _caucho_line_map.add(207, 327);
    _caucho_line_map.add(210, 331);
    _caucho_line_map.add(211, 333);
    _caucho_line_map.add(211, 335);
    _caucho_line_map.add(218, 338);
    _caucho_line_map.add(227, 341);
    _caucho_line_map.add(234, 349);
    _caucho_line_map.add(237, 351);
    _caucho_line_map.add(237, 353);
    _caucho_line_map.add(240, 357);
    _caucho_line_map.add(247, 361);
    _caucho_line_map.add(247, 363);
    _caucho_line_map.add(247, 365);
    _caucho_line_map.add(247, 367);
    _caucho_line_map.add(248, 369);
    _caucho_line_map.add(248, 371);
    _caucho_line_map.add(248, 373);
    _caucho_line_map.add(248, 375);
    _caucho_line_map.add(257, 379);
    com.caucho.vfs.Depend depend;
    depend = new com.caucho.vfs.Depend(mergePath.lookup("file:/usr/local/apache/htdocs/ntvmir/inc/init_global.jsp"), 1043852040000L, 1646L);
    _caucho_depends.add(depend);
    depend = new com.caucho.vfs.Depend(mergePath.lookup("file:/usr/local/apache/htdocs/ntvmir/inc/path_init.jsp"), 1043334172000L, 857L);
    _caucho_depends.add(depend);
    depend = new com.caucho.vfs.Depend(mergePath.lookup("file:/usr/local/apache/htdocs/ntvmir/tvschedule/tvschedule.jsp"), 1046707243000L, 9890L);
    _caucho_depends.add(depend);
  }

  private static byte []_jsp_string55;
  private static byte []_jsp_string23;
  private static byte []_jsp_string61;
  private static byte []_jsp_string11;
  private static byte []_jsp_string47;
  private static byte []_jsp_string56;
  private static byte []_jsp_string20;
  private static byte []_jsp_string28;
  private static byte []_jsp_string26;
  private static byte []_jsp_string9;
  private static byte []_jsp_string16;
  private static byte []_jsp_string35;
  private static byte []_jsp_string14;
  private static byte []_jsp_string54;
  private static byte []_jsp_string10;
  private static byte []_jsp_string50;
  private static byte []_jsp_string53;
  private static byte []_jsp_string4;
  private static byte []_jsp_string27;
  private static byte []_jsp_string19;
  private static byte []_jsp_string31;
  private static byte []_jsp_string15;
  private static byte []_jsp_string45;
  private static byte []_jsp_string17;
  private static byte []_jsp_string13;
  private static byte []_jsp_string22;
  private static byte []_jsp_string41;
  private static byte []_jsp_string6;
  private static byte []_jsp_string30;
  private static byte []_jsp_string39;
  private static byte []_jsp_string42;
  private static byte []_jsp_string18;
  private static byte []_jsp_string36;
  private static byte []_jsp_string65;
  private static byte []_jsp_string62;
  private static byte []_jsp_string57;
  private static byte []_jsp_string40;
  private static byte []_jsp_string32;
  private static byte []_jsp_string24;
  private static byte []_jsp_string59;
  private static byte []_jsp_string2;
  private static byte []_jsp_string51;
  private static byte []_jsp_string7;
  private static byte []_jsp_string0;
  private static byte []_jsp_string58;
  private static byte []_jsp_string33;
  private static byte []_jsp_string12;
  private static byte []_jsp_string63;
  private static byte []_jsp_string21;
  private static byte []_jsp_string49;
  private static byte []_jsp_string29;
  private static byte []_jsp_string44;
  private static byte []_jsp_string25;
  private static byte []_jsp_string34;
  private static byte []_jsp_string3;
  private static byte []_jsp_string5;
  private static byte []_jsp_string66;
  private static byte []_jsp_string52;
  private static byte []_jsp_string64;
  private static byte []_jsp_string37;
  private static byte []_jsp_string38;
  private static byte []_jsp_string46;
  private static byte []_jsp_string43;
  private static byte []_jsp_string67;
  private static byte []_jsp_string60;
  private static byte []_jsp_string1;
  private static byte []_jsp_string8;
  private static byte []_jsp_string48;
  static {
    try {
      _jsp_string55 = "</b></a> ".getBytes("Cp1251");
      _jsp_string23 = "\">\r\n	<input type=\"hidden\" name=\"id\" value=\"".getBytes("Cp1251");
      _jsp_string61 = "\" class=\"nonUa\"><img src=\"".getBytes("Cp1251");
      _jsp_string11 = "/ttl.gif\" height=\"47\" alt=\"".getBytes("Cp1251");
      _jsp_string47 = "<img src=\"".getBytes("Cp1251");
      _jsp_string56 = "</td>\r\n</tr>\r\n<tr><td height=\"6\" colspan=\"3\" background=\"".getBytes("Cp1251");
      _jsp_string20 = "/tvprogram/btn-subs.gif\" width=\"143\" height=\"9\" alt=\"Подписаться на программу\" border=\"0\" hspace=\"7\"></a><br>\r\n<a href=\"/tvschedule/schedule_prn.jsp?date=".getBytes("Cp1251");
      _jsp_string28 = " ".getBytes("Cp1251");
      _jsp_string26 = "\"".getBytes("Cp1251");
      _jsp_string9 = "\r\n</td>\r\n<!--заголовок страницы--><td align=\"right\"><img src=\"".getBytes("Cp1251");
      _jsp_string16 = "/tvprogram/ttl-weekly.gif\" width=\"131\" height=\"19\" alt=\"Программа на неделю\" border=\"0\"></td>\r\n		<td align=\"right\"><img src=\"".getBytes("Cp1251");
      _jsp_string35 = "/tvprogram/ico-cal.gif\" width=\"16\" height=\"12\" alt=\"\" border=\"0\" align=\"absbottom\" hspace=\"3\"><SPAN class=\"grnTtl\">".getBytes("Cp1251");
      _jsp_string14 = "/blu-ttl-bg.gif\" bgcolor=\"#004896\">\r\n	<tr>\r\n		<td nowrap><img src=\"".getBytes("Cp1251");
      _jsp_string54 = "</b></a>\r\n	</td>\r\n	<td><div style=\"width:1;\"><SPACER TYPE=\"block\" HEIGHT=\"1\" WIDTH=\"1\"></div></td>\r\n	<td width=\"100%\" class=\"defFont\"><a class=\"nonUa\"><b class=\"bluTtl\">".getBytes("Cp1251");
      _jsp_string10 = "/".getBytes("Cp1251");
      _jsp_string50 = "\r\n</table>\r\n\r\n</td>\r\n<td></td>\r\n<td>\r\n\r\n".getBytes("Cp1251");
      _jsp_string53 = "/hm-bg.gif) no-repeat;font-family: Verdana;\" class=\"smallFont\" align=\"center\" height=\"18\"><!--распорка--><div style=\"width:36;height:1;\"><SPACER TYPE=\"block\" HEIGHT=\"1\" WIDTH=\"36\"></div>\r\n	<a class=\"nonUa\"><b class=\"bluTtl\">".getBytes("Cp1251");
      _jsp_string4 = "\r\n<div style=\"margin-top:8px\">\r\n".getBytes("Cp1251");
      _jsp_string27 = ">".getBytes("Cp1251");
      _jsp_string19 = "/auth\"><img src=\"".getBytes("Cp1251");
      _jsp_string31 = "/btn-arr-blu.gif\" width=\"18\" height=\"18\" border=\"0\" hspace=\"3\" vspace=\"0\" align=\"absmiddle\"><br>\r\n	</NOBR>\r\n	</td>\r\n	</form></tr>\r\n	</table>\r\n</td>\r\n</tr>\r\n<tr>\r\n<td height=\"20\" bgcolor=\"#DDF3E1\" class=\"defFont\">\r\n&nbsp;<img src=\"".getBytes("Cp1251");
      _jsp_string15 = "/blu-ttl-lft.gif\" width=\"16\" height=\"19\" border=\"0\"><img src=\"".getBytes("Cp1251");
      _jsp_string45 = "</SPAN><br>\r\n<b class=\"bluTtl\">".getBytes("Cp1251");
      _jsp_string17 = "/blu-ttl-rght.gif\" width=\"16\" height=\"19\" border=\"0\"></td>\r\n	</tr>\r\n	</table>\r\n".getBytes("Cp1251");
      _jsp_string13 = "\r\n	<table width=\"100%\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" background=\"".getBytes("Cp1251");
      _jsp_string22 = "/tvprogram/btn-prnt-week.gif\" width=\"169\" height=\"12\" alt=\"Версия для печати на всю неделю\" border=\"0\" hspace=\"7\" vspace=\"7\"></a><br>\r\n</td>\r\n<td><div style=\"width:7;\"><SPACER TYPE=\"block\" HEIGHT=\"1\" WIDTH=\"7\"></div></td>\r\n<td width=\"100%\" align=\"right\" valign=\"top\">\r\n	<table border=\"0\" cellpadding=\"0\" cellspacing=\"0\" style=\"margin-top:5px;\">\r\n	<tr><form action=\"/page.jsp\" method=\"get\">\r\n	<input type=\"hidden\" name=\"date\" value=\"".getBytes("Cp1251");
      _jsp_string41 = "/tvschedule/announce?announce_id=".getBytes("Cp1251");
      _jsp_string6 = "\">".getBytes("Cp1251");
      _jsp_string30 = "\r\n	</select><input type=\"Image\" src=\"".getBytes("Cp1251");
      _jsp_string39 = "\r\n<tr>\r\n<td valign=\"top\" width=\"184\" height=\"87\" background=\"".getBytes("Cp1251");
      _jsp_string42 = "\"><img src=\"".getBytes("Cp1251");
      _jsp_string18 = "\r\n\r\n<table width=\"100%\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" style=\"margin-top:8px;\">\r\n<tr><form action=\"\">\r\n<td>\r\n<a href=\"/pages/".getBytes("Cp1251");
      _jsp_string36 = "</SPAN>\r\n</td>\r\n</tr>\r\n\r\n<tr valign=\"top\">\r\n<td>\r\n\r\n<table border=\"0\" width=\"100%\" cellpadding=\"0\" cellspacing=\"0\" style=\"margin-top:8px\">\r\n".getBytes("Cp1251");
      _jsp_string65 = "</SPAN><img src=\"".getBytes("Cp1251");
      _jsp_string62 = "/2lev/arr-grn-prew.gif\" width=\"9\" height=\"5\" alt=\"\" border=\"0\" hspace=\"4\"><SPAN class=\"grnTtl\">".getBytes("Cp1251");
      _jsp_string57 = "/greyln.gif\"><SPACER TYPE=\"block\" HEIGHT=\"1\" WIDTH=\"1\"></td></tr>\r\n".getBytes("Cp1251");
      _jsp_string40 = "/tvprogram/bg-m-pic.gif\"><div style=\"padding-left:53px;\"><a href=\"/pages/".getBytes("Cp1251");
      _jsp_string32 = "/tvprogram/ico-fngr.gif\" width=\"11\" height=\"11\" alt=\"\" border=\"0\" hspace=\"5\"><b class=\"grnTtl\">В этот день</b>\r\n</td>\r\n<td></td>\r\n<td bgcolor=\"#DDF3E1\" class=\"defFont\"><a href=\"/tvschedule/schedule_prn.jsp?date=".getBytes("Cp1251");
      _jsp_string24 = "\">\r\n	<td class=\"defFont\"><SPAN class=\"bluTtl\">Выберите часовой пояс:</SPAN>&nbsp;</td>\r\n	<td class=\"SELnn\">\r\n	<NOBR><select name=\"show_place_id\" style=\"width:205;font-size:10px;font-family:Tahoma;\" width=\"200\">\r\n".getBytes("Cp1251");
      _jsp_string59 = "\r\n<table border=\"0\" cellpadding=\"0\" cellspacing=\"0\" width=\"100%\" style=\"margin-top:8px;\">\r\n<tr>\r\n	<td class=\"smallFont\"><a href=\"/pages/".getBytes("Cp1251");
      _jsp_string2 = "\r\n\r\n\r\n\r\n\r\n".getBytes("Cp1251");
      _jsp_string51 = "\r\n<table width=\"100%\" border=\"0\" cellpadding=\"2\" cellspacing=\"0\" style=\"margin-top:8px\">\r\n".getBytes("Cp1251");
      _jsp_string7 = "</a> /\r\n".getBytes("Cp1251");
      _jsp_string0 = "\r\n".getBytes("Cp1251");
      _jsp_string58 = "\r\n</table>\r\n".getBytes("Cp1251");
      _jsp_string33 = "&days=1\" target=\"_blank\"><img src=\"".getBytes("Cp1251");
      _jsp_string12 = "\" border=\"0\"></td>\r\n</tr>\r\n</table>\r\n\r\n\r\n".getBytes("Cp1251");
      _jsp_string63 = "</SPAN></a></td>\r\n	<td align=\"right\" class=\"smallFont\"><a href=\"/pages/".getBytes("Cp1251");
      _jsp_string21 = "&days=7\" target=\"_blank\"><img src=\"".getBytes("Cp1251");
      _jsp_string49 = "\r\n<tr><td height=\"12\"></td></tr>\r\n".getBytes("Cp1251");
      _jsp_string29 = "</option>\r\n".getBytes("Cp1251");
      _jsp_string44 = "\" class=\"nonUa\">\r\n<div style=\"margin:5px;line-height:130%;\">\r\n<SPAN class=\"grn\">".getBytes("Cp1251");
      _jsp_string25 = "\r\n	<option value=\"".getBytes("Cp1251");
      _jsp_string34 = "/tvprogram/btn-prnt.gif\" width=\"101\" height=\"10\" alt=\"Версия для печати\" border=\"0\" align=\"right\" hspace=\"5\" vspace=\"2\"></a>\r\n&nbsp;<img src=\"".getBytes("Cp1251");
      _jsp_string3 = "\r\n\r\n<table width=\"100%\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\">\r\n<tr>\r\n<td width=\"100%\" valign=\"top\" class=\"XsmallFont\">\r\n".getBytes("Cp1251");
      _jsp_string5 = "  \r\n<a href=\"".getBytes("Cp1251");
      _jsp_string66 = "/2lev/arr-grn-forw.gif\" width=\"9\" height=\"5\" alt=\"\" border=\"0\" hspace=\"4\"></a></td>\r\n</tr>\r\n</table>\r\n".getBytes("Cp1251");
      _jsp_string52 = "\r\n<tr valign=\"top\">\r\n	<td style=\"background:#FFFFFF url(".getBytes("Cp1251");
      _jsp_string64 = "\" class=\"nonUa\"><SPAN class=\"grnTtl\">".getBytes("Cp1251");
      _jsp_string37 = "\r\n<tr>\r\n<td height=\"20\" bgcolor=\"#DDF3E1\" class=\"defFont\">\r\n&nbsp;<img src=\"".getBytes("Cp1251");
      _jsp_string38 = "/tvprogram/ico-fngr.gif\" width=\"11\" height=\"11\" alt=\"\" border=\"0\" hspace=\"5\"><b class=\"grnTtl\">На следующий день</b>\r\n</td>\r\n</tr>\r\n<tr><td height=\"8\"></td></tr>\r\n".getBytes("Cp1251");
      _jsp_string46 = "</b><br>\r\n".getBytes("Cp1251");
      _jsp_string43 = "\" width=\"77\" height=\"58\" alt=\"\" border=\"0\"></a></div></td>\r\n</tr>\r\n<tr>\r\n<td align=\"center\" class=\"smallFont\">\r\n<a href=\"/pages/".getBytes("Cp1251");
      _jsp_string67 = "\r\n\r\n</td>\r\n</tr>\r\n</table>\r\n".getBytes("Cp1251");
      _jsp_string60 = "/tvschedule?date=".getBytes("Cp1251");
      _jsp_string1 = "\r\n\r\n".getBytes("Cp1251");
      _jsp_string8 = "\r\n</div>\r\n".getBytes("Cp1251");
      _jsp_string48 = "/ar.gif\" width=\"9\" height=\"7\" border=\"0\"><br>\r\n</div>\r\n</a>\r\n</td>\r\n</tr>\r\n".getBytes("Cp1251");
    } catch (java.io.UnsupportedEncodingException e) {
      e.printStackTrace();
    }
  }
}
