/*
 * JSP generated by Resin 2.0.5 (built Thu Jan 10 21:43:38 PST 2002)
 */

package _forum;
import javax.servlet.*;
import javax.servlet.jsp.*;
import javax.servlet.http.*;
import java.io.*;
import java.util.*;
import tengry.cms.forum.*;
import tengry.cms.*;
import tengry.cms.db.*;
import tengry.cms.core.*;
import tengry.cms.user.*;
import tengry.cms.mailer.*;

public class _forum__jsp extends com.caucho.jsp.JavaPage{
  private boolean _caucho_isDead;
  
public String nodePath(WebTreeNode node)
{
    if(node == null)
        return "/pages";
    return nodePath(node.getParent()) + "/" + node.getCode();
}

public String nodePath(String nodeId)
{
    return nodePath(CMSApplication.getApplication().lookup(nodeId));
}

  
	void printPagebar(int pageNumber, int pageSize, int count, String href, JspWriter out) 
		throws java.io.IOException
	{
		out.print("<b>На страницу:</b> ");

		int pages = 1 + (count - 1)/pageSize;
		for(int i = 1; i <= pages; i++)
		{
			if(i > 1)
				out.print(", ");
				
		    if(i == 4 && pageNumber > 6)
		    {
		        out.print("...");
	            i = pageNumber-2;
		        continue;
		    }
            if(i == pageNumber + 2 && pages-pageNumber > 5)
            {
		        out.print("...");
	            i = pages-2;
	            continue;
	        }
		    
			if(i != pageNumber)
				out.print("<a href=\"" + href + "&page_number=" + i + "\">" + i + "</a>");
			else
				out.print("" + i);
		}
		if(pageNumber < pages)
		    out.print(" <a href=\"\">След</a>.");
	}

  
  public void
  _jspService(javax.servlet.http.HttpServletRequest request,
              javax.servlet.http.HttpServletResponse response)
    throws java.io.IOException, javax.servlet.ServletException
  {
    com.caucho.jsp.QPageContext pageContext = (com.caucho.jsp.QPageContext) com.caucho.jsp.QJspFactory.create().getPageContext(this, request, response, null, true, 8192, true);
    javax.servlet.jsp.JspWriter out = (javax.servlet.jsp.JspWriter) pageContext.getOut();
    javax.servlet.ServletConfig config = getServletConfig();
    javax.servlet.Servlet page = this;
    javax.servlet.http.HttpSession session = pageContext.getSession();
    javax.servlet.ServletContext application = pageContext.getServletContext();
    response.setContentType("text/html; charset=windows-1251");
    request.setCharacterEncoding("CP1251");
    try {
      pageContext.write(_jsp_string0, 0, _jsp_string0.length);
      pageContext.write(_jsp_string0, 0, _jsp_string0.length);
      pageContext.write(_jsp_string0, 0, _jsp_string0.length);
      pageContext.write(_jsp_string0, 0, _jsp_string0.length);
      pageContext.write(_jsp_string0, 0, _jsp_string0.length);
      pageContext.write(_jsp_string0, 0, _jsp_string0.length);
      pageContext.write(_jsp_string0, 0, _jsp_string0.length);
      pageContext.write(_jsp_string0, 0, _jsp_string0.length);
      pageContext.write(_jsp_string0, 0, _jsp_string0.length);
      pageContext.write(_jsp_string0, 0, _jsp_string0.length);
      
	String      langCode        = null;
	String      pageId          = null;
	String      des             = null;
    User        user            = null;

    langCode = request.getParameter("lang_code");
    if(langCode == null || langCode.trim().length() == 0)
        langCode = CMSApplication.getApplication().getPrimaryLangCode();

	des = CMSApplication.getApplication().getCurrentDesignPath() + "/" + langCode;

	pageId = request.getParameter("id");
	if("".equals(pageId))
		pageId = null;
		
    user = (User)session.getAttribute("ntvmir.user");
    if(user == null)
    {
        String usrid = CMSApplication.getCookie(request, "user.id");
        if(usrid != null && usrid.length() > 0)
        {
            try
            {
                user = User.quickAuthorize(usrid);
            }catch(Exception e){}
        }
    }

	boolean     adminPreview    = false;
	Hashtable   previewInfo     = null;
	adminPreview = (session.getValue("admin.user") != null && "1".equals(request.getParameter("preview")));
	
	previewInfo = (Hashtable)session.getAttribute("admin.previewinfo");
	if(!adminPreview)
		previewInfo = null;

      pageContext.write(_jsp_string1, 0, _jsp_string1.length);
      pageContext.write(_jsp_string0, 0, _jsp_string0.length);
      pageContext.write(_jsp_string0, 0, _jsp_string0.length);
        response.setHeader("Pragma","no-cache"); 
      pageContext.write(_jsp_string0, 0, _jsp_string0.length);
      
	Vector pagePath = new Vector();
	String sectionImg = "company";
	String sectionName = "О компании";
	if(pageId != null)
	{
	    WebTreeNode treeNode = CMSApplication.getApplication().lookup(pageId);
	    while(treeNode != null && treeNode.getParent() != null)
	    {
	        pagePath.insertElementAt(treeNode, 0);
	        sectionImg = treeNode.getCode();
	        sectionName = treeNode.getName();
	        treeNode = treeNode.getParent();
	    }
	}
	if(adminPreview && previewInfo != null)
	{
	    sectionImg = (String)previewInfo.get("section");
	    if(sectionImg == null)
	        sectionImg = "about";
	    
	}
	if("about".equals(sectionImg))
	    sectionImg = "company";
	else if("tvschedule".equals(sectionImg))
	    sectionImg = "tvprogram";
	else if("auth".equals(sectionImg))
	    sectionImg = "authorization";

      pageContext.write(_jsp_string0, 0, _jsp_string0.length);
      
    String forumId = request.getParameter("forum_id");
    String themeId = request.getParameter("theme_id");
    String create = request.getParameter("create");
    String edit = request.getParameter("edit");
    if("".equals(forumId))
        forumId = null;
try
{
    if(forumId != null && ("1".equals(create) || "1".equals(edit)))
    {

      pageContext.write(_jsp_string0, 0, _jsp_string0.length);
      
    Forum       forum   = new Forum();
    ForumGroup  group   = new ForumGroup();
    ForumItem   theme   = null;
    ForumItem   cite    = null;
    ForumItem   item    = null;
    
    
    String citeId = request.getParameter("cite_id");
    String itemId = request.getParameter("item_id");
    String citeLogin = request.getParameter("cite_login");
    if(citeLogin == null)
        citeLogin = "";
        
    forum.load(forumId);
    if(forum != null)
        group.load(forum.getForumGroupId());
    if(themeId != null)
    {
        theme = new ForumItem();
        theme.load(themeId);
    }
    
    boolean isModerator = (user != null && !user.isDisabled() && forum != null && forum.isModerator(user.getId()));
    boolean visibleOnly = !isModerator;

    if(forum != null && group != null &&
        forum.isVisible() && group.isVisible() && (theme == null || theme.getPublicDate() != null || isModerator))
    {
        if(citeId != null && citeId.length() > 0)
        {
            cite = new ForumItem();
            cite.load(citeId);
            if(!cite.isPublic() && ! isModerator)
                cite = null;
        }
        if(itemId != null && itemId.length() > 0)
        {
            item = new ForumItem();
            item.load(itemId);
        }
        
        String text = "";
        if(item != null)
            text = CMSApplication.toHTML(item.getText());
		            
        else if(cite != null)
            text = "\n[cite]\n[b]" + CMSApplication.toHTML(citeLogin) + " писал(а):[/b]\n" + CMSApplication.toHTML(cite.getText()) + "[/cite]\n";
        if(user != null)
            text += CMSApplication.toHTML(user.getForumSign());

      pageContext.write(_jsp_string2, 0, _jsp_string2.length);
      
    if(pagePath.size() > 1)
    {

      pageContext.write(_jsp_string3, 0, _jsp_string3.length);
        
        for(int i = 0; i < pagePath.size(); i++)
        {
            WebTreeNode treeNode = (WebTreeNode)pagePath.elementAt(i);
            if(i+1 == pagePath.size())
                out.println(CMSApplication.toHTML(treeNode.getName()));
            else
            {

      pageContext.write(_jsp_string4, 0, _jsp_string4.length);
      out.print((nodePath(treeNode)));
      pageContext.write(_jsp_string5, 0, _jsp_string5.length);
      out.print((CMSApplication.toHTML(treeNode.getName())));
      pageContext.write(_jsp_string6, 0, _jsp_string6.length);
      
            }
        }

      pageContext.write(_jsp_string7, 0, _jsp_string7.length);
        } 
      pageContext.write(_jsp_string8, 0, _jsp_string8.length);
      out.print((des));
      pageContext.write(_jsp_string9, 0, _jsp_string9.length);
      out.print((sectionImg));
      pageContext.write(_jsp_string10, 0, _jsp_string10.length);
      out.print((sectionName));
      pageContext.write(_jsp_string11, 0, _jsp_string11.length);
      pageContext.write(_jsp_string12, 0, _jsp_string12.length);
      out.print((des));
      pageContext.write(_jsp_string13, 0, _jsp_string13.length);
      out.print((des));
      pageContext.write(_jsp_string14, 0, _jsp_string14.length);
      out.print((des));
      pageContext.write(_jsp_string15, 0, _jsp_string15.length);
      out.print((des));
      pageContext.write(_jsp_string16, 0, _jsp_string16.length);
      pageContext.write(_jsp_string1, 0, _jsp_string1.length);
      
    String header = "";
    if(item != null)
        header = CMSApplication.toHTML(item.getHeader());
    else if(theme != null)
        header = "Re: " + CMSApplication.toHTML(theme.getHeader());

      pageContext.write(_jsp_string1, 0, _jsp_string1.length);
      pageContext.write(_jsp_string17, 0, _jsp_string17.length);
      out.print((forumId));
      pageContext.write(_jsp_string18, 0, _jsp_string18.length);
      out.print((themeId != null ? themeId : ""));
      pageContext.write(_jsp_string19, 0, _jsp_string19.length);
        if(item != null){ 
      pageContext.write(_jsp_string20, 0, _jsp_string20.length);
      out.print((item.getId()));
      pageContext.write(_jsp_string19, 0, _jsp_string19.length);
        } 
      pageContext.write(_jsp_string21, 0, _jsp_string21.length);
      out.print((header));
      pageContext.write(_jsp_string22, 0, _jsp_string22.length);
      out.print((des));
      pageContext.write(_jsp_string23, 0, _jsp_string23.length);
      out.print((des));
      pageContext.write(_jsp_string24, 0, _jsp_string24.length);
      out.print((des));
      pageContext.write(_jsp_string25, 0, _jsp_string25.length);
      out.print((des));
      pageContext.write(_jsp_string26, 0, _jsp_string26.length);
      out.print((des));
      pageContext.write(_jsp_string27, 0, _jsp_string27.length);
      out.print((des));
      pageContext.write(_jsp_string28, 0, _jsp_string28.length);
      out.print((des));
      pageContext.write(_jsp_string29, 0, _jsp_string29.length);
      out.print((des));
      pageContext.write(_jsp_string30, 0, _jsp_string30.length);
      out.print((des));
      pageContext.write(_jsp_string31, 0, _jsp_string31.length);
      out.print((des));
      pageContext.write(_jsp_string32, 0, _jsp_string32.length);
      out.print((des));
      pageContext.write(_jsp_string33, 0, _jsp_string33.length);
      out.print((des));
      pageContext.write(_jsp_string34, 0, _jsp_string34.length);
      out.print((des));
      pageContext.write(_jsp_string35, 0, _jsp_string35.length);
      out.print((des));
      pageContext.write(_jsp_string36, 0, _jsp_string36.length);
      out.print((des));
      pageContext.write(_jsp_string37, 0, _jsp_string37.length);
      out.print((des));
      pageContext.write(_jsp_string38, 0, _jsp_string38.length);
      out.print((text));
      pageContext.write(_jsp_string39, 0, _jsp_string39.length);
      out.print((des));
      pageContext.write(_jsp_string40, 0, _jsp_string40.length);
      out.print((des));
      pageContext.write(_jsp_string41, 0, _jsp_string41.length);
      out.print((des));
      pageContext.write(_jsp_string42, 0, _jsp_string42.length);
      pageContext.write(_jsp_string0, 0, _jsp_string0.length);
      pageContext.write(_jsp_string0, 0, _jsp_string0.length);
        } 
      pageContext.write(_jsp_string0, 0, _jsp_string0.length);
      
    }
    else if(forumId == null)
    {

      pageContext.write(_jsp_string0, 0, _jsp_string0.length);
      pageContext.write(_jsp_string43, 0, _jsp_string43.length);
      
    if(pagePath.size() > 1)
    {

      pageContext.write(_jsp_string3, 0, _jsp_string3.length);
        
        for(int i = 0; i < pagePath.size(); i++)
        {
            WebTreeNode treeNode = (WebTreeNode)pagePath.elementAt(i);
            if(i+1 == pagePath.size())
                out.println(CMSApplication.toHTML(treeNode.getName()));
            else
            {

      pageContext.write(_jsp_string4, 0, _jsp_string4.length);
      out.print((nodePath(treeNode)));
      pageContext.write(_jsp_string5, 0, _jsp_string5.length);
      out.print((CMSApplication.toHTML(treeNode.getName())));
      pageContext.write(_jsp_string6, 0, _jsp_string6.length);
      
            }
        }

      pageContext.write(_jsp_string7, 0, _jsp_string7.length);
        } 
      pageContext.write(_jsp_string8, 0, _jsp_string8.length);
      out.print((des));
      pageContext.write(_jsp_string9, 0, _jsp_string9.length);
      out.print((sectionImg));
      pageContext.write(_jsp_string10, 0, _jsp_string10.length);
      out.print((sectionName));
      pageContext.write(_jsp_string44, 0, _jsp_string44.length);
      pageContext.write(_jsp_string12, 0, _jsp_string12.length);
      out.print((des));
      pageContext.write(_jsp_string13, 0, _jsp_string13.length);
      out.print((des));
      pageContext.write(_jsp_string14, 0, _jsp_string14.length);
      out.print((des));
      pageContext.write(_jsp_string15, 0, _jsp_string15.length);
      out.print((des));
      pageContext.write(_jsp_string16, 0, _jsp_string16.length);
      pageContext.write(_jsp_string0, 0, _jsp_string0.length);
      pageContext.write(_jsp_string45, 0, _jsp_string45.length);
      
    java.text.SimpleDateFormat sdf = new java.text.SimpleDateFormat("dd.MM.yyyy HH:mm");
    Hashtable forumHash = Forum.getForums(langCode, true);
    Enumeration groups = ForumGroup.getForumGroups(langCode, true).elements();
    boolean firstLoop1 = true;
	while(groups.hasMoreElements())
	{
    	ForumGroup group = (ForumGroup)groups.nextElement();
    	if(firstLoop1)
    	    firstLoop1 = false;
    	else
    	{

      pageContext.write(_jsp_string46, 0, _jsp_string46.length);
            } 
      pageContext.write(_jsp_string0, 0, _jsp_string0.length);
      pageContext.write(_jsp_string47, 0, _jsp_string47.length);
      out.print((CMSApplication.toHTML(group.getName())));
      pageContext.write(_jsp_string48, 0, _jsp_string48.length);
      pageContext.write(_jsp_string49, 0, _jsp_string49.length);
      
        java.text.SimpleDateFormat forumSdf = new java.text.SimpleDateFormat("dd.MM.yyyy-HH.mm.ss");
        Vector vf = (Vector)forumHash.get(group.getId());
        if(vf == null)
            vf = new Vector();
        Enumeration enum = vf.elements();
        boolean firstLoop2 = true;
        while(enum.hasMoreElements())
        {
            Forum forum = (Forum)enum.nextElement();
            Date lastMessageDate = forum.getLastMessageDate();
            Date lastForumVisitDate = null;

            try
            {
                String sLastForumVisitDate = CMSApplication.getCookie(request, "forum.last_view." + forum.getId());
                lastForumVisitDate = forumSdf.parse(sLastForumVisitDate);
                
            }
            catch(Exception e)
            {
                lastForumVisitDate = null;
            }
            
            if(lastMessageDate == null)
                lastMessageDate = new Date();
             
		    if(firstLoop2)
		        firstLoop2 = false;
		    else
		    {

      pageContext.write(_jsp_string50, 0, _jsp_string50.length);
      out.print((des));
      pageContext.write(_jsp_string51, 0, _jsp_string51.length);
      out.print((des));
      pageContext.write(_jsp_string52, 0, _jsp_string52.length);
                } 
      pageContext.write(_jsp_string0, 0, _jsp_string0.length);
      pageContext.write(_jsp_string53, 0, _jsp_string53.length);
      out.print((des));
      pageContext.write(_jsp_string54, 0, _jsp_string54.length);
      out.print((langCode));
      pageContext.write(_jsp_string55, 0, _jsp_string55.length);
      out.print((forum.getId()));
      pageContext.write(_jsp_string56, 0, _jsp_string56.length);
      out.print((CMSApplication.toHTML(forum.getName())));
      pageContext.write(_jsp_string57, 0, _jsp_string57.length);
        if((lastForumVisitDate == null || lastForumVisitDate.before(lastMessageDate)) && forum.getThemeAmount() > 0)
    {

      pageContext.write(_jsp_string58, 0, _jsp_string58.length);
      out.print((des));
      pageContext.write(_jsp_string59, 0, _jsp_string59.length);
      
	} 

      pageContext.write(_jsp_string60, 0, _jsp_string60.length);
      out.print((CMSApplication.toHTML(forum.getDescription())));
      pageContext.write(_jsp_string61, 0, _jsp_string61.length);
      out.print((forum.getThemeAmount()));
      pageContext.write(_jsp_string61, 0, _jsp_string61.length);
      out.print((forum.getMessageAmount()));
      
if(user != null && forum.isModerator(user.getId())  && !user.isDisabled())
{
    out.println("<br> (новых &#151; " + (forum.getAllMessageAmount() - forum.getMessageAmount()) + ")");
}
	
      pageContext.write(_jsp_string62, 0, _jsp_string62.length);
      out.print((des));
      pageContext.write(_jsp_string63, 0, _jsp_string63.length);
        if(forum.getThemeAmount() > 0){ 
      pageContext.write(_jsp_string64, 0, _jsp_string64.length);
      out.print((sdf.format(lastMessageDate)));
      pageContext.write(_jsp_string65, 0, _jsp_string65.length);
      out.print((langCode));
      pageContext.write(_jsp_string66, 0, _jsp_string66.length);
      out.print((CMSApplication.toHTML(forum.getLastMessageLogin())));
      pageContext.write(_jsp_string67, 0, _jsp_string67.length);
      out.print((CMSApplication.toHTML(forum.getLastMessageLogin())));
      pageContext.write(_jsp_string68, 0, _jsp_string68.length);
        } 
      pageContext.write(_jsp_string69, 0, _jsp_string69.length);
      pageContext.write(_jsp_string0, 0, _jsp_string0.length);
      
        }
    }

      pageContext.write(_jsp_string70, 0, _jsp_string70.length);
      pageContext.write(_jsp_string0, 0, _jsp_string0.length);
      pageContext.write(_jsp_string0, 0, _jsp_string0.length);
      
    }
    else if(themeId == null)
    {

      pageContext.write(_jsp_string0, 0, _jsp_string0.length);
      
    Forum forum = new Forum();
    ForumGroup group = new ForumGroup();    
    forum.load(forumId);
    if(forum != null)
        group.load(forum.getForumGroupId());

    if(forum != null && group != null && forum.isVisible() && group.isVisible())
    {
        int pageNumber = 1;
        int pageSize = 10;
        try{ pageNumber = Integer.parseInt(request.getParameter("page_number")); }catch(Exception e){}

        Date startDate = null;
        String  showPeriod = request.getParameter("period");
        
        Calendar cal = Calendar.getInstance();
        cal.setTime(new Date());
        
        if("1".equals(showPeriod))
            cal.add(Calendar.DATE, -1);
        else if("2".equals(showPeriod))
            cal.add(Calendar.DATE, -7);
        else if("3".equals(showPeriod))
            cal.add(Calendar.MONTH, -1);
        else if("4".equals(showPeriod))
            cal.add(Calendar.MONTH, -6);
        else if("5".equals(showPeriod))
            cal.add(Calendar.MONTH, -12);
        else {
            cal = null;
            showPeriod = "0";
        }

        if(cal != null)
            startDate = cal.getTime();
        
        boolean isModerator = (user != null && forum.isModerator(user.getId())  && !user.isDisabled());
        
        boolean visibleOnly = !isModerator;
        
        String href = "/pages/" + langCode + "/forum/?forum_id=" + forumId + "&period=" + showPeriod;
        int num = ForumItem.getForumItemNum(forumId, startDate, visibleOnly);
        
        Enumeration enum = ForumItem.getForumItems(forumId, startDate, pageNumber, pageSize, visibleOnly).elements();
        java.text.SimpleDateFormat sdf = new java.text.SimpleDateFormat("dd.MM.yyyy HH:mm");

      pageContext.write(_jsp_string71, 0, _jsp_string71.length);
        
        for(int i = 0; i < pagePath.size(); i++)
        {
            WebTreeNode treeNode = (WebTreeNode)pagePath.elementAt(i);

      pageContext.write(_jsp_string4, 0, _jsp_string4.length);
      out.print((nodePath(treeNode)));
      pageContext.write(_jsp_string5, 0, _jsp_string5.length);
      out.print((CMSApplication.toHTML(treeNode.getName())));
      pageContext.write(_jsp_string6, 0, _jsp_string6.length);
      
        }

      pageContext.write(_jsp_string0, 0, _jsp_string0.length);
      out.print((CMSApplication.toHTML(forum.getName())));
      pageContext.write(_jsp_string72, 0, _jsp_string72.length);
      out.print((des));
      pageContext.write(_jsp_string9, 0, _jsp_string9.length);
      out.print((sectionImg));
      pageContext.write(_jsp_string10, 0, _jsp_string10.length);
      out.print((sectionName));
      pageContext.write(_jsp_string73, 0, _jsp_string73.length);
      pageContext.write(_jsp_string12, 0, _jsp_string12.length);
      out.print((des));
      pageContext.write(_jsp_string13, 0, _jsp_string13.length);
      out.print((des));
      pageContext.write(_jsp_string14, 0, _jsp_string14.length);
      out.print((des));
      pageContext.write(_jsp_string15, 0, _jsp_string15.length);
      out.print((des));
      pageContext.write(_jsp_string16, 0, _jsp_string16.length);
      pageContext.write(_jsp_string1, 0, _jsp_string1.length);
      pageContext.write(_jsp_string74, 0, _jsp_string74.length);
      out.print((CMSApplication.toHTML(forum.getName())));
      pageContext.write(_jsp_string75, 0, _jsp_string75.length);
      out.print((des));
      pageContext.write(_jsp_string76, 0, _jsp_string76.length);
      out.print((num));
      pageContext.write(_jsp_string77, 0, _jsp_string77.length);
      printPagebar(pageNumber, pageSize, num, href, out);
      pageContext.write(_jsp_string78, 0, _jsp_string78.length);
      pageContext.write(_jsp_string1, 0, _jsp_string1.length);
      pageContext.write(_jsp_string79, 0, _jsp_string79.length);
      out.print((langCode));
      pageContext.write(_jsp_string80, 0, _jsp_string80.length);
      out.print((forumId));
      pageContext.write(_jsp_string19, 0, _jsp_string19.length);
        if(user != null && !user.isDisabled()){ 
      pageContext.write(_jsp_string81, 0, _jsp_string81.length);
      out.print((langCode));
      pageContext.write(_jsp_string55, 0, _jsp_string55.length);
      out.print((forumId));
      pageContext.write(_jsp_string82, 0, _jsp_string82.length);
      out.print((des));
      pageContext.write(_jsp_string83, 0, _jsp_string83.length);
        } 
      pageContext.write(_jsp_string84, 0, _jsp_string84.length);
      out.print(("0".equals(showPeriod) ? " SELECTED":""));
      pageContext.write(_jsp_string85, 0, _jsp_string85.length);
      out.print(("1".equals(showPeriod) ? " SELECTED":""));
      pageContext.write(_jsp_string86, 0, _jsp_string86.length);
      out.print(("2".equals(showPeriod) ? " SELECTED":""));
      pageContext.write(_jsp_string87, 0, _jsp_string87.length);
      out.print(("3".equals(showPeriod) ? " SELECTED":""));
      pageContext.write(_jsp_string88, 0, _jsp_string88.length);
      out.print(("4".equals(showPeriod) ? " SELECTED":""));
      pageContext.write(_jsp_string89, 0, _jsp_string89.length);
      out.print(("5".equals(showPeriod) ? " SELECTED":""));
      pageContext.write(_jsp_string90, 0, _jsp_string90.length);
      out.print((des));
      pageContext.write(_jsp_string91, 0, _jsp_string91.length);
      pageContext.write(_jsp_string92, 0, _jsp_string92.length);
      pageContext.write(_jsp_string93, 0, _jsp_string93.length);
      pageContext.write(_jsp_string94, 0, _jsp_string94.length);
      





    java.text.SimpleDateFormat forumSdf = new java.text.SimpleDateFormat("dd.MM.yyyy-HH.mm.ss");
        
    Date lastForumVisitDate = null;
    try
    {
        String sLastForumVisitDate = CMSApplication.getCookie(request, "forum.last_view." + forum.getId());
        lastForumVisitDate = forumSdf.parse(sLastForumVisitDate);
                
    }
    catch(Exception e)
    {
        lastForumVisitDate = null;
    }
                

    while(enum.hasMoreElements())
    {
        ForumItem theme = (ForumItem)enum.nextElement();
        Date lastMessageDate = theme.getLastMessageDate();
        if(lastMessageDate == null)
            lastMessageDate = new Date();

      pageContext.write(_jsp_string0, 0, _jsp_string0.length);
      pageContext.write(_jsp_string95, 0, _jsp_string95.length);
      out.print((langCode));
      pageContext.write(_jsp_string55, 0, _jsp_string55.length);
      out.print((forum.getId()));
      pageContext.write(_jsp_string96, 0, _jsp_string96.length);
      out.print((theme.getId()));
      pageContext.write(_jsp_string5, 0, _jsp_string5.length);
      
if(theme.getStatus() == ForumItem.CLOSED_THEME){

      pageContext.write(_jsp_string97, 0, _jsp_string97.length);
      out.print((des));
      pageContext.write(_jsp_string98, 0, _jsp_string98.length);
      
}else if(theme.getStatus() == ForumItem.HOT_THEME || theme.getStatus() == ForumItem.MAIN_PAGE_THEME){

      pageContext.write(_jsp_string97, 0, _jsp_string97.length);
      out.print((des));
      pageContext.write(_jsp_string99, 0, _jsp_string99.length);
      
}else{

      pageContext.write(_jsp_string97, 0, _jsp_string97.length);
      out.print((des));
      pageContext.write(_jsp_string100, 0, _jsp_string100.length);
      
} 

      pageContext.write(_jsp_string101, 0, _jsp_string101.length);
      out.print((langCode));
      pageContext.write(_jsp_string55, 0, _jsp_string55.length);
      out.print((forum.getId()));
      pageContext.write(_jsp_string96, 0, _jsp_string96.length);
      out.print((theme.getId()));
      pageContext.write(_jsp_string56, 0, _jsp_string56.length);
      out.print((CMSApplication.toHTML(theme.getHeader())));
      pageContext.write(_jsp_string102, 0, _jsp_string102.length);
        if((lastForumVisitDate == null || lastForumVisitDate.before(lastMessageDate)))
    {

      pageContext.write(_jsp_string58, 0, _jsp_string58.length);
      out.print((des));
      pageContext.write(_jsp_string59, 0, _jsp_string59.length);
      
	} 

      pageContext.write(_jsp_string103, 0, _jsp_string103.length);
      
    int publAmount = theme.getAnswerAmount();
    if(theme.isPublic())
        publAmount ++;

    int allAmount = theme.getAllAnswerAmount() + 1;
        

      pageContext.write(_jsp_string104, 0, _jsp_string104.length);
      out.print((des));
      pageContext.write(_jsp_string105, 0, _jsp_string105.length);
      out.print((sdf.format(lastMessageDate)));
      pageContext.write(_jsp_string65, 0, _jsp_string65.length);
      out.print((langCode));
      pageContext.write(_jsp_string66, 0, _jsp_string66.length);
      out.print((CMSApplication.toHTML(theme.getLastMessageLogin())));
      pageContext.write(_jsp_string67, 0, _jsp_string67.length);
      out.print((CMSApplication.toHTML(theme.getLastMessageLogin())));
      pageContext.write(_jsp_string106, 0, _jsp_string106.length);
      out.print((langCode));
      pageContext.write(_jsp_string66, 0, _jsp_string66.length);
      out.print((CMSApplication.toHTML(theme.getUserLogin())));
      pageContext.write(_jsp_string67, 0, _jsp_string67.length);
      out.print((CMSApplication.toHTML(theme.getUserLogin())));
      pageContext.write(_jsp_string107, 0, _jsp_string107.length);
      out.print((publAmount));
      
	if(isModerator){
	    out.println("<br>(новых &#151 " + (allAmount - publAmount) + ")");
	}
	
      pageContext.write(_jsp_string61, 0, _jsp_string61.length);
      out.print((theme.getViewCount()));
      pageContext.write(_jsp_string108, 0, _jsp_string108.length);
      out.print((des));
      pageContext.write(_jsp_string109, 0, _jsp_string109.length);
      
    int themePages = (theme.getAnswerAmount()+1) / pageSize + 1;
    for(int i = 1; i <= themePages; i++)
    {

      pageContext.write(_jsp_string110, 0, _jsp_string110.length);
      out.print((langCode));
      pageContext.write(_jsp_string55, 0, _jsp_string55.length);
      out.print((forum.getId()));
      pageContext.write(_jsp_string96, 0, _jsp_string96.length);
      out.print((theme.getId()));
      pageContext.write(_jsp_string111, 0, _jsp_string111.length);
      out.print((i));
      pageContext.write(_jsp_string5, 0, _jsp_string5.length);
      out.print((i));
      pageContext.write(_jsp_string112, 0, _jsp_string112.length);
      out.print(( i== themePages ? "":", "));
      pageContext.write(_jsp_string0, 0, _jsp_string0.length);
        } 
      pageContext.write(_jsp_string113, 0, _jsp_string113.length);
      pageContext.write(_jsp_string1, 0, _jsp_string1.length);
                if(isModerator)
            {

      pageContext.write(_jsp_string114, 0, _jsp_string114.length);
                if(theme.getPublicDate() != null)
            {
                if(theme.getStatus() == ForumItem.SIMPLE_THEME || theme.getStatus() == ForumItem.HOT_THEME){ 
      pageContext.write(_jsp_string115, 0, _jsp_string115.length);
      out.print((forumId));
      pageContext.write(_jsp_string96, 0, _jsp_string96.length);
      out.print((theme.getId()));
      pageContext.write(_jsp_string116, 0, _jsp_string116.length);
                    } 
      pageContext.write(_jsp_string0, 0, _jsp_string0.length);
                    if(theme.getStatus() == ForumItem.SIMPLE_THEME){ 
      pageContext.write(_jsp_string117, 0, _jsp_string117.length);
      out.print((forumId));
      pageContext.write(_jsp_string96, 0, _jsp_string96.length);
      out.print((theme.getId()));
      pageContext.write(_jsp_string118, 0, _jsp_string118.length);
                    } 
      pageContext.write(_jsp_string0, 0, _jsp_string0.length);
                    if(theme.getStatus() == ForumItem.HOT_THEME){ 
      pageContext.write(_jsp_string119, 0, _jsp_string119.length);
      out.print((forumId));
      pageContext.write(_jsp_string96, 0, _jsp_string96.length);
      out.print((theme.getId()));
      pageContext.write(_jsp_string120, 0, _jsp_string120.length);
                    }
            }
            else
            {

      pageContext.write(_jsp_string121, 0, _jsp_string121.length);
                } 
      pageContext.write(_jsp_string122, 0, _jsp_string122.length);
      
            } 

      pageContext.write(_jsp_string123, 0, _jsp_string123.length);
      out.print((des));
      pageContext.write(_jsp_string124, 0, _jsp_string124.length);
        } 
      pageContext.write(_jsp_string125, 0, _jsp_string125.length);
      pageContext.write(_jsp_string126, 0, _jsp_string126.length);
      out.print((langCode));
      pageContext.write(_jsp_string80, 0, _jsp_string80.length);
      out.print((forumId));
      pageContext.write(_jsp_string19, 0, _jsp_string19.length);
        if(user != null && !user.isDisabled()){ 
      pageContext.write(_jsp_string127, 0, _jsp_string127.length);
      out.print((langCode));
      pageContext.write(_jsp_string55, 0, _jsp_string55.length);
      out.print((forumId));
      pageContext.write(_jsp_string82, 0, _jsp_string82.length);
      out.print((des));
      pageContext.write(_jsp_string83, 0, _jsp_string83.length);
        } 
      pageContext.write(_jsp_string128, 0, _jsp_string128.length);
      out.print(("0".equals(showPeriod) ? " SELECTED":""));
      pageContext.write(_jsp_string85, 0, _jsp_string85.length);
      out.print(("1".equals(showPeriod) ? " SELECTED":""));
      pageContext.write(_jsp_string86, 0, _jsp_string86.length);
      out.print(("2".equals(showPeriod) ? " SELECTED":""));
      pageContext.write(_jsp_string87, 0, _jsp_string87.length);
      out.print(("3".equals(showPeriod) ? " SELECTED":""));
      pageContext.write(_jsp_string88, 0, _jsp_string88.length);
      out.print(("4".equals(showPeriod) ? " SELECTED":""));
      pageContext.write(_jsp_string89, 0, _jsp_string89.length);
      out.print(("5".equals(showPeriod) ? " SELECTED":""));
      pageContext.write(_jsp_string90, 0, _jsp_string90.length);
      out.print((des));
      pageContext.write(_jsp_string91, 0, _jsp_string91.length);
      pageContext.write(_jsp_string1, 0, _jsp_string1.length);
      pageContext.write(_jsp_string129, 0, _jsp_string129.length);
      printPagebar(pageNumber, pageSize, num, href, out);
      pageContext.write(_jsp_string130, 0, _jsp_string130.length);
      pageContext.write(_jsp_string131, 0, _jsp_string131.length);
      pageContext.write(_jsp_string0, 0, _jsp_string0.length);
        } 
      pageContext.write(_jsp_string0, 0, _jsp_string0.length);
      
    }
    else
    {

      pageContext.write(_jsp_string0, 0, _jsp_string0.length);
      
    Forum forum = new Forum();
    ForumGroup group = new ForumGroup();
    ForumItem  theme = new ForumItem();
    theme.load(themeId);
    forum.load(forumId);
    if(forum != null)
        group.load(forum.getForumGroupId());
        
    boolean isModerator = (user != null && forum != null && forum.isModerator(user.getId()) && !user.isDisabled());
    boolean visibleOnly = !isModerator;

    if(forum != null && group != null && theme != null &&
        forum.isVisible() && group.isVisible() && (theme.getPublicDate() != null || isModerator))
    {
        try
        {
            ForumItem.increaseViewCount(themeId);
        }
        catch(Exception e){}
        
        
        int pageNumber = 1;
        int pageSize = 10;
        try{ pageNumber = Integer.parseInt(request.getParameter("page_number")); }catch(Exception e){}

        Date startDate = null;
        String  showPeriod = request.getParameter("period");
        String order = request.getParameter("order");
        
        if(!"desc".equals(order))
            order = "asc";
        Calendar cal = Calendar.getInstance();
        cal.setTime(new Date());
        
        if("1".equals(showPeriod))
            cal.add(Calendar.DATE, -1);
        else if("2".equals(showPeriod))
            cal.add(Calendar.DATE, -7);
        else if("3".equals(showPeriod))
            cal.add(Calendar.MONTH, -1);
        else if("4".equals(showPeriod))
            cal.add(Calendar.MONTH, -6);
        else if("5".equals(showPeriod))
            cal.add(Calendar.MONTH, -12);
        else {
            cal = null;
            showPeriod = "0";
        }

        if(cal != null)
            startDate = cal.getTime();


        String href = "/pages/" + langCode + "/forum/?forum_id=" + forumId + "&theme_id=" + themeId + "&period=" + showPeriod;
        int num = ForumItem.getAnswerNum(themeId, startDate, visibleOnly);
        Enumeration enum = ForumItem.getAnswers(themeId, startDate, "desc".equals(order), pageNumber, pageSize, visibleOnly).elements();
        java.text.SimpleDateFormat sdf = new java.text.SimpleDateFormat("dd.MM.yyyy HH:mm");

      pageContext.write(_jsp_string71, 0, _jsp_string71.length);
        
        for(int i = 0; i < pagePath.size(); i++)
        {
            WebTreeNode treeNode = (WebTreeNode)pagePath.elementAt(i);

      pageContext.write(_jsp_string4, 0, _jsp_string4.length);
      out.print((nodePath(treeNode)));
      pageContext.write(_jsp_string5, 0, _jsp_string5.length);
      out.print((CMSApplication.toHTML(treeNode.getName())));
      pageContext.write(_jsp_string6, 0, _jsp_string6.length);
      
        }

      pageContext.write(_jsp_string132, 0, _jsp_string132.length);
      out.print((nodePath(pageId)));
      pageContext.write(_jsp_string133, 0, _jsp_string133.length);
      out.print((forum.getId()));
      pageContext.write(_jsp_string5, 0, _jsp_string5.length);
      out.print((CMSApplication.toHTML(forum.getName())));
      pageContext.write(_jsp_string6, 0, _jsp_string6.length);
      out.print((CMSApplication.toHTML(theme.getHeader())));
      pageContext.write(_jsp_string72, 0, _jsp_string72.length);
      out.print((des));
      pageContext.write(_jsp_string9, 0, _jsp_string9.length);
      out.print((sectionImg));
      pageContext.write(_jsp_string10, 0, _jsp_string10.length);
      out.print((sectionName));
      pageContext.write(_jsp_string134, 0, _jsp_string134.length);
      pageContext.write(_jsp_string12, 0, _jsp_string12.length);
      out.print((des));
      pageContext.write(_jsp_string13, 0, _jsp_string13.length);
      out.print((des));
      pageContext.write(_jsp_string14, 0, _jsp_string14.length);
      out.print((des));
      pageContext.write(_jsp_string15, 0, _jsp_string15.length);
      out.print((des));
      pageContext.write(_jsp_string16, 0, _jsp_string16.length);
      pageContext.write(_jsp_string1, 0, _jsp_string1.length);
      pageContext.write(_jsp_string135, 0, _jsp_string135.length);
      out.print((CMSApplication.toHTML(theme.getHeader())));
      pageContext.write(_jsp_string75, 0, _jsp_string75.length);
      out.print((des));
      pageContext.write(_jsp_string136, 0, _jsp_string136.length);
      out.print((num));
      pageContext.write(_jsp_string77, 0, _jsp_string77.length);
      printPagebar(pageNumber, pageSize, num, href, out);
      pageContext.write(_jsp_string130, 0, _jsp_string130.length);
      pageContext.write(_jsp_string1, 0, _jsp_string1.length);
      pageContext.write(_jsp_string79, 0, _jsp_string79.length);
      out.print((langCode));
      pageContext.write(_jsp_string80, 0, _jsp_string80.length);
      out.print((forumId));
      pageContext.write(_jsp_string18, 0, _jsp_string18.length);
      out.print((themeId));
      pageContext.write(_jsp_string19, 0, _jsp_string19.length);
        if(user != null && !user.isDisabled() && theme.getStatus() != ForumItem.CLOSED_THEME){ 
      pageContext.write(_jsp_string127, 0, _jsp_string127.length);
      out.print((langCode));
      pageContext.write(_jsp_string55, 0, _jsp_string55.length);
      out.print((forumId));
      pageContext.write(_jsp_string96, 0, _jsp_string96.length);
      out.print((themeId));
      pageContext.write(_jsp_string82, 0, _jsp_string82.length);
      out.print((des));
      pageContext.write(_jsp_string137, 0, _jsp_string137.length);
        } 
      pageContext.write(_jsp_string84, 0, _jsp_string84.length);
      out.print(("0".equals(showPeriod) ? " SELECTED":""));
      pageContext.write(_jsp_string85, 0, _jsp_string85.length);
      out.print(("1".equals(showPeriod) ? " SELECTED":""));
      pageContext.write(_jsp_string86, 0, _jsp_string86.length);
      out.print(("2".equals(showPeriod) ? " SELECTED":""));
      pageContext.write(_jsp_string87, 0, _jsp_string87.length);
      out.print(("3".equals(showPeriod) ? " SELECTED":""));
      pageContext.write(_jsp_string88, 0, _jsp_string88.length);
      out.print(("4".equals(showPeriod) ? " SELECTED":""));
      pageContext.write(_jsp_string89, 0, _jsp_string89.length);
      out.print(("5".equals(showPeriod) ? " SELECTED":""));
      pageContext.write(_jsp_string138, 0, _jsp_string138.length);
      out.print(("asc".equals(order) ? " SELECTED":""));
      pageContext.write(_jsp_string139, 0, _jsp_string139.length);
      out.print(("desc".equals(order) ? " SELECTED":""));
      pageContext.write(_jsp_string140, 0, _jsp_string140.length);
      out.print((des));
      pageContext.write(_jsp_string91, 0, _jsp_string91.length);
      pageContext.write(_jsp_string92, 0, _jsp_string92.length);
      pageContext.write(_jsp_string141, 0, _jsp_string141.length);
      pageContext.write(_jsp_string94, 0, _jsp_string94.length);
      
    int i = 0;
    while(enum.hasMoreElements())
    {
        i++;
        ForumItem answer = (ForumItem)enum.nextElement();
        String bgcolor = "";
        if(answer.getId().equals(themeId))
            bgcolor = " bgcolor=\"#DDF3E1\"";
        else if(i%2 == 1)
            bgcolor = " bgcolor=\"#F1F1F1\"";
        String text = (new ForumText(CMSApplication.toHTML(answer.getText()))).getText();

      pageContext.write(_jsp_string0, 0, _jsp_string0.length);
      pageContext.write(_jsp_string142, 0, _jsp_string142.length);
      out.print((bgcolor));
      pageContext.write(_jsp_string143, 0, _jsp_string143.length);
      out.print((langCode));
      pageContext.write(_jsp_string66, 0, _jsp_string66.length);
      out.print((CMSApplication.toHTML(answer.getUserLogin())));
      pageContext.write(_jsp_string144, 0, _jsp_string144.length);
      out.print((CMSApplication.toHTML(answer.getUserLogin())));
      pageContext.write(_jsp_string145, 0, _jsp_string145.length);
      out.print((CMSApplication.toHTML(answer.getHeader())));
      pageContext.write(_jsp_string146, 0, _jsp_string146.length);
      out.print((des));
      pageContext.write(_jsp_string147, 0, _jsp_string147.length);
      out.print((sdf.format(answer.getCreateDate())));
      pageContext.write(_jsp_string148, 0, _jsp_string148.length);
      out.print((bgcolor));
      pageContext.write(_jsp_string149, 0, _jsp_string149.length);
      out.print(( bgcolor));
      pageContext.write(_jsp_string150, 0, _jsp_string150.length);
      out.print((langCode));
      pageContext.write(_jsp_string66, 0, _jsp_string66.length);
      out.print((CMSApplication.toHTML(answer.getUserLogin())));
      pageContext.write(_jsp_string151, 0, _jsp_string151.length);
      out.print((des));
      pageContext.write(_jsp_string152, 0, _jsp_string152.length);
      out.print((des));
      pageContext.write(_jsp_string153, 0, _jsp_string153.length);
      out.print((answer.getUserEmail()));
      pageContext.write(_jsp_string151, 0, _jsp_string151.length);
      out.print((des));
      pageContext.write(_jsp_string154, 0, _jsp_string154.length);
        if(user != null  && !user.isDisabled() && theme.getStatus() != ForumItem.CLOSED_THEME){ 
      pageContext.write(_jsp_string155, 0, _jsp_string155.length);
      out.print((langCode));
      pageContext.write(_jsp_string55, 0, _jsp_string55.length);
      out.print((forumId));
      pageContext.write(_jsp_string96, 0, _jsp_string96.length);
      out.print((themeId));
      pageContext.write(_jsp_string156, 0, _jsp_string156.length);
      out.print((answer.getId()));
      pageContext.write(_jsp_string157, 0, _jsp_string157.length);
      out.print((CMSApplication.toHTML(answer.getUserLogin())));
      pageContext.write(_jsp_string151, 0, _jsp_string151.length);
      out.print((des));
      pageContext.write(_jsp_string158, 0, _jsp_string158.length);
       }
      pageContext.write(_jsp_string159, 0, _jsp_string159.length);
      out.print((text));
      pageContext.write(_jsp_string160, 0, _jsp_string160.length);
                if(isModerator)
            {

      pageContext.write(_jsp_string142, 0, _jsp_string142.length);
      out.print((bgcolor));
      pageContext.write(_jsp_string161, 0, _jsp_string161.length);
      out.print((langCode));
      pageContext.write(_jsp_string55, 0, _jsp_string55.length);
      out.print((forumId));
      pageContext.write(_jsp_string96, 0, _jsp_string96.length);
      out.print((themeId));
      pageContext.write(_jsp_string162, 0, _jsp_string162.length);
      out.print((answer.getId()));
      pageContext.write(_jsp_string163, 0, _jsp_string163.length);
                    if(num == 1 || !answer.getId().equals(themeId)){ 
      pageContext.write(_jsp_string164, 0, _jsp_string164.length);
      out.print((forumId));
      pageContext.write(_jsp_string96, 0, _jsp_string96.length);
      out.print((themeId));
      pageContext.write(_jsp_string165, 0, _jsp_string165.length);
      out.print((answer.getId()));
      pageContext.write(_jsp_string166, 0, _jsp_string166.length);
                    } 
      pageContext.write(_jsp_string0, 0, _jsp_string0.length);
                    if(answer.getPublicDate() == null && (theme.isPublic() || answer.getId().equals(themeId))){ 
      pageContext.write(_jsp_string167, 0, _jsp_string167.length);
      out.print((forumId));
      pageContext.write(_jsp_string96, 0, _jsp_string96.length);
      out.print((themeId));
      pageContext.write(_jsp_string165, 0, _jsp_string165.length);
      out.print((answer.getId()));
      pageContext.write(_jsp_string168, 0, _jsp_string168.length);
                    } 
      pageContext.write(_jsp_string0, 0, _jsp_string0.length);
                    if(answer.getPublicDate() == null && !theme.isPublic() && !answer.getId().equals(themeId)){ 
      pageContext.write(_jsp_string169, 0, _jsp_string169.length);
                    } 
      pageContext.write(_jsp_string170, 0, _jsp_string170.length);
                } 
      pageContext.write(_jsp_string0, 0, _jsp_string0.length);
      pageContext.write(_jsp_string171, 0, _jsp_string171.length);
      out.print((des));
      pageContext.write(_jsp_string124, 0, _jsp_string124.length);
        } 
      pageContext.write(_jsp_string172, 0, _jsp_string172.length);
      pageContext.write(_jsp_string126, 0, _jsp_string126.length);
      out.print((langCode));
      pageContext.write(_jsp_string80, 0, _jsp_string80.length);
      out.print((forumId));
      pageContext.write(_jsp_string18, 0, _jsp_string18.length);
      out.print((themeId));
      pageContext.write(_jsp_string19, 0, _jsp_string19.length);
        if(user != null  && !user.isDisabled() && theme.getStatus() != ForumItem.CLOSED_THEME){ 
      pageContext.write(_jsp_string127, 0, _jsp_string127.length);
      out.print((langCode));
      pageContext.write(_jsp_string55, 0, _jsp_string55.length);
      out.print((forumId));
      pageContext.write(_jsp_string96, 0, _jsp_string96.length);
      out.print((themeId));
      pageContext.write(_jsp_string82, 0, _jsp_string82.length);
      out.print((des));
      pageContext.write(_jsp_string137, 0, _jsp_string137.length);
        } 
      pageContext.write(_jsp_string84, 0, _jsp_string84.length);
      out.print(("0".equals(showPeriod) ? " SELECTED":""));
      pageContext.write(_jsp_string85, 0, _jsp_string85.length);
      out.print(("1".equals(showPeriod) ? " SELECTED":""));
      pageContext.write(_jsp_string86, 0, _jsp_string86.length);
      out.print(("2".equals(showPeriod) ? " SELECTED":""));
      pageContext.write(_jsp_string87, 0, _jsp_string87.length);
      out.print(("3".equals(showPeriod) ? " SELECTED":""));
      pageContext.write(_jsp_string88, 0, _jsp_string88.length);
      out.print(("4".equals(showPeriod) ? " SELECTED":""));
      pageContext.write(_jsp_string89, 0, _jsp_string89.length);
      out.print(("5".equals(showPeriod) ? " SELECTED":""));
      pageContext.write(_jsp_string138, 0, _jsp_string138.length);
      out.print(("asc".equals(order) ? " SELECTED":""));
      pageContext.write(_jsp_string139, 0, _jsp_string139.length);
      out.print(("desc".equals(order) ? " SELECTED":""));
      pageContext.write(_jsp_string173, 0, _jsp_string173.length);
      out.print((des));
      pageContext.write(_jsp_string91, 0, _jsp_string91.length);
      pageContext.write(_jsp_string1, 0, _jsp_string1.length);
      pageContext.write(_jsp_string129, 0, _jsp_string129.length);
      printPagebar(pageNumber, pageSize, num, href, out);
      pageContext.write(_jsp_string130, 0, _jsp_string130.length);
      pageContext.write(_jsp_string0, 0, _jsp_string0.length);
      pageContext.write(_jsp_string0, 0, _jsp_string0.length);
        } 
      pageContext.write(_jsp_string0, 0, _jsp_string0.length);
      
    }

      pageContext.write(_jsp_string0, 0, _jsp_string0.length);
        }catch(Exception e){} 
    } catch (java.lang.Throwable _jsp_e) {
      pageContext.handlePageException(_jsp_e);
    } finally {
      JspFactory.getDefaultFactory().releasePageContext(pageContext);
    }
  }

  private com.caucho.java.LineMap _caucho_line_map;
  private java.util.ArrayList _caucho_depends = new java.util.ArrayList();

  public boolean _caucho_isModified()
  {
    if (_caucho_isDead)
      return true;
    if (com.caucho.util.CauchoSystem.getVersionId() != 2058990002)
      return true;
    for (int i = _caucho_depends.size() - 1; i >= 0; i--) {
      com.caucho.vfs.Depend depend;
      depend = (com.caucho.vfs.Depend) _caucho_depends.get(i);
      if (depend.isModified())
        return true;
    }
    return false;
  }

  public long _caucho_lastModified()
  {
    return 0;
  }

  public com.caucho.java.LineMap _caucho_getLineMap()
  {
    return _caucho_line_map;
  }

  public void destroy()
  {
      _caucho_isDead = true;
      super.destroy();
  }

  public void init(com.caucho.java.LineMap lineMap,
                   com.caucho.vfs.Path appDir)
    throws javax.servlet.ServletException
  {
    com.caucho.vfs.Path resinHome = com.caucho.util.CauchoSystem.getResinHome();
    com.caucho.vfs.MergePath mergePath = new com.caucho.vfs.MergePath();
    mergePath.addMergePath(appDir);
    mergePath.addMergePath(resinHome);
    mergePath.addClassPath(getClass().getClassLoader());
    _caucho_line_map = new com.caucho.java.LineMap("_forum__jsp.java", "/usr/local/apache/htdocs/ntvmir/forum/forum.jsp");
    _caucho_line_map.add("/forum/forum.jsp", 1, 1);
    _caucho_line_map.add("/inc/init_global.jsp", 1, 1);
    _caucho_line_map.add(44, 20);
    _caucho_line_map.add("/inc/pagebar.jsp", 1, 33);
    _caucho_line_map.add("/forum/forum.jsp", 1, 82);
    _caucho_line_map.add("/inc/init_global.jsp", 1, 87);
    _caucho_line_map.add("/usr/local/apache/htdocs/ntvmir/forum/forum.jsp", 7, 131);
    _caucho_line_map.add("/inc/pagebar.jsp", 1, 131);
    _caucho_line_map.add("/usr/local/apache/htdocs/ntvmir/forum/forum.jsp", 8, 132);
    _caucho_line_map.add(9, 134);
    _caucho_line_map.add("/inc/path_init.jsp", 1, 134);
    _caucho_line_map.add("/usr/local/apache/htdocs/ntvmir/forum/forum.jsp", 10, 164);
    _caucho_line_map.add(22, 177);
    _caucho_line_map.add("/forum/answer.jsp", 1, 177);
    _caucho_line_map.add(104, 229);
    _caucho_line_map.add(118, 244);
    _caucho_line_map.add(118, 246);
    _caucho_line_map.add(119, 248);
    _caucho_line_map.add(126, 257);
    _caucho_line_map.add(126, 259);
    _caucho_line_map.add(132, 262);
    _caucho_line_map.add(134, 266);
    _caucho_line_map.add(135, 268);
    _caucho_line_map.add(140, 271);
    _caucho_line_map.add(152, 280);
    _caucho_line_map.add(153, 282);
    _caucho_line_map.add(154, 284);
    _caucho_line_map.add(155, 286);
    _caucho_line_map.add(156, 288);
    _caucho_line_map.add(159, 290);
    _caucho_line_map.add(162, 292);
    _caucho_line_map.add(167, 294);
    _caucho_line_map.add(167, 296);
    _caucho_line_map.add(167, 298);
    _caucho_line_map.add(167, 300);
    _caucho_line_map.add(167, 302);
    _caucho_line_map.add(167, 304);
    _caucho_line_map.add(170, 306);
    _caucho_line_map.add(179, 308);
    _caucho_line_map.add(180, 310);
    _caucho_line_map.add(183, 312);
    _caucho_line_map.add(184, 314);
    _caucho_line_map.add(187, 316);
    _caucho_line_map.add(188, 318);
    _caucho_line_map.add(191, 320);
    _caucho_line_map.add(192, 322);
    _caucho_line_map.add(203, 324);
    _caucho_line_map.add(207, 326);
    _caucho_line_map.add(211, 328);
    _caucho_line_map.add(211, 330);
    _caucho_line_map.add(219, 334);
    _caucho_line_map.add("/usr/local/apache/htdocs/ntvmir/forum/forum.jsp", 23, 336);
    _caucho_line_map.add(28, 342);
    _caucho_line_map.add("/forum/main_page.jsp", 6, 343);
    _caucho_line_map.add(20, 358);
    _caucho_line_map.add(20, 360);
    _caucho_line_map.add(21, 362);
    _caucho_line_map.add(28, 371);
    _caucho_line_map.add(28, 373);
    _caucho_line_map.add(33, 376);
    _caucho_line_map.add(35, 380);
    _caucho_line_map.add(36, 382);
    _caucho_line_map.add(42, 386);
    _caucho_line_map.add(60, 403);
    _caucho_line_map.add(67, 406);
    _caucho_line_map.add(99, 439);
    _caucho_line_map.add(99, 441);
    _caucho_line_map.add(100, 443);
    _caucho_line_map.add(104, 448);
    _caucho_line_map.add(104, 450);
    _caucho_line_map.add(104, 452);
    _caucho_line_map.add(109, 458);
    _caucho_line_map.add(110, 460);
    _caucho_line_map.add(118, 464);
    _caucho_line_map.add(119, 466);
    _caucho_line_map.add(120, 468);
    _caucho_line_map.add(120, 469);
    _caucho_line_map.add(130, 476);
    _caucho_line_map.add(131, 478);
    _caucho_line_map.add(132, 480);
    _caucho_line_map.add(132, 482);
    _caucho_line_map.add(132, 484);
    _caucho_line_map.add(132, 486);
    _caucho_line_map.add(133, 488);
    _caucho_line_map.add(139, 491);
    _caucho_line_map.add("/usr/local/apache/htdocs/ntvmir/forum/forum.jsp", 29, 498);
    _caucho_line_map.add(34, 504);
    _caucho_line_map.add("/forum/forum_page.jsp", 1, 504);
    _caucho_line_map.add(53, 552);
    _caucho_line_map.add(58, 558);
    _caucho_line_map.add(58, 560);
    _caucho_line_map.add(59, 562);
    _caucho_line_map.add(62, 566);
    _caucho_line_map.add(65, 568);
    _caucho_line_map.add(65, 570);
    _caucho_line_map.add(65, 572);
    _caucho_line_map.add(72, 575);
    _caucho_line_map.add(74, 579);
    _caucho_line_map.add(75, 581);
    _caucho_line_map.add(83, 585);
    _caucho_line_map.add(86, 587);
    _caucho_line_map.add(86, 589);
    _caucho_line_map.add(87, 591);
    _caucho_line_map.add(95, 595);
    _caucho_line_map.add(96, 597);
    _caucho_line_map.add(97, 599);
    _caucho_line_map.add(98, 601);
    _caucho_line_map.add(98, 603);
    _caucho_line_map.add(98, 605);
    _caucho_line_map.add(99, 607);
    _caucho_line_map.add(102, 609);
    _caucho_line_map.add(103, 611);
    _caucho_line_map.add(104, 613);
    _caucho_line_map.add(105, 615);
    _caucho_line_map.add(106, 617);
    _caucho_line_map.add(107, 619);
    _caucho_line_map.add(107, 621);
    _caucho_line_map.add(125, 626);
    _caucho_line_map.add(155, 658);
    _caucho_line_map.add(155, 660);
    _caucho_line_map.add(155, 662);
    _caucho_line_map.add(157, 666);
    _caucho_line_map.add(157, 668);
    _caucho_line_map.add(159, 672);
    _caucho_line_map.add(159, 674);
    _caucho_line_map.add(161, 678);
    _caucho_line_map.add(161, 680);
    _caucho_line_map.add(164, 684);
    _caucho_line_map.add(164, 686);
    _caucho_line_map.add(164, 688);
    _caucho_line_map.add(164, 690);
    _caucho_line_map.add(165, 692);
    _caucho_line_map.add(168, 696);
    _caucho_line_map.add(169, 698);
    _caucho_line_map.add(178, 702);
    _caucho_line_map.add(188, 711);
    _caucho_line_map.add(188, 713);
    _caucho_line_map.add(188, 715);
    _caucho_line_map.add(188, 717);
    _caucho_line_map.add(188, 719);
    _caucho_line_map.add(190, 723);
    _caucho_line_map.add(190, 725);
    _caucho_line_map.add(191, 727);
    _caucho_line_map.add(191, 728);
    _caucho_line_map.add(196, 734);
    _caucho_line_map.add(200, 736);
    _caucho_line_map.add(201, 738);
    _caucho_line_map.add(206, 744);
    _caucho_line_map.add(206, 746);
    _caucho_line_map.add(206, 748);
    _caucho_line_map.add(206, 750);
    _caucho_line_map.add(206, 752);
    _caucho_line_map.add(206, 754);
    _caucho_line_map.add(207, 756);
    _caucho_line_map.add(215, 759);
    _caucho_line_map.add(221, 763);
    _caucho_line_map.add(224, 767);
    _caucho_line_map.add(224, 769);
    _caucho_line_map.add(225, 771);
    _caucho_line_map.add(226, 773);
    _caucho_line_map.add(227, 775);
    _caucho_line_map.add(227, 777);
    _caucho_line_map.add(228, 779);
    _caucho_line_map.add(229, 781);
    _caucho_line_map.add(230, 783);
    _caucho_line_map.add(230, 785);
    _caucho_line_map.add(231, 787);
    _caucho_line_map.add(243, 795);
    _caucho_line_map.add(248, 799);
    _caucho_line_map.add(249, 801);
    _caucho_line_map.add(255, 804);
    _caucho_line_map.add(256, 806);
    _caucho_line_map.add(257, 808);
    _caucho_line_map.add(258, 810);
    _caucho_line_map.add(258, 812);
    _caucho_line_map.add(258, 814);
    _caucho_line_map.add(259, 816);
    _caucho_line_map.add(262, 818);
    _caucho_line_map.add(263, 820);
    _caucho_line_map.add(264, 822);
    _caucho_line_map.add(265, 824);
    _caucho_line_map.add(266, 826);
    _caucho_line_map.add(267, 828);
    _caucho_line_map.add(267, 830);
    _caucho_line_map.add(275, 834);
    _caucho_line_map.add(283, 838);
    _caucho_line_map.add("/usr/local/apache/htdocs/ntvmir/forum/forum.jsp", 35, 840);
    _caucho_line_map.add(40, 846);
    _caucho_line_map.add("/forum/theme_page.jsp", 1, 846);
    _caucho_line_map.add(65, 906);
    _caucho_line_map.add(70, 912);
    _caucho_line_map.add(70, 914);
    _caucho_line_map.add(71, 916);
    _caucho_line_map.add(74, 920);
    _caucho_line_map.add(74, 922);
    _caucho_line_map.add(74, 924);
    _caucho_line_map.add(75, 926);
    _caucho_line_map.add(78, 928);
    _caucho_line_map.add(78, 930);
    _caucho_line_map.add(78, 932);
    _caucho_line_map.add(86, 935);
    _caucho_line_map.add(88, 939);
    _caucho_line_map.add(89, 941);
    _caucho_line_map.add(96, 945);
    _caucho_line_map.add(99, 947);
    _caucho_line_map.add(99, 949);
    _caucho_line_map.add(100, 951);
    _caucho_line_map.add(107, 955);
    _caucho_line_map.add(108, 957);
    _caucho_line_map.add(109, 959);
    _caucho_line_map.add(110, 961);
    _caucho_line_map.add(111, 963);
    _caucho_line_map.add(111, 965);
    _caucho_line_map.add(111, 967);
    _caucho_line_map.add(111, 969);
    _caucho_line_map.add(112, 971);
    _caucho_line_map.add(115, 973);
    _caucho_line_map.add(116, 975);
    _caucho_line_map.add(117, 977);
    _caucho_line_map.add(118, 979);
    _caucho_line_map.add(119, 981);
    _caucho_line_map.add(120, 983);
    _caucho_line_map.add(123, 987);
    _caucho_line_map.add(124, 989);
    _caucho_line_map.add(141, 994);
    _caucho_line_map.add(155, 1009);
    _caucho_line_map.add(158, 1011);
    _caucho_line_map.add(158, 1013);
    _caucho_line_map.add(158, 1015);
    _caucho_line_map.add(161, 1017);
    _caucho_line_map.add(162, 1019);
    _caucho_line_map.add(162, 1021);
    _caucho_line_map.add(165, 1025);
    _caucho_line_map.add(167, 1029);
    _caucho_line_map.add(167, 1031);
    _caucho_line_map.add(167, 1033);
    _caucho_line_map.add(167, 1035);
    _caucho_line_map.add(167, 1037);
    _caucho_line_map.add(169, 1041);
    _caucho_line_map.add(169, 1043);
    _caucho_line_map.add(169, 1045);
    _caucho_line_map.add(169, 1047);
    _caucho_line_map.add(169, 1049);
    _caucho_line_map.add(169, 1051);
    _caucho_line_map.add(169, 1053);
    _caucho_line_map.add(170, 1055);
    _caucho_line_map.add(173, 1057);
    _caucho_line_map.add(176, 1061);
    _caucho_line_map.add(181, 1063);
    _caucho_line_map.add(181, 1065);
    _caucho_line_map.add(181, 1067);
    _caucho_line_map.add(181, 1069);
    _caucho_line_map.add(182, 1071);
    _caucho_line_map.add(183, 1073);
    _caucho_line_map.add(183, 1075);
    _caucho_line_map.add(183, 1077);
    _caucho_line_map.add(184, 1079);
    _caucho_line_map.add(185, 1081);
    _caucho_line_map.add(186, 1083);
    _caucho_line_map.add(186, 1085);
    _caucho_line_map.add(186, 1087);
    _caucho_line_map.add(187, 1089);
    _caucho_line_map.add(188, 1091);
    _caucho_line_map.add(194, 1095);
    _caucho_line_map.add(198, 1100);
    _caucho_line_map.add(203, 1103);
    _caucho_line_map.add(204, 1105);
    _caucho_line_map.add(205, 1107);
    _caucho_line_map.add(206, 1109);
    _caucho_line_map.add(207, 1111);
    _caucho_line_map.add(207, 1113);
    _caucho_line_map.add(207, 1115);
    _caucho_line_map.add(207, 1117);
    _caucho_line_map.add(208, 1119);
    _caucho_line_map.add(211, 1121);
    _caucho_line_map.add(212, 1123);
    _caucho_line_map.add(213, 1125);
    _caucho_line_map.add(214, 1127);
    _caucho_line_map.add(215, 1129);
    _caucho_line_map.add(216, 1131);
    _caucho_line_map.add(219, 1135);
    _caucho_line_map.add(229, 1141);
    _caucho_line_map.add(234, 1145);
    _caucho_line_map.add("/usr/local/apache/htdocs/ntvmir/forum/forum.jsp", 41, 1147);
    _caucho_line_map.add(44, 1151);
    com.caucho.vfs.Depend depend;
    depend = new com.caucho.vfs.Depend(mergePath.lookup("file:/usr/local/apache/htdocs/ntvmir/inc/init_global.jsp"), 1043852040000L, 1646L);
    _caucho_depends.add(depend);
    depend = new com.caucho.vfs.Depend(mergePath.lookup("file:/usr/local/apache/htdocs/ntvmir/inc/pagebar.jsp"), 1040320291000L, 823L);
    _caucho_depends.add(depend);
    depend = new com.caucho.vfs.Depend(mergePath.lookup("file:/usr/local/apache/htdocs/ntvmir/inc/path_init.jsp"), 1043334172000L, 857L);
    _caucho_depends.add(depend);
    depend = new com.caucho.vfs.Depend(mergePath.lookup("file:/usr/local/apache/htdocs/ntvmir/forum/answer.jsp"), 1044885826000L, 8688L);
    _caucho_depends.add(depend);
    depend = new com.caucho.vfs.Depend(mergePath.lookup("file:/usr/local/apache/htdocs/ntvmir/forum/main_page.jsp"), 1044885872000L, 5550L);
    _caucho_depends.add(depend);
    depend = new com.caucho.vfs.Depend(mergePath.lookup("file:/usr/local/apache/htdocs/ntvmir/forum/forum_page.jsp"), 1044885868000L, 11780L);
    _caucho_depends.add(depend);
    depend = new com.caucho.vfs.Depend(mergePath.lookup("file:/usr/local/apache/htdocs/ntvmir/forum/theme_page.jsp"), 1044886017000L, 11908L);
    _caucho_depends.add(depend);
    depend = new com.caucho.vfs.Depend(mergePath.lookup("file:/usr/local/apache/htdocs/ntvmir/forum/forum.jsp"), 1043841633000L, 1071L);
    _caucho_depends.add(depend);
  }

  private static byte []_jsp_string83;
  private static byte []_jsp_string126;
  private static byte []_jsp_string73;
  private static byte []_jsp_string79;
  private static byte []_jsp_string116;
  private static byte []_jsp_string44;
  private static byte []_jsp_string64;
  private static byte []_jsp_string47;
  private static byte []_jsp_string85;
  private static byte []_jsp_string74;
  private static byte []_jsp_string134;
  private static byte []_jsp_string8;
  private static byte []_jsp_string146;
  private static byte []_jsp_string76;
  private static byte []_jsp_string113;
  private static byte []_jsp_string9;
  private static byte []_jsp_string115;
  private static byte []_jsp_string36;
  private static byte []_jsp_string80;
  private static byte []_jsp_string32;
  private static byte []_jsp_string170;
  private static byte []_jsp_string135;
  private static byte []_jsp_string52;
  private static byte []_jsp_string104;
  private static byte []_jsp_string14;
  private static byte []_jsp_string120;
  private static byte []_jsp_string98;
  private static byte []_jsp_string148;
  private static byte []_jsp_string129;
  private static byte []_jsp_string50;
  private static byte []_jsp_string16;
  private static byte []_jsp_string173;
  private static byte []_jsp_string12;
  private static byte []_jsp_string5;
  private static byte []_jsp_string168;
  private static byte []_jsp_string60;
  private static byte []_jsp_string151;
  private static byte []_jsp_string78;
  private static byte []_jsp_string139;
  private static byte []_jsp_string62;
  private static byte []_jsp_string91;
  private static byte []_jsp_string145;
  private static byte []_jsp_string137;
  private static byte []_jsp_string66;
  private static byte []_jsp_string150;
  private static byte []_jsp_string108;
  private static byte []_jsp_string92;
  private static byte []_jsp_string18;
  private static byte []_jsp_string86;
  private static byte []_jsp_string49;
  private static byte []_jsp_string6;
  private static byte []_jsp_string75;
  private static byte []_jsp_string159;
  private static byte []_jsp_string11;
  private static byte []_jsp_string102;
  private static byte []_jsp_string155;
  private static byte []_jsp_string112;
  private static byte []_jsp_string161;
  private static byte []_jsp_string110;
  private static byte []_jsp_string61;
  private static byte []_jsp_string69;
  private static byte []_jsp_string122;
  private static byte []_jsp_string41;
  private static byte []_jsp_string156;
  private static byte []_jsp_string90;
  private static byte []_jsp_string55;
  private static byte []_jsp_string125;
  private static byte []_jsp_string106;
  private static byte []_jsp_string34;
  private static byte []_jsp_string103;
  private static byte []_jsp_string169;
  private static byte []_jsp_string53;
  private static byte []_jsp_string160;
  private static byte []_jsp_string105;
  private static byte []_jsp_string131;
  private static byte []_jsp_string141;
  private static byte []_jsp_string19;
  private static byte []_jsp_string28;
  private static byte []_jsp_string57;
  private static byte []_jsp_string153;
  private static byte []_jsp_string58;
  private static byte []_jsp_string46;
  private static byte []_jsp_string94;
  private static byte []_jsp_string72;
  private static byte []_jsp_string133;
  private static byte []_jsp_string38;
  private static byte []_jsp_string63;
  private static byte []_jsp_string123;
  private static byte []_jsp_string117;
  private static byte []_jsp_string10;
  private static byte []_jsp_string97;
  private static byte []_jsp_string136;
  private static byte []_jsp_string140;
  private static byte []_jsp_string56;
  private static byte []_jsp_string39;
  private static byte []_jsp_string107;
  private static byte []_jsp_string67;
  private static byte []_jsp_string82;
  private static byte []_jsp_string35;
  private static byte []_jsp_string87;
  private static byte []_jsp_string29;
  private static byte []_jsp_string84;
  private static byte []_jsp_string13;
  private static byte []_jsp_string2;
  private static byte []_jsp_string71;
  private static byte []_jsp_string101;
  private static byte []_jsp_string162;
  private static byte []_jsp_string3;
  private static byte []_jsp_string54;
  private static byte []_jsp_string88;
  private static byte []_jsp_string118;
  private static byte []_jsp_string99;
  private static byte []_jsp_string42;
  private static byte []_jsp_string119;
  private static byte []_jsp_string164;
  private static byte []_jsp_string30;
  private static byte []_jsp_string158;
  private static byte []_jsp_string152;
  private static byte []_jsp_string81;
  private static byte []_jsp_string154;
  private static byte []_jsp_string21;
  private static byte []_jsp_string27;
  private static byte []_jsp_string143;
  private static byte []_jsp_string65;
  private static byte []_jsp_string171;
  private static byte []_jsp_string114;
  private static byte []_jsp_string33;
  private static byte []_jsp_string144;
  private static byte []_jsp_string165;
  private static byte []_jsp_string77;
  private static byte []_jsp_string111;
  private static byte []_jsp_string59;
  private static byte []_jsp_string37;
  private static byte []_jsp_string124;
  private static byte []_jsp_string128;
  private static byte []_jsp_string130;
  private static byte []_jsp_string48;
  private static byte []_jsp_string0;
  private static byte []_jsp_string20;
  private static byte []_jsp_string70;
  private static byte []_jsp_string93;
  private static byte []_jsp_string96;
  private static byte []_jsp_string167;
  private static byte []_jsp_string17;
  private static byte []_jsp_string40;
  private static byte []_jsp_string31;
  private static byte []_jsp_string163;
  private static byte []_jsp_string142;
  private static byte []_jsp_string25;
  private static byte []_jsp_string23;
  private static byte []_jsp_string121;
  private static byte []_jsp_string43;
  private static byte []_jsp_string4;
  private static byte []_jsp_string132;
  private static byte []_jsp_string26;
  private static byte []_jsp_string166;
  private static byte []_jsp_string51;
  private static byte []_jsp_string109;
  private static byte []_jsp_string100;
  private static byte []_jsp_string68;
  private static byte []_jsp_string138;
  private static byte []_jsp_string127;
  private static byte []_jsp_string15;
  private static byte []_jsp_string147;
  private static byte []_jsp_string24;
  private static byte []_jsp_string22;
  private static byte []_jsp_string89;
  private static byte []_jsp_string45;
  private static byte []_jsp_string157;
  private static byte []_jsp_string7;
  private static byte []_jsp_string1;
  private static byte []_jsp_string95;
  private static byte []_jsp_string172;
  private static byte []_jsp_string149;
  static {
    try {
      _jsp_string83 = "/forum/btn-add-thm.gif\" height=\"18\" alt=\"Добавить тему\" border=\"0\"></a></td>\r\n".getBytes("Cp1251");
      _jsp_string126 = "\r\n<table width=\"100%\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" style=\"margin:4px 0px 0px 0px;\">\r\n<tr><form action=\"/pages/".getBytes("Cp1251");
      _jsp_string73 = "\" border=\"0\"></td>\r\n</tr>\r\n</table>\r\n\r\n\r\n\r\n".getBytes("Cp1251");
      _jsp_string79 = "\r\n<table width=\"100%\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" style=\"margin:8px 0px 0px 0px;\">\r\n<tr><form action=\"/pages/".getBytes("Cp1251");
      _jsp_string116 = "\" onClick=\"return confirm('Закрыть тему?');\">закрыть</a>\r\n".getBytes("Cp1251");
      _jsp_string44 = "\" border=\"0\"></td>\r\n</tr>\r\n</table>\r\n\r\n".getBytes("Cp1251");
      _jsp_string64 = "\r\n	".getBytes("Cp1251");
      _jsp_string47 = "\r\n<tr bgcolor=\"#DDF3E1\">\r\n	<td class=\"defFont\">&nbsp;</td>\r\n	<td width=\"70%\" class=\"defFont\" height=\"19\"><b class=\"grnTtl\">".getBytes("Cp1251");
      _jsp_string85 = ">все темы</OPTION>\r\n<OPTION value=1".getBytes("Cp1251");
      _jsp_string74 = "\r\n\r\n\r\n<div style=\"margin:8px 0px 0px 0px;font-family: Geneva CY, Verdana, Tahoma, Arial, sans-serif;\"><b class=\"bluTtl\">".getBytes("Cp1251");
      _jsp_string134 = "\" border=\"0\"></td>\r\n</tr>\r\n</table>\r\n\r\n\r\n\r\n\r\n".getBytes("Cp1251");
      _jsp_string8 = "\r\n</td>\r\n<!--заголовок страницы--><td align=\"right\"><img src=\"".getBytes("Cp1251");
      _jsp_string146 = "</b></td>\r\n	<td class=\"smallFont\" align=\"right\" nowrap><img src=\"".getBytes("Cp1251");
      _jsp_string76 = "/ans-all.gif\" width=\"18\" height=\"8\" border=\"0\" align=\"absmiddle\"><SPAN class=\"c66\">Тем:</SPAN> ".getBytes("Cp1251");
      _jsp_string113 = "\r\n	]</SPAN> </td>\r\n	<td></td>\r\n	<td></td>\r\n	<td></td>\r\n</tr>\r\n".getBytes("Cp1251");
      _jsp_string9 = "/".getBytes("Cp1251");
      _jsp_string115 = "\r\n	<a href=\"/forum/xt_forum.jsp?action=close&forum_id=".getBytes("Cp1251");
      _jsp_string36 = "/forum/ico-smile-6.gif\" width=18></A></td>\r\n	</tr>\r\n	<tr>\r\n	<td><A href=\"javascript:smile(':)');\"><IMG alt=\"\" border=0 height=20 src=\"".getBytes("Cp1251");
      _jsp_string80 = "/forum\">\r\n<input type=\"hidden\" name=\"forum_id\" value=\"".getBytes("Cp1251");
      _jsp_string32 = "/forum/ico-smile-2.gif\" width=18></A></td>\r\n	</tr>\r\n	<tr>	\r\n	<td><A href=\"javascript:smile(':D');\"><IMG alt=\"\" border=0 height=20 src=\"".getBytes("Cp1251");
      _jsp_string170 = "\r\n	</td>\r\n	<td></td>\r\n</tr>\r\n".getBytes("Cp1251");
      _jsp_string135 = "\r\n\r\n<div style=\"margin:8px 0px 0px 0px;font-family: Geneva CY, Verdana, Tahoma, Arial, sans-serif;\"><b class=\"bluTtl\">".getBytes("Cp1251");
      _jsp_string52 = "/greyln2.gif\" width=\"100%\"><SPACER TYPE=\"block\" HEIGHT=\"1\" WIDTH=\"1\"></td></tr>\r\n".getBytes("Cp1251");
      _jsp_string104 = "\r\n<tr valign=\"top\">\r\n	<td class=\"smallFont\" nowrap>\r\n	<img src=\"".getBytes("Cp1251");
      _jsp_string14 = "/blu-ttl-lft.gif\" width=\"16\" height=\"19\" border=\"0\"><img src=\"".getBytes("Cp1251");
      _jsp_string120 = "%>\">обычная</a>\r\n".getBytes("Cp1251");
      _jsp_string98 = "/forum/ico-frm-lock.gif\" width=\"13\" height=\"15\" border=\"0\" hspace=\"4\">".getBytes("Cp1251");
      _jsp_string148 = "</td>\r\n</tr>\r\n<tr".getBytes("Cp1251");
      _jsp_string129 = "\r\n<table width=\"100%\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" style=\"margin:8px 0px 0px 0px;\">\r\n<tr>\r\n<td align=\"right\" class=\"smallFont\"><SPAN class=\"c66\">".getBytes("Cp1251");
      _jsp_string50 = "\r\n<!-- divider --><tr><td height=\"11\" colspan=\"4\" background=\"".getBytes("Cp1251");
      _jsp_string16 = "/blu-ttl-rght.gif\" width=\"16\" height=\"19\" border=\"0\"></td>\r\n	</tr>\r\n	</table>\r\n".getBytes("Cp1251");
      _jsp_string173 = ">начиная с новых</OPTION>\r\n</SELECT>\r\n</SPAN><input type=\"Image\"src=\"".getBytes("Cp1251");
      _jsp_string12 = "\r\n	<table width=\"100%\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" background=\"".getBytes("Cp1251");
      _jsp_string5 = "\">".getBytes("Cp1251");
      _jsp_string168 = "\">опубликовать</a>\r\n".getBytes("Cp1251");
      _jsp_string60 = "</a></td>\r\n	<td></td>\r\n	<td></td>\r\n</tr>\r\n\r\n<tr valign=\"top\">\r\n	<td class=\"smallFont\">".getBytes("Cp1251");
      _jsp_string151 = "\"><img src=\"".getBytes("Cp1251");
      _jsp_string78 = "</SPAN></td>\r\n</tr>\r\n</table>\r\n\r\n".getBytes("Cp1251");
      _jsp_string139 = ">начиная со старых</OPTION>\r\n<OPTION value=desc".getBytes("Cp1251");
      _jsp_string62 = "</td>\r\n</tr>\r\n\r\n<tr valign=\"top\">\r\n	<td class=\"smallFont\" nowrap>\r\n	<img src=\"".getBytes("Cp1251");
      _jsp_string91 = "/btn-arr-blu.gif\" width=\"18\" height=\"18\" border=\"0\" hspace=\"5\" align=\"absmiddle\"></NOBR></td>\r\n</form></tr>\r\n</table>\r\n".getBytes("Cp1251");
      _jsp_string145 = "</b></a>\r\n	</td>\r\n	<td rowspan=\"3\"><div style=\"width:10\"><SPACER TYPE=\"block\" HEIGHT=\"1\" WIDTH=\"10\"></div></td>\r\n	<td class=\"defFont\"><b class=\"bluTtl\">".getBytes("Cp1251");
      _jsp_string137 = "/forum/btn-add-msg.gif\" height=\"18\" alt=\"Добавить сообщение\" border=\"0\"></a></td>\r\n".getBytes("Cp1251");
      _jsp_string66 = "/forum/profile?login=".getBytes("Cp1251");
      _jsp_string150 = ">\r\n		<td class=\"smallFont\" valign=\"bottom\">\r\n		<a href=\"/pages/".getBytes("Cp1251");
      _jsp_string108 = "</td>\r\n</tr>\r\n\r\n<tr valign=\"top\">\r\n	<td class=\"XsmallFont\"><SPAN class=\"c66\">[<img src=\"".getBytes("Cp1251");
      _jsp_string92 = "\r\n\r\n<table width=\"100%\" border=\"0\" cellpadding=\"1\" cellspacing=\"0\" style=\"margin:8px 0px 0px 0px;\">\r\n\r\n".getBytes("Cp1251");
      _jsp_string18 = "\">\r\n<input type=\"hidden\" name=\"theme_id\" value=\"".getBytes("Cp1251");
      _jsp_string86 = ">за последний день</OPTION>\r\n<OPTION value=2".getBytes("Cp1251");
      _jsp_string49 = "\r\n<!--отступ--><tr><td height=\"10\" colspan=\"5\"><SPACER TYPE=\"block\" HEIGHT=\"1\" WIDTH=\"1\"></td></tr>\r\n\r\n".getBytes("Cp1251");
      _jsp_string6 = "</a> /\r\n".getBytes("Cp1251");
      _jsp_string75 = "</b></div>\r\n<table width=\"100%\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\">\r\n<td height=\"22\" valign=\"top\">\r\n<SPAN class=\"smallFont\"><img src=\"".getBytes("Cp1251");
      _jsp_string159 = "\r\n        ".getBytes("Cp1251");
      _jsp_string11 = "\" border=\"0\"></td>\r\n</tr>\r\n</table>\r\n\r\n\r\n".getBytes("Cp1251");
      _jsp_string102 = "</b>\r\n".getBytes("Cp1251");
      _jsp_string155 = "<a href=\"/pages/".getBytes("Cp1251");
      _jsp_string112 = "</a>".getBytes("Cp1251");
      _jsp_string161 = ">\r\n	<td><div style=\"width:3\"><SPACER TYPE=\"block\" HEIGHT=\"1\" WIDTH=\"3\"></div></td>\r\n	<td></td>\r\n	<td><div style=\"width:10\"><SPACER TYPE=\"block\" HEIGHT=\"1\" WIDTH=\"10\"></div></td>\r\n	<td class=\"defFont\">\r\n	<a href=\"/pages/".getBytes("Cp1251");
      _jsp_string110 = "\r\n	<a href=\"/pages/".getBytes("Cp1251");
      _jsp_string61 = "</td>\r\n	<td class=\"smallFont\" align=\"center\">".getBytes("Cp1251");
      _jsp_string69 = "\r\n	</td>\r\n	<td></td>\r\n	<td></td>\r\n</tr>\r\n".getBytes("Cp1251");
      _jsp_string122 = "\r\n	</td>\r\n	<td></td>\r\n	<td></td>\r\n	<td></td>\r\n</tr>\r\n".getBytes("Cp1251");
      _jsp_string41 = "/forum/btn-preview.gif\" height=\"18\" alt=\"Предварительный просмотр\" border=\"0\"></a><a href=\"javascript: submitMessage();\"><img src=\"".getBytes("Cp1251");
      _jsp_string156 = "&create=1&cite_id=".getBytes("Cp1251");
      _jsp_string90 = ">за последний год</OPTION></SELECT></SPAN><input type=\"Image\"src=\"".getBytes("Cp1251");
      _jsp_string55 = "/forum?forum_id=".getBytes("Cp1251");
      _jsp_string125 = "\r\n\r\n</table>\r\n\r\n".getBytes("Cp1251");
      _jsp_string106 = "</b></a>\r\n	</td>\r\n	<td class=\"smallFont\" align=\"center\"><a href=\"/pages/".getBytes("Cp1251");
      _jsp_string34 = "/forum/ico-smile-4.gif\" width=18></A></td>\r\n	</tr>		\r\n	<tr>\r\n	<td><A href=\"javascript:smile(':-/');\"><IMG alt=\"\" border=0 height=20 src=\"".getBytes("Cp1251");
      _jsp_string103 = "\r\n\r\n</a></td>\r\n	<td></td>\r\n	<td></td>\r\n	<td></td>\r\n</tr>\r\n".getBytes("Cp1251");
      _jsp_string169 = "\r\n	не опубликовано\r\n".getBytes("Cp1251");
      _jsp_string53 = "\r\n<tr valign=\"top\">\r\n	<td rowspan=\"3\"><a href=\"\"><img src=\"".getBytes("Cp1251");
      _jsp_string160 = "\r\n		</td>\r\n</tr>\r\n".getBytes("Cp1251");
      _jsp_string105 = "/ans-lst.gif\" width=\"8\" height=\"7\" border=\"0\" hspace=\"1\" align=\"baseline\">&nbsp;<SPAN class=\"c66\">Посл. ответ:</SPAN> ".getBytes("Cp1251");
      _jsp_string131 = "\r\n\r\n\r\n\r\n".getBytes("Cp1251");
      _jsp_string141 = "\r\n<tr bgcolor=\"#DDF3E1\">\r\n	<td><div style=\"width:3\"><SPACER TYPE=\"block\" HEIGHT=\"1\" WIDTH=\"3\"></div></td>\r\n	<td width=\"13%\" class=\"defFont\" height=\"19\"><b class=\"grnTtl\">Автор</b></td>\r\n	<td><div style=\"width:10\"><SPACER TYPE=\"block\" HEIGHT=\"1\" WIDTH=\"10\"></div></td>\r\n	<td width=\"87%\" class=\"defFont\" colspan=\"2\"><b class=\"grnTtl\">Сообщение</b></td>\r\n</tr>\r\n".getBytes("Cp1251");
      _jsp_string19 = "\">\r\n".getBytes("Cp1251");
      _jsp_string28 = "/forum/ico-li.gif\" width=18></A><A href=\"javascript: txt('\\n   [p] ', '');\"><IMG alt=\"Новый абзац\" border=0 height=18 src=\"".getBytes("Cp1251");
      _jsp_string57 = "</b>\r\n<br>\r\n".getBytes("Cp1251");
      _jsp_string153 = "/dvder.gif\" width=\"9\" height=\"9\" border=\"0\"><a href=\"mailto:".getBytes("Cp1251");
      _jsp_string58 = "\r\n	&nbsp;<img src=\"".getBytes("Cp1251");
      _jsp_string46 = "\r\n<!--отступ--><tr><td height=\"13\" colspan=\"5\"><SPACER TYPE=\"block\" HEIGHT=\"1\" WIDTH=\"1\"></td></tr>\r\n".getBytes("Cp1251");
      _jsp_string94 = "\r\n\r\n<!--отступ--><tr><td height=\"10\" colspan=\"5\"><SPACER TYPE=\"block\" HEIGHT=\"1\" WIDTH=\"1\"></td></tr>\r\n".getBytes("Cp1251");
      _jsp_string72 = "\r\n</div>\r\n</td>\r\n<!--заголовок страницы--><td align=\"right\"><img src=\"".getBytes("Cp1251");
      _jsp_string133 = "?forum_id=".getBytes("Cp1251");
      _jsp_string38 = "/forum/ico-smile-8.gif\" width=18></A></td>\r\n	</tr>\r\n</table>\r\n</div>\r\n\r\n<SPAN class=\"smallFont\">\r\n<b style=\"color:#D82E12;\">!</b>&nbsp;Не разрешено<br>\r\n&nbsp;&nbsp;использовать HTML \r\n</SPAN>\r\n\r\n</td>\r\n<td height=\"100%\"><textarea name=\"message\" cols=\"38\" rows=\"8\" style=\"width:100%;height:100%;font-size:10px;font-family:Tahoma;\"  maxlength=\"8000\" wrap=\"on\">".getBytes("Cp1251");
      _jsp_string63 = "/ans-lst.gif\" width=\"8\" height=\"7\" border=\"0\" hspace=\"1\" align=\"baseline\">&nbsp;<SPAN class=\"c66\">Посл. ответ:</SPAN>\r\n".getBytes("Cp1251");
      _jsp_string123 = "\r\n\r\n\r\n<!-- divider --><tr><td height=\"11\" colspan=\"5\" background=\"".getBytes("Cp1251");
      _jsp_string117 = "\r\n	<a href=\"/forum/xt_forum.jsp?action=hot&forum_id=".getBytes("Cp1251");
      _jsp_string10 = "/ttl.gif\" height=\"47\" alt=\"".getBytes("Cp1251");
      _jsp_string97 = "<img src=\"".getBytes("Cp1251");
      _jsp_string136 = "/ans-all.gif\" width=\"18\" height=\"8\" border=\"0\" align=\"absmiddle\"><SPAN class=\"c66\">Сообщений:</SPAN> ".getBytes("Cp1251");
      _jsp_string140 = ">начиная с новых</OPTION>\r\n</SELECT></SPAN><input type=\"Image\"src=\"".getBytes("Cp1251");
      _jsp_string56 = "\" class=\"nonUa\"><b class=\"bluTtl\">".getBytes("Cp1251");
      _jsp_string39 = "</textarea></td>\r\n<td></td>\r\n</tr>\r\n\r\n<!-- divider --><tr><td height=\"11\" colspan=\"4\" background=\"".getBytes("Cp1251");
      _jsp_string107 = "</b></a></td>\r\n	<td class=\"smallFont\" align=\"center\">".getBytes("Cp1251");
      _jsp_string67 = "\" class=\"nonUa\"><b>".getBytes("Cp1251");
      _jsp_string82 = "&create=1\"><img src=\"".getBytes("Cp1251");
      _jsp_string35 = "/forum/ico-smile-5.gif\" width=18></A></td>\r\n	<td><A href=\"javascript:smile(':confused:');\"><IMG alt=\"\" border=0 height=20 src=\"".getBytes("Cp1251");
      _jsp_string87 = ">за последние 7 дней</OPTION>\r\n<OPTION value=3".getBytes("Cp1251");
      _jsp_string29 = "/forum/ico-p.gif\" width=18 hspace=\"4\"></A></td>\r\n<td></td>\r\n</tr>\r\n<!-- divider --><tr><td height=\"11\" colspan=\"4\" background=\"".getBytes("Cp1251");
      _jsp_string84 = "\r\n<td align=\"right\"><NOBR><SPAN class=\"smallFont\"><b class=\"c66\">Показать:</b></SPAN>\r\n<SPAN class=\"SELnn\"><SELECT NAME=\"period\">\r\n<OPTION value=0".getBytes("Cp1251");
      _jsp_string13 = "/blu-ttl-bg.gif\" bgcolor=\"#004896\">\r\n	<tr>\r\n		<td nowrap><img src=\"".getBytes("Cp1251");
      _jsp_string2 = "\r\n<script language=\"JavaScript\">\r\n\r\nfunction txt(text1, text2)\r\n{\r\n    insertText(text1, text2);\r\n}\r\n\r\nfunction smile(txt)\r\n{\r\n    insertText(txt, '');\r\n}\r\n\r\nfunction insertText(text1, text2)\r\n{\r\n    if (document.selection) {\r\n    	document.message_form.message.focus();\r\n    	var ttt = document.message_form.message.document.selection.createRange().text;\r\n    	document.message_form.message.document.selection.createRange().text = text1 + ttt + text2;\r\n    	//document.message_form.message.document.selection.createRange().text = text;\r\n    }\r\n    else\r\n        document.message_form.message.value += text1 + text2;\r\n        \r\n}\r\n\r\nfunction preview()\r\n{\r\n	window.open('','preview','');\r\n	document.forms.message_form.target = 'preview';\r\n	document.forms.message_form.action = '/forum/preview.jsp';\r\n	document.forms.message_form.submit();\r\n	document.forms.message_form.action = '/forum/xt_answer.jsp';\r\n	document.forms.message_form.target='_self';\r\n}\r\n\r\nfunction submitMessage()\r\n{\r\n    var frm = document.message_form;\r\n    if(frm.header.value == '')\r\n    {\r\n        alert('Не указан заголовок.');\r\n        frm.header.focus();\r\n        return;\r\n    }\r\n    frm.submit();\r\n}\r\n\r\n</script>\r\n\r\n<table width=\"100%\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\">\r\n<tr>\r\n<td width=\"100%\" valign=\"top\" class=\"XsmallFont\">\r\n".getBytes("Cp1251");
      _jsp_string71 = "\r\n\r\n<table width=\"100%\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\">\r\n<tr>\r\n<td width=\"100%\" valign=\"top\" class=\"XsmallFont\">\r\n<div style=\"margin-top:8px\">\r\n".getBytes("Cp1251");
      _jsp_string101 = "</a></td>\r\n	<td class=\"defFont\" colspan=\"2\"><a href=\"/pages/".getBytes("Cp1251");
      _jsp_string162 = "&edit=1&item_id=".getBytes("Cp1251");
      _jsp_string3 = "\r\n<div style=\"margin-top:8px\">\r\n".getBytes("Cp1251");
      _jsp_string54 = "/ico-frm.gif\" width=\"13\" height=\"15\" alt=\"Форум закрыт\" border=\"0\" hspace=\"4\"></a></td>\r\n	<td width=\"70%\" class=\"defFont\"><a href=\"/pages/".getBytes("Cp1251");
      _jsp_string88 = ">за последний месяц</OPTION>\r\n<OPTION value=4".getBytes("Cp1251");
      _jsp_string118 = "%>\">горячая</a>\r\n".getBytes("Cp1251");
      _jsp_string99 = "/forum/ico-frm-hot.gif\" width=\"13\" height=\"15\" border=\"0\" hspace=\"4\">".getBytes("Cp1251");
      _jsp_string42 = "/forum/btn-post.gif\" height=\"18\" alt=\"Отправить для публикации на сайте\" border=\"0\" hspace=\"10\"></a></td>\r\n<td></td>\r\n</form>\r\n</tr>\r\n\r\n</table>\r\n".getBytes("Cp1251");
      _jsp_string119 = "\r\n	<a href=\"/forum/xt_forum.jsp?action=simple&forum_id=".getBytes("Cp1251");
      _jsp_string164 = "\r\n	<a href=\"/forum/xt_forum.jsp?action=del&forum_id=".getBytes("Cp1251");
      _jsp_string30 = "/greyln2.gif\"><SPACER TYPE=\"block\" HEIGHT=\"1\" WIDTH=\"1\"></td></tr>\r\n\r\n<tr valign=\"top\">\r\n<td></td>\r\n<td><SPAN class=\"defFont\">Сообщение:</SPAN><br>\r\n\r\n<div align=\"right\">\r\n<table border=\"0\" cellpadding=\"2\" cellspacing=\"0\" style=\"margin-top:8px;\">\r\n	<tr>\r\n	<td><A href=\"javascript:smile(':mad:');\"><IMG alt=\"\" border=0 height=20 src=\"".getBytes("Cp1251");
      _jsp_string158 = "/forum/btn-quote.gif\" height=\"18\" alt=\"Цитировать\" border=\"0\" align=\"right\" hspace=\"5\"></a>".getBytes("Cp1251");
      _jsp_string152 = "/forum/ico-prifile.gif\" alt=\"Посмотреть регистрационные данные\" width=\"10\" height=\"10\" border=\"0\"></a><img src=\"".getBytes("Cp1251");
      _jsp_string81 = "\r\n    <td><a href=\"/pages/".getBytes("Cp1251");
      _jsp_string154 = "/forum/ico-eml.gif\" alt=\"Отправить e-mail\" width=\"10\" height=\"10\" border=\"0\"></a>\r\n		</td>\r\n		<td class=\"smallFont\" colspan=\"2\">".getBytes("Cp1251");
      _jsp_string21 = "\r\n<td><div style=\"width:12;\"><SPACER TYPE=\"block\" HEIGHT=\"1\" WIDTH=\"12\"></div></td>\r\n<td class=\"defFont\"><div style=\"width:160;\"><SPACER TYPE=\"block\" HEIGHT=\"1\" WIDTH=\"160\"></div>Заголовок:</td>\r\n<td width=\"100%\"><input type=\"text\" name=\"header\" value=\"".getBytes("Cp1251");
      _jsp_string27 = "/forum/ico-ul.gif\" width=18 hspace=\"4\"></A><A href=\"javascript: txt('\\n [*] ', '');\"><IMG alt=\"Элемент списка\" border=0 height=18 src=\"".getBytes("Cp1251");
      _jsp_string143 = ">\r\n	<td rowspan=\"3\"><div style=\"width:3\"><SPACER TYPE=\"block\" HEIGHT=\"1\" WIDTH=\"3\"></div></td>\r\n	<td class=\"defFont\">\r\n	<a href=\"/pages/".getBytes("Cp1251");
      _jsp_string65 = " от <a href=\"/pages/".getBytes("Cp1251");
      _jsp_string171 = "\r\n\r\n<!-- divider --><tr><td height=\"11\" colspan=\"5\" background=\"".getBytes("Cp1251");
      _jsp_string114 = "\r\n<tr valign=\"top\">\r\n	<td><div style=\"width:3\"><SPACER TYPE=\"block\" HEIGHT=\"1\" WIDTH=\"3\"></div></td>\r\n	<td class=\"defFont\">\r\n".getBytes("Cp1251");
      _jsp_string33 = "/forum/ico-smile-3.gif\" width=18></A></td>\r\n	<td><A href=\"javascript:smile(':lol:');\"><IMG alt=\"\" border=0 height=20 src=\"".getBytes("Cp1251");
      _jsp_string144 = "\"><b class=\"bluTtl\">".getBytes("Cp1251");
      _jsp_string165 = "&item_id=".getBytes("Cp1251");
      _jsp_string77 = "</SPAN></td>\r\n<td valign=\"bottom\" align=\"right\" class=\"smallFont\"><SPAN class=\"c66\">".getBytes("Cp1251");
      _jsp_string111 = "&page_number=".getBytes("Cp1251");
      _jsp_string59 = "/forum/ico-new-ms.gif\" width=\"9\" height=\"7\" alt=\"\" border=\"0\">\r\n".getBytes("Cp1251");
      _jsp_string37 = "/forum/ico-smile-7.gif\" width=18></A></td>\r\n	<td><A href=\"javascript:smile(':(');\"><IMG alt=\"\" border=0 height=20 src=\"".getBytes("Cp1251");
      _jsp_string124 = "/greyln2.gif\"><SPACER TYPE=\"block\" HEIGHT=\"1\" WIDTH=\"1\"></td></tr>\r\n".getBytes("Cp1251");
      _jsp_string128 = "\r\n<td align=\"right\"><NOBR><SPAN class=\"smallFont\"><b class=\"c66\">Показать:</b></SPAN>\r\n<SPAN class=\"SELnn\"><SELECT>\r\n<OPTION value=0".getBytes("Cp1251");
      _jsp_string130 = "</SPAN></td>\r\n</tr>\r\n</table>\r\n".getBytes("Cp1251");
      _jsp_string48 = "</b></td>\r\n	<td width=\"15%\" align=\"center\" class=\"defFont\"><b class=\"grnTtl\">&nbsp;&nbsp;Темы&nbsp;&nbsp;</b></td>\r\n	<td width=\"15%\" align=\"center\" class=\"defFont\"><b class=\"grnTtl\">Сообщений&nbsp;</b></td>\r\n</tr>\r\n".getBytes("Cp1251");
      _jsp_string0 = "\r\n".getBytes("Cp1251");
      _jsp_string20 = "\r\n<input type=\"hidden\" name=\"item_id\" value=\"".getBytes("Cp1251");
      _jsp_string70 = "\r\n</table>\r\n".getBytes("Cp1251");
      _jsp_string93 = "\r\n<tr bgcolor=\"#DDF3E1\">\r\n	<td class=\"defFont\">&nbsp;</td>\r\n	<td width=\"55%\" class=\"defFont\" height=\"19\"><b class=\"grnTtl\">Темы</b></td>\r\n	<td width=\"15%\" align=\"center\" class=\"defFont\"><b class=\"grnTtl\">Автор</b></td>\r\n	<td width=\"15%\" align=\"center\" class=\"defFont\"><b class=\"grnTtl\">&nbsp;&nbsp;Сообщений&nbsp;&nbsp;</b></td>\r\n	<td width=\"15%\" align=\"center\" class=\"defFont\"><b class=\"grnTtl\">Просмотров&nbsp;</b></td>\r\n</tr>\r\n".getBytes("Cp1251");
      _jsp_string96 = "&theme_id=".getBytes("Cp1251");
      _jsp_string167 = "\r\n	<a href=\"/forum/xt_forum.jsp?action=publ&forum_id=".getBytes("Cp1251");
      _jsp_string17 = "\r\n<table width=\"100%\" border=\"0\" cellpadding=\"1\" cellspacing=\"0\" style=\"margin:8px 0px 0px 0px;\">\r\n<tr>\r\n<form action=\"/forum/xt_answer.jsp\" METHOD=post name=\"message_form\">\r\n<input type=\"hidden\" name=\"forum_id\" value=\"".getBytes("Cp1251");
      _jsp_string40 = "/greyln2.gif\"><SPACER TYPE=\"block\" HEIGHT=\"1\" WIDTH=\"1\"></td></tr>\r\n<tr>\r\n<td></td>\r\n<td></td>\r\n<td><a href=\"javascript: preview();\"><img src=\"".getBytes("Cp1251");
      _jsp_string31 = "/forum/ico-smile-1.gif\" width=18></A></td>\r\n	<td><A href=\"javascript:smile(';)');\"><IMG alt=\"\" border=0 height=20 src=\"".getBytes("Cp1251");
      _jsp_string163 = "\">редактировать</a>&nbsp;\r\n".getBytes("Cp1251");
      _jsp_string142 = "\r\n<tr valign=\"top\"".getBytes("Cp1251");
      _jsp_string25 = "/forum/ico-itlc.gif\" width=18 hspace=\"4\"></A><A href=\"javascript: txt('[u]', '[/u]');\"><IMG alt=\"Подчеркнутый\" border=0 height=18 src=\"".getBytes("Cp1251");
      _jsp_string23 = "/greyln2.gif\"><SPACER TYPE=\"block\" HEIGHT=\"1\" WIDTH=\"1\"></td></tr>\r\n\r\n<tr>\r\n<td></td>\r\n<td class=\"defFont\">Форматирование:</td>\r\n<td class=\"defFont\"><A href=\"javascript: txt('[b]', '[/b]');\"><IMG alt=\"Жирный\" border=0 height=18 src=\"".getBytes("Cp1251");
      _jsp_string121 = "\r\nтема не опубликована\r\n".getBytes("Cp1251");
      _jsp_string43 = "\r\n\r\n<table width=\"100%\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\">\r\n<tr>\r\n<td width=\"100%\" valign=\"top\" class=\"XsmallFont\">\r\n".getBytes("Cp1251");
      _jsp_string4 = "  \r\n<a href=\"".getBytes("Cp1251");
      _jsp_string132 = "\r\n<a href=\"".getBytes("Cp1251");
      _jsp_string26 = "/forum/ico-undrln.gif\" width=18></A><A href=\"javascript: txt('\\n[ul]\\n [*] ', '\\n[/ul]');\"><IMG alt=\"Список\" border=0 height=18 src=\"".getBytes("Cp1251");
      _jsp_string166 = "\">удалить</a>\r\n".getBytes("Cp1251");
      _jsp_string51 = "/greyln2.gif\" width=\"100%\"><SPACER TYPE=\"block\" HEIGHT=\"1\" WIDTH=\"1\"></td><td height=\"11\" colspan=\"4\" background=\"".getBytes("Cp1251");
      _jsp_string109 = "/forum/ico-pg.gif\" width=\"8\" height=\"10\" alt=\"\" border=\"0\" align=\"absbottom\" hspace=\"2\">&nbsp;На страницу:\r\n".getBytes("Cp1251");
      _jsp_string100 = "/ico-frm.gif\" width=\"13\" height=\"15\" border=\"0\" hspace=\"4\">".getBytes("Cp1251");
      _jsp_string68 = "</b></a>\r\n".getBytes("Cp1251");
      _jsp_string138 = ">за последний год</OPTION></SELECT>\r\n<SELECT name=order>\r\n<OPTION value=asc".getBytes("Cp1251");
      _jsp_string127 = "\r\n<td><a href=\"/pages/".getBytes("Cp1251");
      _jsp_string15 = "/2lev/ttl-thms.gif\" width=\"131\" height=\"19\" alt=\"Темы для обсуждения\" border=\"0\"></td>\r\n		<td align=\"right\"><img src=\"".getBytes("Cp1251");
      _jsp_string147 = "/ans-lst.gif\" width=\"8\" height=\"7\" border=\"0\" hspace=\"1\" align=\"baseline\">&nbsp;<SPAN class=\"c66\">Добавлено:</SPAN> ".getBytes("Cp1251");
      _jsp_string24 = "/forum/ico-bld.gif\" width=18></A><A href=\"javascript: txt('[i]', '[/i]');\"><IMG alt=\"Наклонный\" border=0 height=18 src=\"".getBytes("Cp1251");
      _jsp_string22 = "\" style=\"width:100%;font-size:10px;font-family:Tahoma;\" size=\"38\" maxlength=\"100\"></td>\r\n<td><div style=\"width:12;\"><SPACER TYPE=\"block\" HEIGHT=\"1\" WIDTH=\"12\"></div></td>\r\n</tr>\r\n<!-- divider --><tr><td height=\"11\" colspan=\"4\" background=\"".getBytes("Cp1251");
      _jsp_string89 = ">за последние 6 месяцев</OPTION>\r\n<OPTION value=5".getBytes("Cp1251");
      _jsp_string45 = "\r\n<table width=\"100%\" border=\"0\" cellpadding=\"1\" cellspacing=\"0\" style=\"margin:8px 0px 0px 0px;\">\r\n".getBytes("Cp1251");
      _jsp_string157 = "&cite_login=".getBytes("Cp1251");
      _jsp_string7 = "\r\n</div>\r\n".getBytes("Cp1251");
      _jsp_string1 = "\r\n\r\n".getBytes("Cp1251");
      _jsp_string95 = "\r\n<tr valign=\"top\">\r\n	<td rowspan=\"3\"><a href=\"/pages/".getBytes("Cp1251");
      _jsp_string172 = "\r\n</table>\r\n\r\n".getBytes("Cp1251");
      _jsp_string149 = "><td><SPACER TYPE=\"block\" HEIGHT=\"1\" WIDTH=\"1\"></td><td colspan=\"2\" height=\"7\"><SPACER TYPE=\"block\" HEIGHT=\"1\" WIDTH=\"1\"></td></tr>\r\n<tr valign=\"top\"".getBytes("Cp1251");
    } catch (java.io.UnsupportedEncodingException e) {
      e.printStackTrace();
    }
  }
}
