/*
 * JSP generated by Resin 2.0.5 (built Thu Jan 10 21:43:38 PST 2002)
 */

package _admin;
import javax.servlet.*;
import javax.servlet.jsp.*;
import javax.servlet.http.*;
import tengry.ntvmir.*;
import java.util.*;
import java.text.SimpleDateFormat;
import java.io.*;
import tengry.cms.*;
import tengry.cms.core.*;
import tengry.cms.db.*;
import tengry.cms.user.*;
import tengry.cms.tender.*;
import tengry.cms.press.*;
import tengry.cms.product.*;
import tengry.cms.dict.*;
import tengry.cms.vote.*;
import tengry.cms.faq.*;
import tengry.cms.forum.*;
import tengry.cms.mailer.*;

public class _homepage__jsp extends com.caucho.jsp.JavaPage{
  private boolean _caucho_isDead;
  
	public boolean isPagePrivate(String id) throws DBException
	{
		Group g1 = CMSApplication.getApplication().getGroupByName("default");
		Group g2 = CMSApplication.getApplication().getGroupByName("private");
		if(g1 != null && g2 != null)
		{
			return !Group.isR(g1.getAccessCode(id)) && 
					Group.isR(g2.getAccessCode(id));
		}
		else return false;
	}

  
	private final String	separator	= File.separator;
	
	private void drawFolders(JspWriter out, File folder, String path, String url, String selected, String tab) throws IOException
	{
		boolean	isEmpty	= false;
		try
		{
			String sss = path + File.separator + folder.getName();
			
			File[]	files = folder.listFiles();
			
			out.println("<OPTION VALUE=\"" + sss + "\"" + (sss.equals(selected) ? " SELECTED" : "") +">");
			out.println(sss + "</OPTION>");
			for( int i=0; files != null && i < files.length ; i++ )
			{
				if ( files[i].isDirectory() )
					drawFolders(out, files[i], sss, url + File.separator + folder.getName(), selected, tab+tab);
			}
		}catch( Exception e )
		{}
	}
	
	String buildPath(WebTreeNode node)
	{
		if(node == null) return "";
		if(node.getParent() == null)
			return node.getName();
		return buildPath(node.getParent()) + "/" + node.getName();
	}

  
  public void
  _jspService(javax.servlet.http.HttpServletRequest request,
              javax.servlet.http.HttpServletResponse response)
    throws java.io.IOException, javax.servlet.ServletException
  {
    com.caucho.jsp.QPageContext pageContext = (com.caucho.jsp.QPageContext) com.caucho.jsp.QJspFactory.create().getPageContext(this, request, response, null, true, 8192, true);
    javax.servlet.jsp.JspWriter out = (javax.servlet.jsp.JspWriter) pageContext.getOut();
    javax.servlet.ServletConfig config = getServletConfig();
    javax.servlet.Servlet page = this;
    javax.servlet.http.HttpSession session = pageContext.getSession();
    javax.servlet.ServletContext application = pageContext.getServletContext();
    response.setContentType("text/html; charset=windows-1251");
    request.setCharacterEncoding("CP1251");
    try {
      pageContext.write(_jsp_string0, 0, _jsp_string0.length);
      pageContext.write(_jsp_string0, 0, _jsp_string0.length);
      pageContext.write(_jsp_string0, 0, _jsp_string0.length);
      
	// set the Service name for authorization
	String pageId = HomePage.SERVICE_CODE;

      pageContext.write(_jsp_string0, 0, _jsp_string0.length);
      pageContext.write(_jsp_string0, 0, _jsp_string0.length);
      pageContext.write(_jsp_string0, 0, _jsp_string0.length);
      pageContext.write(_jsp_string0, 0, _jsp_string0.length);
      pageContext.write(_jsp_string0, 0, _jsp_string0.length);
      pageContext.write(_jsp_string0, 0, _jsp_string0.length);
      pageContext.write(_jsp_string0, 0, _jsp_string0.length);
      pageContext.write(_jsp_string0, 0, _jsp_string0.length);
      pageContext.write(_jsp_string0, 0, _jsp_string0.length);
      pageContext.write(_jsp_string0, 0, _jsp_string0.length);
      pageContext.write(_jsp_string0, 0, _jsp_string0.length);
      pageContext.write(_jsp_string0, 0, _jsp_string0.length);
      pageContext.write(_jsp_string0, 0, _jsp_string0.length);
      pageContext.write(_jsp_string0, 0, _jsp_string0.length);
      pageContext.write(_jsp_string0, 0, _jsp_string0.length);
      pageContext.write(_jsp_string0, 0, _jsp_string0.length);
      
tengry.cms.core.Admin currentAdmin = (tengry.cms.core.Admin)session.getValue( "admin.user" );
int pageAccessCode = 0;
if( currentAdmin == null )
{
	response.sendRedirect( "/admin/login.jsp" );
	return;
}
else pageAccessCode = currentAdmin.getAccessCode(pageId);

if( ! tengry.cms.core.Admin.isR(pageAccessCode) && ! "admin.index".equals(pageId))
{
	response .sendRedirect( "/admin/index.jsp?err=" + tengry.cms.CMSApplication.PAGE_ERROR_ACCESS_DENIED );
	return;
}

      pageContext.write(_jsp_string1, 0, _jsp_string1.length);
        response.setHeader("Pragma","no-cache"); 
      pageContext.write(_jsp_string0, 0, _jsp_string0.length);
      
    String langCode = request.getParameter("lang_code");
    if(langCode == null || langCode.trim().length() == 0)
        langCode = CMSApplication.getApplication().getPrimaryLangCode();

      pageContext.write(_jsp_string0, 0, _jsp_string0.length);
      pageContext.write(_jsp_string0, 0, _jsp_string0.length);
      
	HomePage hp = HomePage.getInstance(langCode);
	String message = "";

	Enumeration enum = CMSApplication.getApplication().getNodesByTypeCode(langCode, News.SERVICE_CODE);

      pageContext.write(_jsp_string0, 0, _jsp_string0.length);
      pageContext.write(_jsp_string0, 0, _jsp_string0.length);
      
	String actionDone = request.getParameter("action_done");
	if("news".equals(actionDone))
		message = "Параметры новостей на главной странице установлены.";
	if("banner".equals(actionDone))
		message = "Баннеры главной странице установлены.";
	if("themes".equals(actionDone))
		message = "Статус тем форума изменен.";
	else if("img".equals(actionDone))
		message = "Банк фотографий для ротации установлен.";
	else if("announce".equals(actionDone))
		message = "Анонс сохранен.";

      pageContext.write(_jsp_string0, 0, _jsp_string0.length);
      out.flush();
      pageContext.include("/admin/inc/page_start.jsp"+ '?'+ "title="+ "Главная страница"+ '&'+ "header="+ "Настройки главной страницы"+ '&'+ "message="+ (message)+ '&'+ "width="+ "700"+ '&'+ "err="+ (request.getParameter("err")));
      pageContext.write(_jsp_string2, 0, _jsp_string2.length);
      
    java.text.SimpleDateFormat sdf =  new java.text.SimpleDateFormat("dd.MM.yyyy HH:mm");
    Enumeration themeEnum = ForumItem.getHotThemes(langCode, false).elements();
    while(themeEnum.hasMoreElements())
    {
        ForumItem forumTheme = (ForumItem)themeEnum.nextElement();
        String ss = null;
        if(forumTheme.getStatus() == ForumItem.HOT_THEME)
            ss = "c1";
        else
            ss = "c3";

      pageContext.write(_jsp_string3, 0, _jsp_string3.length);
      out.print((ss));
      pageContext.write(_jsp_string4, 0, _jsp_string4.length);
      out.print((forumTheme.getId()));
      pageContext.write(_jsp_string5, 0, _jsp_string5.length);
      out.print((ss));
      pageContext.write(_jsp_string6, 0, _jsp_string6.length);
      out.print((CMSApplication.toHTML(forumTheme.getHeader())));
      pageContext.write(_jsp_string7, 0, _jsp_string7.length);
      out.print((ss));
      pageContext.write(_jsp_string8, 0, _jsp_string8.length);
      out.print((forumTheme.getAnswerAmount()));
      pageContext.write(_jsp_string9, 0, _jsp_string9.length);
      out.print((ss));
      pageContext.write(_jsp_string8, 0, _jsp_string8.length);
      out.print((forumTheme.getLastMessageDate() != null ? sdf.format(forumTheme.getLastMessageDate()) : ""));
      pageContext.write(_jsp_string10, 0, _jsp_string10.length);
        } 
      pageContext.write(_jsp_string11, 0, _jsp_string11.length);
      
	int l = 0;
	while(enum.hasMoreElements())
	{
		WebTreeNode node = (WebTreeNode)enum.nextElement();
		String style = node.isVisible() ? "c3" : "c1";
		String sPrivate = isPagePrivate(node.getId()) ? "<B STYLE=\"color: red;\">*</B>" : "";

      pageContext.write(_jsp_string12, 0, _jsp_string12.length);
      out.print((style));
      pageContext.write(_jsp_string13, 0, _jsp_string13.length);
      out.print((node.getId()));
      pageContext.write(_jsp_string14, 0, _jsp_string14.length);
      out.print((node.getId().equals(hp.getNewsNodeId()) ? " CHECKED" : ""));
      pageContext.write(_jsp_string15, 0, _jsp_string15.length);
      out.print((style));
      pageContext.write(_jsp_string16, 0, _jsp_string16.length);
      out.print((sPrivate + buildPath(node)));
      pageContext.write(_jsp_string17, 0, _jsp_string17.length);
      	
		l++;
	} 

      pageContext.write(_jsp_string18, 0, _jsp_string18.length);
      out.print((hp.isShowNews() ? " CHECKED" : ""));
      pageContext.write(_jsp_string19, 0, _jsp_string19.length);
      out.print((hp.getBannerImg(1)));
      pageContext.write(_jsp_string20, 0, _jsp_string20.length);
      out.print((hp.getBannerUrl(1)));
      pageContext.write(_jsp_string21, 0, _jsp_string21.length);
      out.print((hp.isBannerShow(1) ? " CHECKED" : ""));
      pageContext.write(_jsp_string22, 0, _jsp_string22.length);
      out.print((hp.getBannerImg(2)));
      pageContext.write(_jsp_string23, 0, _jsp_string23.length);
      out.print((hp.getBannerUrl(2)));
      pageContext.write(_jsp_string24, 0, _jsp_string24.length);
      out.print((hp.isBannerShow(2) ? " CHECKED" : ""));
      pageContext.write(_jsp_string25, 0, _jsp_string25.length);
      out.flush();
      pageContext.include("/admin/inc/page_finish.jsp");
      pageContext.write(_jsp_string0, 0, _jsp_string0.length);
    } catch (java.lang.Throwable _jsp_e) {
      pageContext.handlePageException(_jsp_e);
    } finally {
      JspFactory.getDefaultFactory().releasePageContext(pageContext);
    }
  }

  private com.caucho.java.LineMap _caucho_line_map;
  private java.util.ArrayList _caucho_depends = new java.util.ArrayList();

  public boolean _caucho_isModified()
  {
    if (_caucho_isDead)
      return true;
    if (com.caucho.util.CauchoSystem.getVersionId() != 2058990002)
      return true;
    for (int i = _caucho_depends.size() - 1; i >= 0; i--) {
      com.caucho.vfs.Depend depend;
      depend = (com.caucho.vfs.Depend) _caucho_depends.get(i);
      if (depend.isModified())
        return true;
    }
    return false;
  }

  public long _caucho_lastModified()
  {
    return 0;
  }

  public com.caucho.java.LineMap _caucho_getLineMap()
  {
    return _caucho_line_map;
  }

  public void destroy()
  {
      _caucho_isDead = true;
      super.destroy();
  }

  public void init(com.caucho.java.LineMap lineMap,
                   com.caucho.vfs.Path appDir)
    throws javax.servlet.ServletException
  {
    com.caucho.vfs.Path resinHome = com.caucho.util.CauchoSystem.getResinHome();
    com.caucho.vfs.MergePath mergePath = new com.caucho.vfs.MergePath();
    mergePath.addMergePath(appDir);
    mergePath.addMergePath(resinHome);
    mergePath.addClassPath(getClass().getClassLoader());
    _caucho_line_map = new com.caucho.java.LineMap("_homepage__jsp.java", "/usr/local/apache/htdocs/ntvmir/admin/homepage.jsp");
    _caucho_line_map.add("/admin/homepage.jsp", 1, 1);
    _caucho_line_map.add("/admin/inc/page_init.jsp", 1, 1);
    _caucho_line_map.add("/admin/inc/functions/is_page_private.jsp", 1, 28);
    _caucho_line_map.add("/usr/local/apache/htdocs/ntvmir/admin/homepage.jsp", 16, 41);
    _caucho_line_map.add("/admin/homepage.jsp", 1, 87);
    _caucho_line_map.add(8, 95);
    _caucho_line_map.add("/admin/inc/page_init.jsp", 1, 95);
    _caucho_line_map.add("/admin/inc/authorize.jsp", 1, 110);
    _caucho_line_map.add("/admin/inc/page_init.jsp", 17, 127);
    _caucho_line_map.add(18, 129);
    _caucho_line_map.add("/usr/local/apache/htdocs/ntvmir/admin/homepage.jsp", 9, 135);
    _caucho_line_map.add("/admin/inc/functions/is_page_private.jsp", 1, 135);
    _caucho_line_map.add("/usr/local/apache/htdocs/ntvmir/admin/homepage.jsp", 10, 136);
    _caucho_line_map.add(16, 143);
    _caucho_line_map.add(47, 144);
    _caucho_line_map.add(60, 158);
    _caucho_line_map.add(111, 161);
    _caucho_line_map.add(125, 176);
    _caucho_line_map.add(128, 180);
    _caucho_line_map.add(131, 184);
    _caucho_line_map.add(134, 188);
    _caucho_line_map.add(137, 190);
    _caucho_line_map.add(172, 192);
    _caucho_line_map.add(182, 203);
    _caucho_line_map.add(182, 205);
    _caucho_line_map.add(185, 207);
    _caucho_line_map.add(190, 211);
    _caucho_line_map.add(196, 216);
    _caucho_line_map.add(242, 218);
    _caucho_line_map.add(253, 220);
    _caucho_line_map.add(259, 222);
    _caucho_line_map.add(281, 224);
    _caucho_line_map.add(292, 226);
    _caucho_line_map.add(298, 228);
    _caucho_line_map.add(310, 230);
    com.caucho.vfs.Depend depend;
    depend = new com.caucho.vfs.Depend(mergePath.lookup("file:/usr/local/apache/htdocs/ntvmir/admin/inc/page_init.jsp"), 1043089496000L, 877L);
    _caucho_depends.add(depend);
    depend = new com.caucho.vfs.Depend(mergePath.lookup("file:/usr/local/apache/htdocs/ntvmir/admin/inc/authorize.jsp"), 1019117520000L, 486L);
    _caucho_depends.add(depend);
    depend = new com.caucho.vfs.Depend(mergePath.lookup("file:/usr/local/apache/htdocs/ntvmir/admin/inc/functions/is_page_private.jsp"), 1018937983000L, 373L);
    _caucho_depends.add(depend);
    depend = new com.caucho.vfs.Depend(mergePath.lookup("file:/usr/local/apache/htdocs/ntvmir/admin/homepage.jsp"), 1044525486000L, 9935L);
    _caucho_depends.add(depend);
  }

  private static byte []_jsp_string13;
  private static byte []_jsp_string4;
  private static byte []_jsp_string7;
  private static byte []_jsp_string15;
  private static byte []_jsp_string6;
  private static byte []_jsp_string12;
  private static byte []_jsp_string24;
  private static byte []_jsp_string25;
  private static byte []_jsp_string3;
  private static byte []_jsp_string5;
  private static byte []_jsp_string19;
  private static byte []_jsp_string0;
  private static byte []_jsp_string9;
  private static byte []_jsp_string22;
  private static byte []_jsp_string8;
  private static byte []_jsp_string14;
  private static byte []_jsp_string18;
  private static byte []_jsp_string2;
  private static byte []_jsp_string10;
  private static byte []_jsp_string16;
  private static byte []_jsp_string11;
  private static byte []_jsp_string17;
  private static byte []_jsp_string21;
  private static byte []_jsp_string1;
  private static byte []_jsp_string20;
  private static byte []_jsp_string23;
  static {
    try {
      _jsp_string13 = "\" VALIGN=\"middle\">\r\n<INPUT TYPE=\"radio\" NAME=\"news_page_id\" VALUE=\"".getBytes("Cp1251");
      _jsp_string4 = "\" VALIGN=\"middle\">\r\n    <INPUT TYPE=\"checkbox\" NAME=\"theme_id\" VALUE=\"".getBytes("Cp1251");
      _jsp_string7 = "</A></DIV>\r\n</TD>\r\n<TD HEIGHT=\"20\" WIDTH=\"1%\" CLASS=\"".getBytes("Cp1251");
      _jsp_string15 = ">\r\n</TD>\r\n\r\n<TD HEIGHT=\"20\" CLASS=\"".getBytes("Cp1251");
      _jsp_string6 = "\"><DIV STYLE=\"padding-left:6px;padding-right:6px\">\r\n    <A>".getBytes("Cp1251");
      _jsp_string12 = "\r\n<TR>\r\n<TD WIDTH=\"1%\" HEIGHT=\"20\" CLASS=\"".getBytes("Cp1251");
      _jsp_string24 = "\">\r\n</TD>\r\n</TR>\r\n\r\n<TR>\r\n<TD COLSPAN=\"2\" HEIGHT=\"20\" CLASS=\"c3\">\r\n<INPUT TYPE=\"checkbox\" NAME=\"banner_show_2\" SIZE=\"5\" VALUE=\"1\" ID=\"ccc2\" ".getBytes("Cp1251");
      _jsp_string25 = "> <LABEL FOR=\"ccc2\">Показывать второй баннер на главной странице</LABEL><BR>\r\n</TD>\r\n</TR>\r\n\r\n\r\n<TR>\r\n<TD ALIGN=\"center\" COLSPAN=\"2\">\r\n<INPUT TYPE=\"button\" VALUE=\"Установить\" onClick=\"submitBannerForm();\">\r\n</TD>\r\n</TR>\r\n</FORM>\r\n</TABLE>\r\n".getBytes("Cp1251");
      _jsp_string3 = "\r\n<TR>\r\n<TD HEIGHT=\"20\" WIDTH=\"1%\" CLASS=\"".getBytes("Cp1251");
      _jsp_string5 = "\">\r\n</TD>\r\n<TD HEIGHT=\"20\" WIDTH=\"100%\" CLASS=\"".getBytes("Cp1251");
      _jsp_string19 = "> <LABEL FOR=\"ccc0\">Показывать блок \"Топ новость\" на главной странице</LABEL><BR>\r\n</TD>\r\n</TR>\r\n<TR>\r\n<TD ALIGN=\"center\" COLSPAN=\"2\">\r\n<INPUT TYPE=\"button\" VALUE=\"Установить\" onClick=\"submitNewsForm();\">\r\n</TD>\r\n</TR>\r\n</FORM>\r\n</TABLE>\r\n<BR>\r\n<TABLE BORDER=\"0\" CELLSPACING=\"1\" CELLPADDING=\"1\" WIDTH=\"700\">\r\n<TR>\r\n<TD ROWSPAN=\"3\" WIDTH=\"10\"><IMG SRC=\"/admin/img/blank.gif\" WIDTH=\"10\" HEIGHT=\"1\"><BR></TD>\r\n<TD WIDTH=\"15\" ALIGN=\"center\"><B STYLE=\"color: red;\">*</B></TD><TD ALIGN=\"center\"> &#151; </TD>\r\n<TD ALIGN=\"left\">просмотр ленты доступен только для зарегистрированных пользователей;</TD>\r\n</TR>\r\n<TR>\r\n<TD WIDTH=\"15\" CLASS=\"c3\"><IMG SRC=\"/admin/img/blank.gif\" WIDTH=\"15\" HEIGHT=\"15\"><BR></TD><TD ALIGN=\"center\"> &#151; </TD>\r\n<TD ALIGN=\"left\">лента опубликована в пользовательской части;</TD>\r\n</TR>\r\n<TR>\r\n<TD WIDTH=\"15\" CLASS=\"c1\"><IMG SRC=\"/admin/img/blank.gif\" WIDTH=\"15\" HEIGHT=\"15\"><BR></TD><TD ALIGN=\"center\"> &#151; </TD>\r\n<TD ALIGN=\"left\">лента не опубликована в пользовательской части;</TD>\r\n</TR>\r\n</TABLE>\r\n\r\n\r\n<BR><BR>\r\n\r\n<TABLE BORDER=\"0\" CELLSPACING=\"1\" CELLPADDING=\"1\" WIDTH=\"700\">\r\n<FORM NAME=\"banner_form\" ACTION=\"xt_homepage.jsp\">\r\n<INPUT TYPE=\"hidden\" NAME=\"mode\" VALUE=\"banner\">\r\n<TR>\r\n<TD COLSPAN=\"2\" ALIGN=\"center\" CLASS=\"c2\" HEIGHT=\"20\">\r\n<B>Первый баннер</B>\r\n</TD>\r\n</TR>\r\n\r\n<TR>\r\n<TD WIDTH=\"1%\" HEIGHT=\"20\" CLASS=\"c3\" VALIGN=\"middle\">\r\n<DIV STYLE=\"padding-left:6px;padding-right:6px\">\r\n<NOBR>Адрес баннера</NOBR>\r\n</DIV>\r\n</TD>\r\n<TD WIDTH=\"1%\" HEIGHT=\"20\" CLASS=\"c3\" VALIGN=\"middle\">\r\n<INPUT TYPE=\"text\" STYLE=\"width: 100%\" NAME=\"banner_img\" VALUE=\"".getBytes("Cp1251");
      _jsp_string0 = "\r\n".getBytes("Cp1251");
      _jsp_string9 = "</NOBR></DIV>\r\n</TD>\r\n<TD HEIGHT=\"20\" WIDTH=\"1%\" CLASS=\"".getBytes("Cp1251");
      _jsp_string22 = "> <LABEL FOR=\"ccc1\">Показывать первый баннер на главной странице</LABEL><BR>\r\n</TD>\r\n</TR>\r\n\r\n\r\n\r\n\r\n\r\n\r\n<TR>\r\n<TD COLSPAN=\"2\" ALIGN=\"center\" CLASS=\"c2\" HEIGHT=\"20\">\r\n<B>Второй баннер</B>\r\n</TD>\r\n</TR>\r\n\r\n<TR>\r\n<TD WIDTH=\"1%\" HEIGHT=\"20\" CLASS=\"c3\" VALIGN=\"middle\">\r\n<DIV STYLE=\"padding-left:6px;padding-right:6px\">\r\n<NOBR>Адрес баннера</NOBR>\r\n</DIV>\r\n</TD>\r\n<TD WIDTH=\"100%\" HEIGHT=\"20\" CLASS=\"c3\" VALIGN=\"middle\">\r\n<INPUT TYPE=\"text\" STYLE=\"width: 100%\" NAME=\"banner_img\" VALUE=\"".getBytes("Cp1251");
      _jsp_string8 = "\"><DIV STYLE=\"padding-left:6px;padding-right:6px\">\r\n    <NOBR>".getBytes("Cp1251");
      _jsp_string14 = "\"".getBytes("Cp1251");
      _jsp_string18 = "\r\n<TR>\r\n<TD COLSPAN=\"2\" HEIGHT=\"20\" CLASS=\"c3\">\r\n<INPUT TYPE=\"checkbox\" NAME=\"news_show\" SIZE=\"5\" VALUE=\"1\" ID=\"ccc0\" ".getBytes("Cp1251");
      _jsp_string2 = "\r\n\r\n<SCRIPT LANGUAGE=\"javascript\">\r\nfunction submitNewsForm()\r\n{\r\n	if(confirm(\"Установить?\"))\r\n		document.forms['news_form'].submit();\r\n}\r\nfunction submitBannerForm()\r\n{\r\n	if(confirm(\"Установить?\"))\r\n		document.forms['banner_form'].submit();\r\n}\r\nfunction submitThemeForm(pub)\r\n{\r\n    document.theme_form.submode.value=pub;\r\n	if(confirm(\"Изменить статус?\"))\r\n		document.theme_form.submit();\r\n}\r\n</SCRIPT>\r\n\r\n\r\n\r\n<TABLE BORDER=\"0\" CELLSPACING=\"1\" CELLPADDING=\"1\" WIDTH=\"700\">\r\n<FORM NAME=\"theme_form\" ACTION=\"xt_homepage.jsp\">\r\n<INPUT TYPE=\"hidden\" NAME=\"mode\" VALUE=\"themes\">\r\n<INPUT TYPE=\"hidden\" NAME=\"submode\" VALUE=\"publ\">\r\n<TR>\r\n<TD HEIGHT=\"20\" CLASS=\"c2\" COLSPAN=\"5\" ALIGN=\"center\">\r\n<B>Горячие темы форума</B>\r\n</TD>\r\n</TR>\r\n<TR>\r\n<TD HEIGHT=\"20\" WIDTH=\"1%\" CLASS=\"c2\" VALIGN=\"middle\"></TD>\r\n<TD HEIGHT=\"20\" WIDTH=\"100%\" CLASS=\"c2\"><DIV STYLE=\"padding-left:6px;padding-right:6px\">\r\n    Заголовок темы</DIV>\r\n</TD>\r\n<TD HEIGHT=\"20\" WIDTH=\"1%\" CLASS=\"c2\"><DIV STYLE=\"padding-left:6px;padding-right:6px\">\r\n    отв.</DIV>\r\n</TD>\r\n<TD HEIGHT=\"20\" WIDTH=\"1%\" CLASS=\"c2\"><DIV STYLE=\"padding-left:6px;padding-right:6px\">\r\n    <NOBR>посл. ответ</NOBR></DIV>\r\n</TD>\r\n</TR>\r\n\r\n".getBytes("Cp1251");
      _jsp_string10 = "</NOBR></DIV>\r\n</TD>\r\n</TR>\r\n".getBytes("Cp1251");
      _jsp_string16 = "\">\r\n<DIV STYLE=\"padding-left:6px;padding-right:6px\">\r\n".getBytes("Cp1251");
      _jsp_string11 = "\r\n<TR>\r\n<TD ALIGN=\"center\" COLSPAN=\"4\">\r\n<A HREF=\"javascript: submitThemeForm('publ');\">Разместить</A> |\r\n<A HREF=\"javascript: submitThemeForm('unpubl');\">Снять</A> |\r\n<A HREF=\"javascript: submitThemeForm('unhot');\">Убрать из \"горячих\"</A>\r\n</TD>\r\n</TR>\r\n</FORM>\r\n</TABLE>\r\n<BR>\r\n<TABLE BORDER=\"0\" CELLSPACING=\"1\" CELLPADDING=\"1\" WIDTH=\"700\">\r\n<TR>\r\n<TD ROWSPAN=\"2\" WIDTH=\"10\"><IMG SRC=\"/admin/img/blank.gif\" WIDTH=\"10\" HEIGHT=\"1\"><BR></TD>\r\n<TD WIDTH=\"15\" CLASS=\"c3\"><IMG SRC=\"/admin/img/blank.gif\" WIDTH=\"15\" HEIGHT=\"15\"><BR></TD><TD ALIGN=\"center\"> &#151; </TD>\r\n<TD ALIGN=\"left\">тема размещена на главной странице;</TD>\r\n</TR>\r\n<TR>\r\n<TD WIDTH=\"15\" CLASS=\"c1\"><IMG SRC=\"/admin/img/blank.gif\" WIDTH=\"15\" HEIGHT=\"15\"><BR></TD><TD ALIGN=\"center\"> &#151; </TD>\r\n<TD ALIGN=\"left\">тема не размещена на главной странице;</TD>\r\n</TR>\r\n</TABLE>\r\n\r\n\r\n\r\n<BR><BR>\r\n\r\n<TABLE BORDER=\"0\" CELLSPACING=\"1\" CELLPADDING=\"1\" WIDTH=\"700\">\r\n<FORM NAME=\"news_form\" ACTION=\"xt_homepage.jsp\">\r\n<INPUT TYPE=\"hidden\" NAME=\"mode\" VALUE=\"news\">\r\n<TR>\r\n<TD COLSPAN=\"2\" ALIGN=\"center\" CLASS=\"c2\" HEIGHT=\"20\">\r\n<B>Новостная лента для главной страницы</B>\r\n</TD>\r\n</TR>\r\n".getBytes("Cp1251");
      _jsp_string17 = "\r\n</DIV></TD>\r\n</TR>\r\n".getBytes("Cp1251");
      _jsp_string21 = "\">\r\n</TD>\r\n</TR>\r\n\r\n<TR>\r\n<TD COLSPAN=\"2\" HEIGHT=\"20\" CLASS=\"c3\">\r\n<INPUT TYPE=\"checkbox\" NAME=\"banner_show_1\" SIZE=\"5\" VALUE=\"1\" ID=\"ccc1\" ".getBytes("Cp1251");
      _jsp_string1 = "\r\n\r\n".getBytes("Cp1251");
      _jsp_string20 = "\">\r\n</TD>\r\n</TR>\r\n\r\n<TR>\r\n<TD WIDTH=\"1%\" HEIGHT=\"20\" CLASS=\"c3\" VALIGN=\"middle\">\r\n<DIV STYLE=\"padding-left:6px;padding-right:6px\">\r\n<NOBR>Ссылка баннера</NOBR>\r\n</DIV>\r\n</TD>\r\n<TD WIDTH=\"1%\" HEIGHT=\"20\" CLASS=\"c3\" VALIGN=\"middle\">\r\n<INPUT TYPE=\"text\" STYLE=\"width: 100%\" NAME=\"banner_url\" VALUE=\"".getBytes("Cp1251");
      _jsp_string23 = "\">\r\n</TD>\r\n</TR>\r\n\r\n<TR>\r\n<TD WIDTH=\"1%\" HEIGHT=\"20\" CLASS=\"c3\" VALIGN=\"middle\">\r\n<DIV STYLE=\"padding-left:6px;padding-right:6px\">\r\n<NOBR>Ссылка баннера</NOBR>\r\n</DIV>\r\n</TD>\r\n<TD WIDTH=\"100%\" HEIGHT=\"20\" CLASS=\"c3\" VALIGN=\"middle\">\r\n<INPUT TYPE=\"text\" STYLE=\"width: 100%\" NAME=\"banner_url\" VALUE=\"".getBytes("Cp1251");
    } catch (java.io.UnsupportedEncodingException e) {
      e.printStackTrace();
    }
  }
}
