/*
 * JSP generated by Resin 2.0.5 (built Thu Jan 10 21:43:38 PST 2002)
 */

package _admin;
import javax.servlet.*;
import javax.servlet.jsp.*;
import javax.servlet.http.*;
import java.util.*;
import java.text.SimpleDateFormat;
import java.io.*;
import tengry.cms.*;
import tengry.cms.core.*;
import tengry.cms.db.*;
import tengry.cms.user.*;
import tengry.cms.tender.*;
import tengry.cms.press.*;
import tengry.cms.product.*;
import tengry.cms.dict.*;
import tengry.cms.vote.*;
import tengry.cms.faq.*;
import tengry.cms.forum.*;
import tengry.cms.mailer.*;

public class _index__jsp extends com.caucho.jsp.JavaPage{
  private boolean _caucho_isDead;
  
  public void
  _jspService(javax.servlet.http.HttpServletRequest request,
              javax.servlet.http.HttpServletResponse response)
    throws java.io.IOException, javax.servlet.ServletException
  {
    com.caucho.jsp.QPageContext pageContext = (com.caucho.jsp.QPageContext) com.caucho.jsp.QJspFactory.create().getPageContext(this, request, response, null, true, 8192, true);
    javax.servlet.jsp.JspWriter out = (javax.servlet.jsp.JspWriter) pageContext.getOut();
    javax.servlet.ServletConfig config = getServletConfig();
    javax.servlet.Servlet page = this;
    javax.servlet.http.HttpSession session = pageContext.getSession();
    javax.servlet.ServletContext application = pageContext.getServletContext();
    response.setContentType("text/html; charset=windows-1251");
    request.setCharacterEncoding("CP1251");
    try {
      pageContext.write(_jsp_string0, 0, _jsp_string0.length);
      pageContext.write(_jsp_string0, 0, _jsp_string0.length);
       String pageId = "admin.index"; 
      pageContext.write(_jsp_string0, 0, _jsp_string0.length);
      pageContext.write(_jsp_string0, 0, _jsp_string0.length);
      pageContext.write(_jsp_string0, 0, _jsp_string0.length);
      pageContext.write(_jsp_string0, 0, _jsp_string0.length);
      pageContext.write(_jsp_string0, 0, _jsp_string0.length);
      pageContext.write(_jsp_string0, 0, _jsp_string0.length);
      pageContext.write(_jsp_string0, 0, _jsp_string0.length);
      pageContext.write(_jsp_string0, 0, _jsp_string0.length);
      pageContext.write(_jsp_string0, 0, _jsp_string0.length);
      pageContext.write(_jsp_string0, 0, _jsp_string0.length);
      pageContext.write(_jsp_string0, 0, _jsp_string0.length);
      pageContext.write(_jsp_string0, 0, _jsp_string0.length);
      pageContext.write(_jsp_string0, 0, _jsp_string0.length);
      pageContext.write(_jsp_string0, 0, _jsp_string0.length);
      pageContext.write(_jsp_string0, 0, _jsp_string0.length);
      pageContext.write(_jsp_string0, 0, _jsp_string0.length);
      
tengry.cms.core.Admin currentAdmin = (tengry.cms.core.Admin)session.getValue( "admin.user" );
int pageAccessCode = 0;
if( currentAdmin == null )
{
	response.sendRedirect( "/admin/login.jsp" );
	return;
}
else pageAccessCode = currentAdmin.getAccessCode(pageId);

if( ! tengry.cms.core.Admin.isR(pageAccessCode) && ! "admin.index".equals(pageId))
{
	response .sendRedirect( "/admin/index.jsp?err=" + tengry.cms.CMSApplication.PAGE_ERROR_ACCESS_DENIED );
	return;
}

      pageContext.write(_jsp_string1, 0, _jsp_string1.length);
        response.setHeader("Pragma","no-cache"); 
      pageContext.write(_jsp_string0, 0, _jsp_string0.length);
      
    String langCode = request.getParameter("lang_code");
    if(langCode == null || langCode.trim().length() == 0)
        langCode = CMSApplication.getApplication().getPrimaryLangCode();

      pageContext.write(_jsp_string0, 0, _jsp_string0.length);
      out.flush();
      pageContext.include("/admin/inc/page_start.jsp"+ '?'+ "title="+ "Административная часть"+ '&'+ "err="+ (request.getParameter("err")));
      pageContext.write(_jsp_string1, 0, _jsp_string1.length);
      out.flush();
      pageContext.include("/admin/inc/page_finish.jsp");
      pageContext.write(_jsp_string0, 0, _jsp_string0.length);
    } catch (java.lang.Throwable _jsp_e) {
      pageContext.handlePageException(_jsp_e);
    } finally {
      JspFactory.getDefaultFactory().releasePageContext(pageContext);
    }
  }

  private com.caucho.java.LineMap _caucho_line_map;
  private java.util.ArrayList _caucho_depends = new java.util.ArrayList();

  public boolean _caucho_isModified()
  {
    if (_caucho_isDead)
      return true;
    if (com.caucho.util.CauchoSystem.getVersionId() != 2058990002)
      return true;
    for (int i = _caucho_depends.size() - 1; i >= 0; i--) {
      com.caucho.vfs.Depend depend;
      depend = (com.caucho.vfs.Depend) _caucho_depends.get(i);
      if (depend.isModified())
        return true;
    }
    return false;
  }

  public long _caucho_lastModified()
  {
    return 0;
  }

  public com.caucho.java.LineMap _caucho_getLineMap()
  {
    return _caucho_line_map;
  }

  public void destroy()
  {
      _caucho_isDead = true;
      super.destroy();
  }

  public void init(com.caucho.java.LineMap lineMap,
                   com.caucho.vfs.Path appDir)
    throws javax.servlet.ServletException
  {
    com.caucho.vfs.Path resinHome = com.caucho.util.CauchoSystem.getResinHome();
    com.caucho.vfs.MergePath mergePath = new com.caucho.vfs.MergePath();
    mergePath.addMergePath(appDir);
    mergePath.addMergePath(resinHome);
    mergePath.addClassPath(getClass().getClassLoader());
    _caucho_line_map = new com.caucho.java.LineMap("_index__jsp.java", "/usr/local/apache/htdocs/ntvmir/admin/index.jsp");
    _caucho_line_map.add("/admin/index.jsp", 1, 1);
    _caucho_line_map.add("/admin/inc/page_init.jsp", 1, 1);
    _caucho_line_map.add("/admin/index.jsp", 1, 42);
    _caucho_line_map.add(4, 46);
    _caucho_line_map.add("/admin/inc/page_init.jsp", 1, 46);
    _caucho_line_map.add("/admin/inc/authorize.jsp", 1, 61);
    _caucho_line_map.add("/admin/inc/page_init.jsp", 17, 78);
    _caucho_line_map.add(18, 80);
    _caucho_line_map.add("/usr/local/apache/htdocs/ntvmir/admin/index.jsp", 5, 86);
    _caucho_line_map.add(10, 89);
    com.caucho.vfs.Depend depend;
    depend = new com.caucho.vfs.Depend(mergePath.lookup("file:/usr/local/apache/htdocs/ntvmir/admin/inc/page_init.jsp"), 1043089496000L, 877L);
    _caucho_depends.add(depend);
    depend = new com.caucho.vfs.Depend(mergePath.lookup("file:/usr/local/apache/htdocs/ntvmir/admin/inc/authorize.jsp"), 1019117520000L, 486L);
    _caucho_depends.add(depend);
    depend = new com.caucho.vfs.Depend(mergePath.lookup("file:/usr/local/apache/htdocs/ntvmir/admin/index.jsp"), 1039518709000L, 439L);
    _caucho_depends.add(depend);
  }

  private static byte []_jsp_string1;
  private static byte []_jsp_string0;
  static {
    try {
      _jsp_string1 = "\r\n\r\n".getBytes("Cp1251");
      _jsp_string0 = "\r\n".getBytes("Cp1251");
    } catch (java.io.UnsupportedEncodingException e) {
      e.printStackTrace();
    }
  }
}
