/*
 * JSP generated by Resin 2.0.5 (built Thu Jan 10 21:43:38 PST 2002)
 */

package _admin;
import javax.servlet.*;
import javax.servlet.jsp.*;
import javax.servlet.http.*;
import tengry.cms.*;
import java.util.*;

public class _login__jsp extends com.caucho.jsp.JavaPage{
  private boolean _caucho_isDead;
  
  public void
  _jspService(javax.servlet.http.HttpServletRequest request,
              javax.servlet.http.HttpServletResponse response)
    throws java.io.IOException, javax.servlet.ServletException
  {
    com.caucho.jsp.QPageContext pageContext = (com.caucho.jsp.QPageContext) com.caucho.jsp.QJspFactory.create().getPageContext(this, request, response, null, true, 8192, true);
    javax.servlet.jsp.JspWriter out = (javax.servlet.jsp.JspWriter) pageContext.getOut();
    javax.servlet.ServletConfig config = getServletConfig();
    javax.servlet.Servlet page = this;
    javax.servlet.http.HttpSession session = pageContext.getSession();
    javax.servlet.ServletContext application = pageContext.getServletContext();
    response.setContentType("text/html; charset=windows-1251");
    request.setCharacterEncoding("CP1251");
    try {
      pageContext.write(_jsp_string0, 0, _jsp_string0.length);
      pageContext.write(_jsp_string0, 0, _jsp_string0.length);
      pageContext.write(_jsp_string0, 0, _jsp_string0.length);
      pageContext.write(_jsp_string0, 0, _jsp_string0.length);
      
    response.setHeader( "Pragma", "no-cache" );

      pageContext.write(_jsp_string0, 0, _jsp_string0.length);
      out.flush();
      pageContext.include("/admin/inc/page_header.jsp"+ '?'+ "title="+ "Авторизация администратора");
      pageContext.write(_jsp_string1, 0, _jsp_string1.length);
       if( "1".equals( request.getParameter( "err" ))){ 
      pageContext.write(_jsp_string2, 0, _jsp_string2.length);
      	} 
      pageContext.write(_jsp_string3, 0, _jsp_string3.length);
    } catch (java.lang.Throwable _jsp_e) {
      pageContext.handlePageException(_jsp_e);
    } finally {
      JspFactory.getDefaultFactory().releasePageContext(pageContext);
    }
  }

  private com.caucho.java.LineMap _caucho_line_map;
  private java.util.ArrayList _caucho_depends = new java.util.ArrayList();

  public boolean _caucho_isModified()
  {
    if (_caucho_isDead)
      return true;
    if (com.caucho.util.CauchoSystem.getVersionId() != 2058990002)
      return true;
    for (int i = _caucho_depends.size() - 1; i >= 0; i--) {
      com.caucho.vfs.Depend depend;
      depend = (com.caucho.vfs.Depend) _caucho_depends.get(i);
      if (depend.isModified())
        return true;
    }
    return false;
  }

  public long _caucho_lastModified()
  {
    return 0;
  }

  public com.caucho.java.LineMap _caucho_getLineMap()
  {
    return _caucho_line_map;
  }

  public void destroy()
  {
      _caucho_isDead = true;
      super.destroy();
  }

  public void init(com.caucho.java.LineMap lineMap,
                   com.caucho.vfs.Path appDir)
    throws javax.servlet.ServletException
  {
    com.caucho.vfs.Path resinHome = com.caucho.util.CauchoSystem.getResinHome();
    com.caucho.vfs.MergePath mergePath = new com.caucho.vfs.MergePath();
    mergePath.addMergePath(appDir);
    mergePath.addMergePath(resinHome);
    mergePath.addClassPath(getClass().getClassLoader());
    _caucho_line_map = new com.caucho.java.LineMap("_login__jsp.java", "/admin/login.jsp");
    _caucho_line_map.add(1, 1);
    _caucho_line_map.add(1, 29);
    _caucho_line_map.add(8, 37);
    _caucho_line_map.add(12, 40);
    com.caucho.vfs.Depend depend;
    depend = new com.caucho.vfs.Depend(mergePath.lookup("file:/usr/local/apache/htdocs/ntvmir/admin/login.jsp"), 1038503385000L, 1440L);
    _caucho_depends.add(depend);
  }

  private static byte []_jsp_string3;
  private static byte []_jsp_string2;
  private static byte []_jsp_string0;
  private static byte []_jsp_string1;
  static {
    try {
      _jsp_string3 = "\r\n<FORM ACTION=\"xt_login.jsp\" METHOD=\"POST\">\r\n<TABLE WIDTH=\"350\" BORDER=\"0\" CELLPADDING=\"0\" CELLSPACING=\"1\">\r\n<TR ALIGN=\"center\">\r\n<TD CLASS=\"titnew\" HEIGHT=\"20\" COLSPAN=\"2\">\r\n<DIV STYLE=\"padding-left:6px;padding-right:6px;\" CLASS=\"titnew\">Авторизация</DIV>\r\n</TD>\r\n</TR>\r\n<TR>\r\n<TD CLASS=\"c2\" HEIGHT=\"20\" WIDTH=\"30%\">\r\n<DIV STYLE=\"padding-left:6px;padding-right:6px;\" CLASS=\"\">Login:</DIV>\r\n</TD>\r\n<TD CLASS=\"c2\">\r\n<DIV STYLE=\"padding-left:6px;padding-right:6px;\" CLASS=\"\"><INPUT TYPE=\"text\" NAME=\"login\" VALUE=\"\" SIZE=\"30\"></DIV>\r\n</TD>\r\n</TR>\r\n\r\n<TR>\r\n<TD CLASS=\"c2\" HEIGHT=\"20\" WIDTH=\"30%\">\r\n<DIV STYLE=\"padding-left:6px;padding-right:6px;\" CLASS=\"\">Пароль:</DIV>\r\n</TD>\r\n<TD CLASS=\"c2\">\r\n<DIV STYLE=\"padding-left:6px;padding-right:6px;\" CLASS=\"\"><INPUT TYPE=\"password\" NAME=\"password\" VALUE=\"\" SIZE=\"30\"></DIV>\r\n</TD>\r\n</TR>\r\n\r\n\r\n<TR ALIGN=\"center\">\r\n<TD CLASS=\"c2\" COLSPAN=2>\r\n<INPUT TYPE=\"submit\" VALUE=\"Войти в систему\">\r\n</TD>\r\n</TR>\r\n</TABLE>\r\n</FORM>\r\n\r\n</BODY>\r\n</HTML>\r\n".getBytes("Cp1251");
      _jsp_string2 = "\r\n<B>Ошибка авторизации</B><BR>\r\n".getBytes("Cp1251");
      _jsp_string0 = "\r\n".getBytes("Cp1251");
      _jsp_string1 = "\r\n<BR><BR>\r\n".getBytes("Cp1251");
    } catch (java.io.UnsupportedEncodingException e) {
      e.printStackTrace();
    }
  }
}
