<TABLE BORDER="0" CELLPADDING="0" CELLSPACING="0" WIDTH="100%" HEIGHT="50">
<TR VALIGN="top">
<TD><IMG SRC="<%=des%>/main/lft_bot.gif" WIDTH="559" HEIGHT="32"></TD>
<TD WIDTH="100%" BACKGROUND="<%=des%>/main/bg_bot.gif">
<DIV STYLE="margin-top:15;padding:0 5 0 10;font-family:Verdana;font-size:10px;color:#FFFFFF;width:221">
<A HREF="http://www.northgas.ru" STYLE="font-family:Verdana;font-size:10px;color:#FFFFFF;text-decoration: none;">&copy; Copyright 2002 <%=(lang == CMSApplication.LANG_ENG ? "ZAO &laquo;Northgas&raquo;" :  "ÇÀÎ &laquo;Íîðòãàç&raquo;")%></A>
</DIV>
</TD>
</TR>
</TABLE>
