<META NAME="keywords" CONTENT="northgas, gas company, independent gas company, gas,natural gas, petroleum products, oil-gas-condensate, separation gas">
<META NAME="keywords" CONTENT="sales gas, condensate, liquefied gas, pentan fractions, fuel, gas condensate distillate, processing products, hydrocarbon fuel">
<META NAME="keywords" CONTENT="gas production, processing products, natural gas production, natural gas processing,  energy resource complex, production company">
<META NAME="keywords" CONTENT="north-urengoi field, bolshoi urengoi fields, nadym-pur-tazovsky region, yamalo-nenetsky autonomous area, geological supplies, fields">
<META NAME="keywords" CONTENT="gas plant, gas pipeline transfer, oil and gas industry, gas market, east dome of north-urengoi field, well-boring">
<META NAME="keywords" CONTENT="akhmedov, farkhad akhmedov, farkhat, morgan, david morgan, golubkov, tupitsin, sadekov, kazantseva">
<META NAME="keywords" CONTENT="natural gas, gas-condensate, propane, butane, diesel fuel, northgas, nortgas, nordgas, gas producing eterprise, gas extraction">
<META NAME="keywords" CONTENT="condensate pipeline, west dome of north-urengoi field, deethanization of gas-condensate, stabilization of gas-condensate">
<META NAME="keywords" CONTENT="gas-condensate processing, gas processing, liberalization, intellectual gas field, independent company, private company">
