/*
 * JSP generated by Resin 2.0.5 (built Thu Jan 10 21:43:38 PST 2002)
 */

import javax.servlet.*;
import javax.servlet.jsp.*;
import javax.servlet.http.*;
import java.io.*;
import java.util.*;
import tengry.cms.*;
import tengry.cms.core.*;

public class _dispatch__jsp extends com.caucho.jsp.JavaPage{
  private boolean _caucho_isDead;
  
  public void
  _jspService(javax.servlet.http.HttpServletRequest request,
              javax.servlet.http.HttpServletResponse response)
    throws java.io.IOException, javax.servlet.ServletException
  {
    com.caucho.jsp.QPageContext pageContext = (com.caucho.jsp.QPageContext) com.caucho.jsp.QJspFactory.create().getPageContext(this, request, response, null, true, 8192, true);
    javax.servlet.jsp.JspWriter out = (javax.servlet.jsp.JspWriter) pageContext.getOut();
    javax.servlet.ServletConfig config = getServletConfig();
    javax.servlet.Servlet page = this;
    javax.servlet.http.HttpSession session = pageContext.getSession();
    javax.servlet.ServletContext application = pageContext.getServletContext();
    response.setContentType("text/html; charset=windows-1251");
    request.setCharacterEncoding("CP1251");
    try {
      pageContext.write(_jsp_string0, 0, _jsp_string0.length);
      pageContext.write(_jsp_string0, 0, _jsp_string0.length);
      pageContext.write(_jsp_string0, 0, _jsp_string0.length);
      pageContext.write(_jsp_string0, 0, _jsp_string0.length);
      pageContext.write(_jsp_string0, 0, _jsp_string0.length);
      pageContext.write(_jsp_string0, 0, _jsp_string0.length);
      
//    out.println("ip: " + request.getRemoteAddr());
//    out.println("url = " + request.getHeader("REDIRECT_URL"));
    String urla = request.getHeader("REDIRECT_URL");
    if(urla == null)
        urla = "";
    WebTreeNode node = null;
    StringTokenizer st = new StringTokenizer(urla, "/");
    while(st.hasMoreTokens())
    {
        String name = st.nextToken();
        if(node == null && "pages".equals(name))
            continue;
        if(node == null)
            node = CMSApplication.getApplication().getWebRoot(name);
        else
            node = node.getChild(name);
        if(node == null)
            break;
    }
    String queryString = request.getHeader("REDIRECT_QUERY_STRING");

    if(queryString == null)
        queryString = "";
    if(queryString.length() > 0 && '&' != queryString.charAt(0))
        queryString = "&" + queryString;

    String redirect = "page.jsp?id=" + (node != null ? node.getId() : "" ) + queryString;
//    response.sendRedirect(redirect);
//    pageContext.forward(redirect);

      pageContext.write(_jsp_string0, 0, _jsp_string0.length);
      pageContext.forward(redirect);
      if (true) return;
      pageContext.write(_jsp_string0, 0, _jsp_string0.length);
    } catch (java.lang.Throwable _jsp_e) {
      pageContext.handlePageException(_jsp_e);
    } finally {
      JspFactory.getDefaultFactory().releasePageContext(pageContext);
    }
  }

  private com.caucho.java.LineMap _caucho_line_map;
  private java.util.ArrayList _caucho_depends = new java.util.ArrayList();

  public boolean _caucho_isModified()
  {
    if (_caucho_isDead)
      return true;
    if (com.caucho.util.CauchoSystem.getVersionId() != 2058990002)
      return true;
    for (int i = _caucho_depends.size() - 1; i >= 0; i--) {
      com.caucho.vfs.Depend depend;
      depend = (com.caucho.vfs.Depend) _caucho_depends.get(i);
      if (depend.isModified())
        return true;
    }
    return false;
  }

  public long _caucho_lastModified()
  {
    return 0;
  }

  public com.caucho.java.LineMap _caucho_getLineMap()
  {
    return _caucho_line_map;
  }

  public void destroy()
  {
      _caucho_isDead = true;
      super.destroy();
  }

  public void init(com.caucho.java.LineMap lineMap,
                   com.caucho.vfs.Path appDir)
    throws javax.servlet.ServletException
  {
    com.caucho.vfs.Path resinHome = com.caucho.util.CauchoSystem.getResinHome();
    com.caucho.vfs.MergePath mergePath = new com.caucho.vfs.MergePath();
    mergePath.addMergePath(appDir);
    mergePath.addMergePath(resinHome);
    mergePath.addClassPath(getClass().getClassLoader());
    _caucho_line_map = new com.caucho.java.LineMap("_dispatch__jsp.java", "/dispatch.jsp");
    _caucho_line_map.add(1, 1);
    _caucho_line_map.add(1, 30);
    _caucho_line_map.add(38, 68);
    com.caucho.vfs.Depend depend;
    depend = new com.caucho.vfs.Depend(mergePath.lookup("file:/usr/local/apache/htdocs/ntvmir/dispatch.jsp"), 1043756672000L, 1334L);
    _caucho_depends.add(depend);
  }

  private static byte []_jsp_string0;
  static {
    try {
      _jsp_string0 = "\r\n".getBytes("Cp1251");
    } catch (java.io.UnsupportedEncodingException e) {
      e.printStackTrace();
    }
  }
}
