/*
 * JSP generated by Resin 2.0.5 (built Thu Jan 10 21:43:38 PST 2002)
 */

import javax.servlet.*;
import javax.servlet.jsp.*;
import javax.servlet.http.*;
import java.io.*;
import java.util.*;
import tengry.cms.user.*;
import tengry.cms.press.*;
import tengry.cms.dict.*;
import tengry.cms.tender.*;
import tengry.cms.vote.*;
import tengry.cms.*;
import tengry.cms.db.*;
import tengry.cms.core.*;
import tengry.cms.mailer.*;

public class _page__jsp extends com.caucho.jsp.JavaPage{
  private boolean _caucho_isDead;
  
public String nodePath(WebTreeNode node)
{
    if(node == null)
        return "/pages";
    return nodePath(node.getParent()) + "/" + node.getCode();
}

public String nodePath(String nodeId)
{
    return nodePath(CMSApplication.getApplication().lookup(nodeId));
}

  
	public boolean isPagePrivate(String id) throws DBException
	{
		Group g1 = CMSApplication.getApplication().getGroupByName("default");
		Group g2 = CMSApplication.getApplication().getGroupByName("private");
		if(g1 != null && g2 != null)
		{
			return !Group.isR(g1.getAccessCode(id)) && 
					Group.isR(g2.getAccessCode(id));
		}
		else return false;
	}

  
    private static final String [] TVS_MONTHS = new String[] {
        "Января", "Февраля", "Марта", "Апреля", "Мая", "Июня",
        "Июля", "Авгуса", "Сентября", "Октября", "Ноября", "Декабря"
    };
    private static final String [] TVS_DAYS = new String[] {
        "--", "Воскресенье", "Понедельник", "Вторник", "Среда", "Четверг", "Пятница", "Суббота"
    };
    public String TVS_toString(Date date)
    {
        Calendar cal = Calendar.getInstance();
        cal.setTime(date);
        return  "" + cal.get(Calendar.DATE) + " " + TVS_MONTHS[cal.get(Calendar.MONTH)] + 
                    ", <b>" + TVS_DAYS[cal.get(Calendar.DAY_OF_WEEK)] + "</b>";
    }

  
    
    public void printTree(boolean firstCall, String des, String id, Vector nodes, 
                            String pre, String post, JspWriter out) throws IOException
    {
        if(nodes == null || nodes.size() == 0)
            return;
        pre += "<div class=\"Lnav\">";
        post += "</div>";
        Enumeration enum = nodes.elements();
        while(enum.hasMoreElements())
        {
            WebTreeNode node = (WebTreeNode)enum.nextElement();
            if(firstCall)
                firstCall = false;
            else
                out.println(
                    "<div><img src=\"" + des + "/2lev/lft-ln.gif\" width=\"169\" height=\"1\" alt=\"\" border=\"0\" vspace=\"6\"></div>");

            if(id.equals(node.getId()))
                out.print(pre + "<a class=\"cur\"><b>");
            else
                out.print(pre + "<a href=\"" + nodePath(node) + "\"><b>");
            out.print(CMSApplication.toHTML(node.getName()));
            out.println("</b></a>" + post);
            printTree(false, des, id, node.getVisibleChilds(), pre, post, out);
        }
    
    }

  
  public void
  _jspService(javax.servlet.http.HttpServletRequest request,
              javax.servlet.http.HttpServletResponse response)
    throws java.io.IOException, javax.servlet.ServletException
  {
    com.caucho.jsp.QPageContext pageContext = (com.caucho.jsp.QPageContext) com.caucho.jsp.QJspFactory.create().getPageContext(this, request, response, null, true, 8192, true);
    javax.servlet.jsp.JspWriter out = (javax.servlet.jsp.JspWriter) pageContext.getOut();
    javax.servlet.ServletConfig config = getServletConfig();
    javax.servlet.Servlet page = this;
    javax.servlet.http.HttpSession session = pageContext.getSession();
    javax.servlet.ServletContext application = pageContext.getServletContext();
    response.setContentType("text/html; charset=windows-1251");
    request.setCharacterEncoding("CP1251");
    try {
      pageContext.write(_jsp_string0, 0, _jsp_string0.length);
      pageContext.write(_jsp_string0, 0, _jsp_string0.length);
      
try
{

      pageContext.write(_jsp_string0, 0, _jsp_string0.length);
      pageContext.write(_jsp_string0, 0, _jsp_string0.length);
      pageContext.write(_jsp_string0, 0, _jsp_string0.length);
      pageContext.write(_jsp_string0, 0, _jsp_string0.length);
      pageContext.write(_jsp_string0, 0, _jsp_string0.length);
      pageContext.write(_jsp_string0, 0, _jsp_string0.length);
      pageContext.write(_jsp_string0, 0, _jsp_string0.length);
      pageContext.write(_jsp_string0, 0, _jsp_string0.length);
      pageContext.write(_jsp_string0, 0, _jsp_string0.length);
      pageContext.write(_jsp_string0, 0, _jsp_string0.length);
      pageContext.write(_jsp_string0, 0, _jsp_string0.length);
      pageContext.write(_jsp_string0, 0, _jsp_string0.length);
      pageContext.write(_jsp_string0, 0, _jsp_string0.length);
      
	String      langCode        = null;
	String      pageId          = null;
	String      des             = null;
    User        user            = null;

    langCode = request.getParameter("lang_code");
    if(langCode == null || langCode.trim().length() == 0)
        langCode = CMSApplication.getApplication().getPrimaryLangCode();

	des = CMSApplication.getApplication().getCurrentDesignPath() + "/" + langCode;

	pageId = request.getParameter("id");
	if("".equals(pageId))
		pageId = null;
		
    user = (User)session.getAttribute("ntvmir.user");
    if(user == null)
    {
        String usrid = CMSApplication.getCookie(request, "user.id");
        if(usrid != null && usrid.length() > 0)
        {
            try
            {
                user = User.quickAuthorize(usrid);
            }catch(Exception e){}
        }
    }

	boolean     adminPreview    = false;
	Hashtable   previewInfo     = null;
	adminPreview = (session.getValue("admin.user") != null && "1".equals(request.getParameter("preview")));
	
	previewInfo = (Hashtable)session.getAttribute("admin.previewinfo");
	if(!adminPreview)
		previewInfo = null;

      pageContext.write(_jsp_string1, 0, _jsp_string1.length);
      pageContext.write(_jsp_string0, 0, _jsp_string0.length);
        
	response.setHeader("Pragma","no-cache");
	
	WebTreeNode node            = null;
	String sectionCode = "";	
	
	if(previewInfo == null)
	{
		if(pageId != null)
			node = CMSApplication.getApplication().lookup(pageId);
		if(node == null || (! node.isVisible() && ! adminPreview))
		{

      pageContext.write(_jsp_string0, 0, _jsp_string0.length);
      pageContext.forward("/404.html");
      if (true) return;
      pageContext.write(_jsp_string0, 0, _jsp_string0.length);
      
//			response.sendRedirect("/404.html");
			return;
		}
		if(node.getParent() == null)
		{		
			response.sendRedirect("/index.jsp");
			return;
		}
		
		// When page not found or page is soft link.
		if(node.getLinkId() != null && node.getLinkId().length() > 0)
		{
			WebTreeNode rootWebNode = CMSApplication.getApplication().getWebRoot(langCode);
			if(node.getLinkId().equals(rootWebNode.getId()))
			{
				response.sendRedirect("/index.jsp");
			}
			else
			{
				response.sendRedirect(nodePath(node.getLinkId()));
		    }
		    return;
		}
		
		sectionCode = node.getSectionCode();
	
		// Where page is private
		if(isPagePrivate(node.getId()) && ! adminPreview)
		{
			boolean isOk = false;
			if(user != null)
			{
/*
				Enumeration enum = user.getGroups();
				while(enum.hasMoreElements())
				{
					Group g = (Group)enum.nextElement();
					if(g.isR(node.getId()))
					{
						isOk = true;
						break;
					}
				}
*/
                isOk = true;
			}
			// when user has no permission to view page redirect him to authorization
			if( ! isOk && ! node.getPageType().getCode().equals("auth"))
			{
			    response.sendRedirect("/pages/" + langCode + "/auth?back_page_id=" + node.getId());
			    return;
/********************************************
				Enumeration enum = CMSApplication.getApplication().getNodesByTypeCode(langCode, "auth");
				if(enum.hasMoreElements())
				{
					WebTreeNode authNode = (WebTreeNode)enum.nextElement();
					response.sendRedirect("/page.jsp?id=" + authNode.getId() + "&back_page_id=" + node.getId());
					return;
				}
		    
		        response.sendRedirect("/pages/" + langCode + "/auth?back_page_id=" + node.getId());
				else
				{

<jsp:forward page="/404.html"/>
//					response.sendRedirect("/404.html");
					return;
				}
*******************************************/
			}
		}
	}
	else
	{
		sectionCode = (String)previewInfo.get("section");
	}

	
	String [] parameters = null;
	{
		Vector params = new Vector();
		Enumeration paramNames = request.getParameterNames();
		while(paramNames.hasMoreElements())
		{
			String paramName = (String)paramNames.nextElement();
			String [] vals = request .getParameterValues(paramName);
			for(int i = 0; i < vals.length; i++)
				params.add(paramName + "=" + vals[i]);
		}
		parameters = new String[params.size()];
		for(int i = 0; i < parameters.length; i++)
			parameters[i] = (String)params.elementAt(i);
	}

      pageContext.write(_jsp_string0, 0, _jsp_string0.length);
      pageContext.write(_jsp_string0, 0, _jsp_string0.length);
      pageContext.write(_jsp_string0, 0, _jsp_string0.length);
      

if("forum".equals(sectionCode))
{
    String forumId = request.getParameter("forum_id");
    String themeId = request.getParameter("theme_id");
    if(forumId != null && themeId == null)
    {
        java.text.SimpleDateFormat forumSdf = new java.text.SimpleDateFormat("dd.MM.yyyy-HH.mm.ss");
        String sDate = forumSdf.format(new Date());
        CMSApplication.setCookie(response, "forum.last_view." + forumId, sDate);
    }
}

if("tvschedule".equals(sectionCode))
{
    String showPlaceId = request.getParameter("show_place_id");
    if(showPlaceId != null)
    {
        CMSApplication.setCookie(response, "tvschedule.showplace", showPlaceId);
    }
}
    

      pageContext.write(_jsp_string0, 0, _jsp_string0.length);
      
    String sectionImgDir = sectionCode;
	if("about".equals(sectionImgDir))
	    sectionImgDir = "company";
	else if("tvschedule".equals(sectionImgDir))
	    sectionImgDir = "tvprogram";
	else if("auth".equals(sectionImgDir))
	    sectionImgDir = "authorization";
	else if("map".equals(sectionImgDir))
	    sectionImgDir = "sitemap";
    
	PageType pageType;
	
	if(previewInfo == null)
		pageType = node.getPageType();
	else
		pageType = (PageType)previewInfo.get("pagetype");

	String allParams = "?id=" + (node != null ? node.getId() : "");
	for(int i = 0; i < parameters.length; i++)
		if(!parameters[i].startsWith("page_id="))
			allParams += "&" + CMSApplication.URLEncode(parameters[i]);
    
    // для того, что б инклюдящиеся страницы могли устанавливать куки
    session.setAttribute("page.response", response);

    String title = "";
    if(node != null)
    {
        WebTreeNode tmpNode = node;
        while(tmpNode.getParent() != null)
        {
            title = " :: " + tmpNode.getName() + title;
            tmpNode = tmpNode.getParent();
        }
    }
    String siteUrl = CMSApplication.getApplication().getProperty("www.address", "/");
    String europeUrl = CMSApplication.getApplication().getProperty("www.europe", "/");
    String americaUrl = CMSApplication.getApplication().getProperty("www.america", "/");


      pageContext.write(_jsp_string2, 0, _jsp_string2.length);
      out.print((CMSApplication.getSiteName()));
      out.print((title));
      pageContext.write(_jsp_string3, 0, _jsp_string3.length);
      out.print((des));
      pageContext.write(_jsp_string4, 0, _jsp_string4.length);
      out.print((des));
      pageContext.write(_jsp_string5, 0, _jsp_string5.length);
      out.print((des));
      pageContext.write(_jsp_string6, 0, _jsp_string6.length);
      pageContext.write(_jsp_string7, 0, _jsp_string7.length);
      out.print((des));
      pageContext.write(_jsp_string8, 0, _jsp_string8.length);
      out.print((des));
      pageContext.write(_jsp_string9, 0, _jsp_string9.length);
      out.print((des));
      pageContext.write(_jsp_string10, 0, _jsp_string10.length);
      out.print((des));
      pageContext.write(_jsp_string11, 0, _jsp_string11.length);
      out.print((des));
      pageContext.write(_jsp_string12, 0, _jsp_string12.length);
      pageContext.write(_jsp_string0, 0, _jsp_string0.length);
      pageContext.write(_jsp_string13, 0, _jsp_string13.length);
      out.print((des));
      pageContext.write(_jsp_string14, 0, _jsp_string14.length);
      
	  if(!sectionCode.equals("about")){ 
      
      pageContext.write(_jsp_string15, 0, _jsp_string15.length);
      out.print((langCode));
      pageContext.write(_jsp_string16, 0, _jsp_string16.length);
      out.print((des));
      pageContext.write(_jsp_string17, 0, _jsp_string17.length);
      
	  }else{ 
	  
      pageContext.write(_jsp_string18, 0, _jsp_string18.length);
      out.print((des));
      pageContext.write(_jsp_string19, 0, _jsp_string19.length);
      
	  } 
	 
	  if(!sectionCode.equals("about") && !sectionCode.equals("tvschedule")){ 
	  
      pageContext.write(_jsp_string18, 0, _jsp_string18.length);
      out.print((des));
      pageContext.write(_jsp_string20, 0, _jsp_string20.length);
      
	  }
	
	  if(!sectionCode.equals("tvschedule")){ 
	  
      pageContext.write(_jsp_string15, 0, _jsp_string15.length);
      out.print((langCode));
      pageContext.write(_jsp_string21, 0, _jsp_string21.length);
      out.print((des));
      pageContext.write(_jsp_string22, 0, _jsp_string22.length);
      
	  } else {
	  
      pageContext.write(_jsp_string18, 0, _jsp_string18.length);
      out.print((des));
      pageContext.write(_jsp_string23, 0, _jsp_string23.length);
      
	  }
	
	  if(!sectionCode.equals("tvschedule") && !sectionCode.equals("support")){ 
	  
      pageContext.write(_jsp_string18, 0, _jsp_string18.length);
      out.print((des));
      pageContext.write(_jsp_string20, 0, _jsp_string20.length);
      
	  }
	  
	  if(!sectionCode.equals("support")){ 
	  
      pageContext.write(_jsp_string15, 0, _jsp_string15.length);
      out.print((langCode));
      pageContext.write(_jsp_string24, 0, _jsp_string24.length);
      out.print((des));
      pageContext.write(_jsp_string25, 0, _jsp_string25.length);
      
	  } else { 
	  
      pageContext.write(_jsp_string18, 0, _jsp_string18.length);
      out.print((des));
      pageContext.write(_jsp_string26, 0, _jsp_string26.length);
      
	  }
	  
	  if(!sectionCode.equals("support") && !sectionCode.equals("forum")){
	  
      pageContext.write(_jsp_string18, 0, _jsp_string18.length);
      out.print((des));
      pageContext.write(_jsp_string20, 0, _jsp_string20.length);
      
	  }
	  
	  if(!sectionCode.equals("forum")){ 
	  
      pageContext.write(_jsp_string15, 0, _jsp_string15.length);
      out.print((langCode));
      pageContext.write(_jsp_string27, 0, _jsp_string27.length);
      out.print((des));
      pageContext.write(_jsp_string28, 0, _jsp_string28.length);
      
	  } else {
	  
      pageContext.write(_jsp_string18, 0, _jsp_string18.length);
      out.print((des));
      pageContext.write(_jsp_string29, 0, _jsp_string29.length);
      
	  } 
      pageContext.write(_jsp_string18, 0, _jsp_string18.length);
      out.print((des));
      pageContext.write(_jsp_string30, 0, _jsp_string30.length);
      pageContext.write(_jsp_string31, 0, _jsp_string31.length);
      pageContext.write(_jsp_string32, 0, _jsp_string32.length);
      out.print((des));
      pageContext.write(_jsp_string33, 0, _jsp_string33.length);
      out.print((sectionImgDir));
      pageContext.write(_jsp_string34, 0, _jsp_string34.length);
      out.print((des));
      pageContext.write(_jsp_string35, 0, _jsp_string35.length);
      pageContext.write(_jsp_string31, 0, _jsp_string31.length);
      pageContext.write(_jsp_string36, 0, _jsp_string36.length);
      pageContext.write(_jsp_string37, 0, _jsp_string37.length);
      out.print((des));
      pageContext.write(_jsp_string38, 0, _jsp_string38.length);
      
    if(siteUrl.equals(americaUrl))
    {

      pageContext.write(_jsp_string39, 0, _jsp_string39.length);
      out.print((europeUrl));
      pageContext.write(_jsp_string40, 0, _jsp_string40.length);
      out.print((des));
      pageContext.write(_jsp_string41, 0, _jsp_string41.length);
      out.print((americaUrl));
      pageContext.write(_jsp_string40, 0, _jsp_string40.length);
      out.print((des));
      pageContext.write(_jsp_string42, 0, _jsp_string42.length);
      
    }
    else
    {

      pageContext.write(_jsp_string43, 0, _jsp_string43.length);
      out.print((americaUrl));
      pageContext.write(_jsp_string40, 0, _jsp_string40.length);
      out.print((des));
      pageContext.write(_jsp_string44, 0, _jsp_string44.length);
      out.print((europeUrl));
      pageContext.write(_jsp_string40, 0, _jsp_string40.length);
      out.print((des));
      pageContext.write(_jsp_string45, 0, _jsp_string45.length);
        } 
      pageContext.write(_jsp_string46, 0, _jsp_string46.length);
      out.print((des));
      pageContext.write(_jsp_string47, 0, _jsp_string47.length);
        if(!"search".equals(sectionCode))
    {

      pageContext.write(_jsp_string48, 0, _jsp_string48.length);
      out.print((langCode));
      pageContext.write(_jsp_string49, 0, _jsp_string49.length);
      out.print((langCode));
      pageContext.write(_jsp_string50, 0, _jsp_string50.length);
      out.print((des));
      pageContext.write(_jsp_string51, 0, _jsp_string51.length);
      out.print((des));
      pageContext.write(_jsp_string52, 0, _jsp_string52.length);
      out.print((langCode));
      pageContext.write(_jsp_string53, 0, _jsp_string53.length);
      out.print((des));
      pageContext.write(_jsp_string54, 0, _jsp_string54.length);
      out.print((des));
      pageContext.write(_jsp_string55, 0, _jsp_string55.length);
      
    }
    else
    {

      pageContext.write(_jsp_string56, 0, _jsp_string56.length);
      out.print((des));
      pageContext.write(_jsp_string57, 0, _jsp_string57.length);
      out.print((des));
      pageContext.write(_jsp_string58, 0, _jsp_string58.length);
      out.print((des));
      pageContext.write(_jsp_string59, 0, _jsp_string59.length);
        } 
      pageContext.write(_jsp_string60, 0, _jsp_string60.length);
      out.print((des));
      pageContext.write(_jsp_string61, 0, _jsp_string61.length);
      
    if(adminPreview)
    {

      pageContext.write(_jsp_string62, 0, _jsp_string62.length);
      out.print((des));
      pageContext.write(_jsp_string63, 0, _jsp_string63.length);
      
    }
try
{
    if(sectionCode.equals("forum") || sectionCode.equals("map"))
    {

      pageContext.write(_jsp_string0, 0, _jsp_string0.length);
      
    if(user == null)
    {
        String message = null;
        if("auth".equals(request.getParameter("err")))
            message = "Неверный логин/пароль";

      pageContext.write(_jsp_string64, 0, _jsp_string64.length);
      out.print((langCode));
      pageContext.write(_jsp_string65, 0, _jsp_string65.length);
      out.print((des));
      pageContext.write(_jsp_string66, 0, _jsp_string66.length);
      out.print((des));
      pageContext.write(_jsp_string67, 0, _jsp_string67.length);
      pageContext.write(_jsp_string1, 0, _jsp_string1.length);
        if(message != null)
    {

      pageContext.write(_jsp_string68, 0, _jsp_string68.length);
      out.print((message));
      pageContext.write(_jsp_string69, 0, _jsp_string69.length);
        } 
      pageContext.write(_jsp_string70, 0, _jsp_string70.length);
      out.print((pageId));
      pageContext.write(_jsp_string71, 0, _jsp_string71.length);
      out.print((des));
      pageContext.write(_jsp_string72, 0, _jsp_string72.length);
      out.print((des));
      pageContext.write(_jsp_string73, 0, _jsp_string73.length);
      out.print((langCode));
      pageContext.write(_jsp_string74, 0, _jsp_string74.length);
      out.print((des));
      pageContext.write(_jsp_string75, 0, _jsp_string75.length);
      pageContext.write(_jsp_string76, 0, _jsp_string76.length);
        
    }
    else
    {

      pageContext.write(_jsp_string77, 0, _jsp_string77.length);
      out.print((langCode));
      pageContext.write(_jsp_string65, 0, _jsp_string65.length);
      out.print((des));
      pageContext.write(_jsp_string78, 0, _jsp_string78.length);
      out.print((des));
      pageContext.write(_jsp_string79, 0, _jsp_string79.length);
      out.print((user.getLogin()));
      pageContext.write(_jsp_string80, 0, _jsp_string80.length);
      out.print((langCode));
      pageContext.write(_jsp_string74, 0, _jsp_string74.length);
      out.print((des));
      pageContext.write(_jsp_string81, 0, _jsp_string81.length);
      out.print((pageId));
      pageContext.write(_jsp_string82, 0, _jsp_string82.length);
      out.print((des));
      pageContext.write(_jsp_string83, 0, _jsp_string83.length);
        } 
      pageContext.write(_jsp_string0, 0, _jsp_string0.length);
        }
    else if(sectionCode.equals("tvschedule"))
    {

      pageContext.write(_jsp_string0, 0, _jsp_string0.length);
      pageContext.write(_jsp_string0, 0, _jsp_string0.length);
      
{
    String  sDate   = request.getParameter("date");
    Date    date    = null;
    java.text.SimpleDateFormat sdf = new java.text.SimpleDateFormat("dd.MM.yyyy");

    try{
        date = sdf.parse(sDate);
    } catch(Exception e) {
        date = sdf.parse(sdf.format(new Date()));
    }
    
    Calendar cal = Calendar.getInstance();
    cal.setTime(date);
    int nnn = 1;
    switch(cal.get(Calendar.DAY_OF_WEEK))
    {
        case Calendar.MONDAY:       nnn = 1; break;
        case Calendar.TUESDAY:      nnn = 2; break;
        case Calendar.WEDNESDAY:    nnn = 3; break;
        case Calendar.THURSDAY:     nnn = 4; break;
        case Calendar.FRIDAY:       nnn = 5; break;
        case Calendar.SATURDAY:     nnn = 6; break;
        case Calendar.SUNDAY:       nnn = 7; break;
    }
    cal.add(Calendar.DATE, -nnn);
    
    for(int i = 0; i < 7; i++)
    {
        cal.add(Calendar.DATE, 1);
        if(i > 0)
        {    

      pageContext.write(_jsp_string84, 0, _jsp_string84.length);
      out.print((des));
      pageContext.write(_jsp_string63, 0, _jsp_string63.length);
            }
        if(nnn == i+1)
        {

      pageContext.write(_jsp_string85, 0, _jsp_string85.length);
      out.print((TVS_toString(cal.getTime())));
      pageContext.write(_jsp_string86, 0, _jsp_string86.length);
            }
        else
        {

      pageContext.write(_jsp_string87, 0, _jsp_string87.length);
      out.print((langCode));
      pageContext.write(_jsp_string88, 0, _jsp_string88.length);
      out.print((sdf.format(cal.getTime())));
      pageContext.write(_jsp_string89, 0, _jsp_string89.length);
      out.print((TVS_toString(cal.getTime())));
      pageContext.write(_jsp_string86, 0, _jsp_string86.length);
            }
    }
}

      pageContext.write(_jsp_string0, 0, _jsp_string0.length);
        }
    else if(sectionCode.equals("search"))
    {

      pageContext.write(_jsp_string0, 0, _jsp_string0.length);
      
    String query = request.getParameter("f_query");
    if(query == null)
    	query = "";
    else
        query = query.trim();
    	
    String mode = request.getParameter("f_mode");
    if( ! ("and".equals(mode) || "or".equals(mode) || "full".equals(mode)))
    	mode = "and";
    if(query.length() > 0)
    {

      pageContext.write(_jsp_string90, 0, _jsp_string90.length);
      out.print((CMSApplication.toHTML(query)));
      pageContext.write(_jsp_string91, 0, _jsp_string91.length);
      out.print((des));
      pageContext.write(_jsp_string92, 0, _jsp_string92.length);
      out.print(("and".equals(mode) ? "CHECKED" : ""));
      pageContext.write(_jsp_string93, 0, _jsp_string93.length);
      out.print(("or".equals(mode) ? "CHECKED" : ""));
      pageContext.write(_jsp_string94, 0, _jsp_string94.length);
      out.print(("full".equals(mode) ? "CHECKED" : ""));
      pageContext.write(_jsp_string95, 0, _jsp_string95.length);
        }
    else
    {

      pageContext.write(_jsp_string0, 0, _jsp_string0.length);
      
    if(user == null)
    {
        String message = null;
        if("auth".equals(request.getParameter("err")))
            message = "Неверный логин/пароль";

      pageContext.write(_jsp_string64, 0, _jsp_string64.length);
      out.print((langCode));
      pageContext.write(_jsp_string65, 0, _jsp_string65.length);
      out.print((des));
      pageContext.write(_jsp_string66, 0, _jsp_string66.length);
      out.print((des));
      pageContext.write(_jsp_string67, 0, _jsp_string67.length);
      pageContext.write(_jsp_string1, 0, _jsp_string1.length);
        if(message != null)
    {

      pageContext.write(_jsp_string68, 0, _jsp_string68.length);
      out.print((message));
      pageContext.write(_jsp_string69, 0, _jsp_string69.length);
        } 
      pageContext.write(_jsp_string70, 0, _jsp_string70.length);
      out.print((pageId));
      pageContext.write(_jsp_string71, 0, _jsp_string71.length);
      out.print((des));
      pageContext.write(_jsp_string72, 0, _jsp_string72.length);
      out.print((des));
      pageContext.write(_jsp_string73, 0, _jsp_string73.length);
      out.print((langCode));
      pageContext.write(_jsp_string74, 0, _jsp_string74.length);
      out.print((des));
      pageContext.write(_jsp_string75, 0, _jsp_string75.length);
      pageContext.write(_jsp_string76, 0, _jsp_string76.length);
        
    }
    else
    {

      pageContext.write(_jsp_string77, 0, _jsp_string77.length);
      out.print((langCode));
      pageContext.write(_jsp_string65, 0, _jsp_string65.length);
      out.print((des));
      pageContext.write(_jsp_string78, 0, _jsp_string78.length);
      out.print((des));
      pageContext.write(_jsp_string79, 0, _jsp_string79.length);
      out.print((user.getLogin()));
      pageContext.write(_jsp_string80, 0, _jsp_string80.length);
      out.print((langCode));
      pageContext.write(_jsp_string74, 0, _jsp_string74.length);
      out.print((des));
      pageContext.write(_jsp_string81, 0, _jsp_string81.length);
      out.print((pageId));
      pageContext.write(_jsp_string82, 0, _jsp_string82.length);
      out.print((des));
      pageContext.write(_jsp_string83, 0, _jsp_string83.length);
        } 
      pageContext.write(_jsp_string0, 0, _jsp_string0.length);
        } 
      pageContext.write(_jsp_string0, 0, _jsp_string0.length);
      
    }
    else if(sectionCode.equals("auth") && user != null)
    {

      pageContext.write(_jsp_string0, 0, _jsp_string0.length);
      
    if(user == null)
    {
        String message = null;
        if("auth".equals(request.getParameter("err")))
            message = "Неверный логин/пароль";

      pageContext.write(_jsp_string64, 0, _jsp_string64.length);
      out.print((langCode));
      pageContext.write(_jsp_string65, 0, _jsp_string65.length);
      out.print((des));
      pageContext.write(_jsp_string66, 0, _jsp_string66.length);
      out.print((des));
      pageContext.write(_jsp_string67, 0, _jsp_string67.length);
      pageContext.write(_jsp_string1, 0, _jsp_string1.length);
        if(message != null)
    {

      pageContext.write(_jsp_string68, 0, _jsp_string68.length);
      out.print((message));
      pageContext.write(_jsp_string69, 0, _jsp_string69.length);
        } 
      pageContext.write(_jsp_string70, 0, _jsp_string70.length);
      out.print((pageId));
      pageContext.write(_jsp_string71, 0, _jsp_string71.length);
      out.print((des));
      pageContext.write(_jsp_string72, 0, _jsp_string72.length);
      out.print((des));
      pageContext.write(_jsp_string73, 0, _jsp_string73.length);
      out.print((langCode));
      pageContext.write(_jsp_string74, 0, _jsp_string74.length);
      out.print((des));
      pageContext.write(_jsp_string75, 0, _jsp_string75.length);
      pageContext.write(_jsp_string76, 0, _jsp_string76.length);
        
    }
    else
    {

      pageContext.write(_jsp_string77, 0, _jsp_string77.length);
      out.print((langCode));
      pageContext.write(_jsp_string65, 0, _jsp_string65.length);
      out.print((des));
      pageContext.write(_jsp_string78, 0, _jsp_string78.length);
      out.print((des));
      pageContext.write(_jsp_string79, 0, _jsp_string79.length);
      out.print((user.getLogin()));
      pageContext.write(_jsp_string80, 0, _jsp_string80.length);
      out.print((langCode));
      pageContext.write(_jsp_string74, 0, _jsp_string74.length);
      out.print((des));
      pageContext.write(_jsp_string81, 0, _jsp_string81.length);
      out.print((pageId));
      pageContext.write(_jsp_string82, 0, _jsp_string82.length);
      out.print((des));
      pageContext.write(_jsp_string83, 0, _jsp_string83.length);
        } 
      pageContext.write(_jsp_string0, 0, _jsp_string0.length);
      
    }
    else
    {

      pageContext.write(_jsp_string0, 0, _jsp_string0.length);
      pageContext.write(_jsp_string0, 0, _jsp_string0.length);
      
    if(node != null)
    {
        WebTreeNode ttt = node;
        while(ttt.getParent() != null && ttt.getParent().getParent() != null)
            ttt = ttt.getParent();
        
        printTree(true, des, pageId, ttt.getVisibleChilds(), "", "", out);
    }

      pageContext.write(_jsp_string0, 0, _jsp_string0.length);
        }
}catch(Exception e){}

      pageContext.write(_jsp_string96, 0, _jsp_string96.length);
      pageContext.write(_jsp_string97, 0, _jsp_string97.length);
      out.print((des));
      pageContext.write(_jsp_string98, 0, _jsp_string98.length);
      pageContext.write(_jsp_string0, 0, _jsp_string0.length);
      
boolean votePrinted = false;
try{
if(node != null && node.getVoteId() != null)
{
    String userIP = request.getRemoteAddr();
    Vote vote = new Vote();
    vote.load(node.getVoteId());
    Enumeration enum = VoteItem.getVoteItems(vote.getId());
       
    if(!vote.isVotedIP(userIP))
    {
        String voteType = (vote.getSelectorType() == Vote.SELECTOR_RADIO ? "radio" : "checkbox");

      pageContext.write(_jsp_string99, 0, _jsp_string99.length);
      out.print((pageId));
      pageContext.write(_jsp_string100, 0, _jsp_string100.length);
      out.print((vote.getId()));
      pageContext.write(_jsp_string101, 0, _jsp_string101.length);
      out.print((des));
      pageContext.write(_jsp_string102, 0, _jsp_string102.length);
      out.print((des));
      pageContext.write(_jsp_string103, 0, _jsp_string103.length);
      out.print((des));
      pageContext.write(_jsp_string104, 0, _jsp_string104.length);
      out.print((CMSApplication.toHTML(vote.getQuestion())));
      pageContext.write(_jsp_string105, 0, _jsp_string105.length);
        
        int i = 0;
        while(enum.hasMoreElements())
        {
            VoteItem item = (VoteItem)enum.nextElement();
            i++;

      pageContext.write(_jsp_string106, 0, _jsp_string106.length);
      out.print(( i==1 ? 6 : 0));
      pageContext.write(_jsp_string107, 0, _jsp_string107.length);
      out.print((voteType));
      pageContext.write(_jsp_string108, 0, _jsp_string108.length);
      out.print((item.getId()));
      pageContext.write(_jsp_string109, 0, _jsp_string109.length);
      out.print((i));
      pageContext.write(_jsp_string110, 0, _jsp_string110.length);
      out.print((i));
      pageContext.write(_jsp_string89, 0, _jsp_string89.length);
      out.print((CMSApplication.toHTML(item.getItem())));
      pageContext.write(_jsp_string111, 0, _jsp_string111.length);
            } 
      pageContext.write(_jsp_string112, 0, _jsp_string112.length);
      out.print((des));
      pageContext.write(_jsp_string113, 0, _jsp_string113.length);
      





    }
    else
    {







      pageContext.write(_jsp_string114, 0, _jsp_string114.length);
      out.print((des));
      pageContext.write(_jsp_string102, 0, _jsp_string102.length);
      out.print((des));
      pageContext.write(_jsp_string103, 0, _jsp_string103.length);
      out.print((des));
      pageContext.write(_jsp_string115, 0, _jsp_string115.length);
      out.print((CMSApplication.toHTML(vote.getQuestion())));
      pageContext.write(_jsp_string116, 0, _jsp_string116.length);
      out.print((des));
      pageContext.write(_jsp_string117, 0, _jsp_string117.length);
      out.print((vote.getQuantity()));
      pageContext.write(_jsp_string118, 0, _jsp_string118.length);
      
        java.text.DecimalFormat df = new java.text.DecimalFormat( "##0.0" );

	    while(enum.hasMoreElements())
	    {
	    	VoteItem item = (VoteItem) enum.nextElement();
	    	int l1 = 0;
	    	double pct = 0;
	    	if(vote.getQuantity() > 0 )
	    	{
	    		l1 = (item.getQuantity() * 100) / vote.getQuantity();
	    		pct = ((double)item.getQuantity() * 100.0) / ((double)vote.getQuantity());
	    	}

      pageContext.write(_jsp_string119, 0, _jsp_string119.length);
      out.print((CMSApplication.toHTML(item.getItem())));
      pageContext.write(_jsp_string120, 0, _jsp_string120.length);
      out.print((item.getQuantity()));
      pageContext.write(_jsp_string121, 0, _jsp_string121.length);
      out.print((l1));
      pageContext.write(_jsp_string122, 0, _jsp_string122.length);
      out.print((100-l1));
      pageContext.write(_jsp_string123, 0, _jsp_string123.length);
      out.print((df.format(pct)));
      pageContext.write(_jsp_string124, 0, _jsp_string124.length);
            } 
      pageContext.write(_jsp_string125, 0, _jsp_string125.length);
      
    }
    votePrinted = true;
}
}catch(Exception e){}

      pageContext.write(_jsp_string0, 0, _jsp_string0.length);
      pageContext.write(_jsp_string126, 0, _jsp_string126.length);
      
    if(!votePrinted)
    {

      pageContext.write(_jsp_string18, 0, _jsp_string18.length);
      out.print((des));
      pageContext.write(_jsp_string127, 0, _jsp_string127.length);
       
    }
try{
    if("forum".equals(sectionCode))
    {

      pageContext.write(_jsp_string0, 0, _jsp_string0.length);
      pageContext.write(_jsp_string128, 0, _jsp_string128.length);
      out.print((des));
      pageContext.write(_jsp_string129, 0, _jsp_string129.length);
      out.print((des));
      pageContext.write(_jsp_string130, 0, _jsp_string130.length);
      out.print((des));
      pageContext.write(_jsp_string131, 0, _jsp_string131.length);
        }
    else
    {

      pageContext.write(_jsp_string0, 0, _jsp_string0.length);
      pageContext.write(_jsp_string132, 0, _jsp_string132.length);
        }
}catch(Exception e){}
 
      pageContext.write(_jsp_string133, 0, _jsp_string133.length);
      pageContext.write(_jsp_string31, 0, _jsp_string31.length);
      
    //out.println("<!--" + pageType.getUrlUser() + allParams + "-->");
	pageContext.include(pageType.getUrlUser() + allParams);

      pageContext.write(_jsp_string134, 0, _jsp_string134.length);
      pageContext.write(_jsp_string135, 0, _jsp_string135.length);
      pageContext.write(_jsp_string136, 0, _jsp_string136.length);
      out.print((des));
      pageContext.write(_jsp_string137, 0, _jsp_string137.length);
      out.print((des));
      pageContext.write(_jsp_string138, 0, _jsp_string138.length);
      pageContext.write(_jsp_string31, 0, _jsp_string31.length);
      pageContext.write(_jsp_string139, 0, _jsp_string139.length);
      pageContext.write(_jsp_string140, 0, _jsp_string140.length);
      pageContext.write(_jsp_string141, 0, _jsp_string141.length);
      out.print((des));
      pageContext.write(_jsp_string142, 0, _jsp_string142.length);
      out.print((des));
      pageContext.write(_jsp_string143, 0, _jsp_string143.length);
      out.print((des));
      pageContext.write(_jsp_string144, 0, _jsp_string144.length);
      pageContext.write(_jsp_string145, 0, _jsp_string145.length);
      out.print((des));
      pageContext.write(_jsp_string146, 0, _jsp_string146.length);
      out.print((des));
      pageContext.write(_jsp_string147, 0, _jsp_string147.length);
      pageContext.write(_jsp_string148, 0, _jsp_string148.length);
      out.print((langCode));
      pageContext.write(_jsp_string149, 0, _jsp_string149.length);
      out.print((langCode));
      pageContext.write(_jsp_string150, 0, _jsp_string150.length);
      out.print((langCode));
      pageContext.write(_jsp_string151, 0, _jsp_string151.length);
      out.print((langCode));
      pageContext.write(_jsp_string152, 0, _jsp_string152.length);
      pageContext.write(_jsp_string153, 0, _jsp_string153.length);
      pageContext.write(_jsp_string154, 0, _jsp_string154.length);
      out.print((des));
      pageContext.write(_jsp_string155, 0, _jsp_string155.length);
      out.print((des));
      pageContext.write(_jsp_string156, 0, _jsp_string156.length);
      out.print((des));
      pageContext.write(_jsp_string157, 0, _jsp_string157.length);
      out.print((des));
      pageContext.write(_jsp_string144, 0, _jsp_string144.length);
      pageContext.write(_jsp_string158, 0, _jsp_string158.length);
      out.print((des));
      pageContext.write(_jsp_string146, 0, _jsp_string146.length);
      out.print((des));
      pageContext.write(_jsp_string159, 0, _jsp_string159.length);
      pageContext.write(_jsp_string160, 0, _jsp_string160.length);
      
}catch(Exception e)
{
    e.printStackTrace(System.err);
}

    } catch (java.lang.Throwable _jsp_e) {
      pageContext.handlePageException(_jsp_e);
    } finally {
      JspFactory.getDefaultFactory().releasePageContext(pageContext);
    }
  }

  private com.caucho.java.LineMap _caucho_line_map;
  private java.util.ArrayList _caucho_depends = new java.util.ArrayList();

  public boolean _caucho_isModified()
  {
    if (_caucho_isDead)
      return true;
    if (com.caucho.util.CauchoSystem.getVersionId() != 2058990002)
      return true;
    for (int i = _caucho_depends.size() - 1; i >= 0; i--) {
      com.caucho.vfs.Depend depend;
      depend = (com.caucho.vfs.Depend) _caucho_depends.get(i);
      if (depend.isModified())
        return true;
    }
    return false;
  }

  public long _caucho_lastModified()
  {
    return 0;
  }

  public com.caucho.java.LineMap _caucho_getLineMap()
  {
    return _caucho_line_map;
  }

  public void destroy()
  {
      _caucho_isDead = true;
      super.destroy();
  }

  public void init(com.caucho.java.LineMap lineMap,
                   com.caucho.vfs.Path appDir)
    throws javax.servlet.ServletException
  {
    com.caucho.vfs.Path resinHome = com.caucho.util.CauchoSystem.getResinHome();
    com.caucho.vfs.MergePath mergePath = new com.caucho.vfs.MergePath();
    mergePath.addMergePath(appDir);
    mergePath.addMergePath(resinHome);
    mergePath.addClassPath(getClass().getClassLoader());
    _caucho_line_map = new com.caucho.java.LineMap("_page__jsp.java", "/usr/local/apache/htdocs/ntvmir/page.jsp");
    _caucho_line_map.add("/page.jsp", 1, 1);
    _caucho_line_map.add("/inc/page_init.jsp", 1, 1);
    _caucho_line_map.add("/inc/init_global.jsp", 1, 1);
    _caucho_line_map.add(44, 22);
    _caucho_line_map.add("/inc/page_init.jsp", 118, 35);
    _caucho_line_map.add("/tvschedule/left_up.jsp", 1, 48);
    _caucho_line_map.add("/left_up.jsp", 1, 64);
    _caucho_line_map.add("/page.jsp", 1, 109);
    _caucho_line_map.add(7, 116);
    _caucho_line_map.add("/inc/page_init.jsp", 1, 116);
    _caucho_line_map.add("/inc/init_global.jsp", 1, 123);
    _caucho_line_map.add("/inc/page_init.jsp", 9, 167);
    _caucho_line_map.add(22, 181);
    _caucho_line_map.add(23, 184);
    _caucho_line_map.add(118, 280);
    _caucho_line_map.add("/usr/local/apache/htdocs/ntvmir/page.jsp", 13, 282);
    _caucho_line_map.add("/inc/set_cookies.jsp", 1, 282);
    _caucho_line_map.add("/usr/local/apache/htdocs/ntvmir/page.jsp", 14, 307);
    _caucho_line_map.add(60, 349);
    _caucho_line_map.add(60, 350);
    _caucho_line_map.add(65, 352);
    _caucho_line_map.add(66, 354);
    _caucho_line_map.add(69, 356);
    _caucho_line_map.add(77, 359);
    _caucho_line_map.add(78, 361);
    _caucho_line_map.add(79, 363);
    _caucho_line_map.add(80, 365);
    _caucho_line_map.add(81, 367);
    _caucho_line_map.add(92, 371);
    _caucho_line_map.add(92, 373);
    _caucho_line_map.add(94, 377);
    _caucho_line_map.add(94, 379);
    _caucho_line_map.add(94, 381);
    _caucho_line_map.add(96, 385);
    _caucho_line_map.add(96, 387);
    _caucho_line_map.add(100, 393);
    _caucho_line_map.add(100, 395);
    _caucho_line_map.add(104, 401);
    _caucho_line_map.add(104, 403);
    _caucho_line_map.add(104, 405);
    _caucho_line_map.add(106, 409);
    _caucho_line_map.add(106, 411);
    _caucho_line_map.add(110, 417);
    _caucho_line_map.add(110, 419);
    _caucho_line_map.add(114, 425);
    _caucho_line_map.add(114, 427);
    _caucho_line_map.add(114, 429);
    _caucho_line_map.add(116, 433);
    _caucho_line_map.add(116, 435);
    _caucho_line_map.add(120, 441);
    _caucho_line_map.add(120, 443);
    _caucho_line_map.add(124, 449);
    _caucho_line_map.add(124, 451);
    _caucho_line_map.add(124, 453);
    _caucho_line_map.add(126, 457);
    _caucho_line_map.add(126, 459);
    _caucho_line_map.add(127, 462);
    _caucho_line_map.add(138, 466);
    _caucho_line_map.add(138, 468);
    _caucho_line_map.add(139, 470);
    _caucho_line_map.add(153, 475);
    _caucho_line_map.add(159, 482);
    _caucho_line_map.add(159, 484);
    _caucho_line_map.add(159, 486);
    _caucho_line_map.add(159, 488);
    _caucho_line_map.add(160, 490);
    _caucho_line_map.add(165, 496);
    _caucho_line_map.add(165, 498);
    _caucho_line_map.add(165, 500);
    _caucho_line_map.add(165, 502);
    _caucho_line_map.add(166, 504);
    _caucho_line_map.add(167, 506);
    _caucho_line_map.add(172, 508);
    _caucho_line_map.add(182, 514);
    _caucho_line_map.add(182, 516);
    _caucho_line_map.add(182, 518);
    _caucho_line_map.add(182, 520);
    _caucho_line_map.add(182, 522);
    _caucho_line_map.add(190, 524);
    _caucho_line_map.add(198, 526);
    _caucho_line_map.add(209, 532);
    _caucho_line_map.add(209, 534);
    _caucho_line_map.add(209, 536);
    _caucho_line_map.add(217, 538);
    _caucho_line_map.add(224, 542);
    _caucho_line_map.add(230, 549);
    _caucho_line_map.add(237, 557);
    _caucho_line_map.add("/user/left_up.jsp", 1, 557);
    _caucho_line_map.add(9, 567);
    _caucho_line_map.add(10, 569);
    _caucho_line_map.add(18, 576);
    _caucho_line_map.add(25, 580);
    _caucho_line_map.add(45, 582);
    _caucho_line_map.add(53, 584);
    _caucho_line_map.add(54, 586);
    _caucho_line_map.add(54, 588);
    _caucho_line_map.add(58, 591);
    _caucho_line_map.add(64, 599);
    _caucho_line_map.add(65, 601);
    _caucho_line_map.add(66, 603);
    _caucho_line_map.add(67, 605);
    _caucho_line_map.add(67, 607);
    _caucho_line_map.add(68, 609);
    _caucho_line_map.add(68, 611);
    _caucho_line_map.add("/usr/local/apache/htdocs/ntvmir/page.jsp", 238, 615);
    _caucho_line_map.add(242, 620);
    _caucho_line_map.add("/tvschedule/left_up.jsp", 1, 620);
    _caucho_line_map.add(17, 621);
    _caucho_line_map.add(50, 655);
    _caucho_line_map.add(51, 657);
    _caucho_line_map.add(55, 662);
    _caucho_line_map.add(56, 664);
    _caucho_line_map.add(60, 669);
    _caucho_line_map.add(60, 671);
    _caucho_line_map.add(60, 673);
    _caucho_line_map.add(61, 675);
    _caucho_line_map.add("/usr/local/apache/htdocs/ntvmir/page.jsp", 243, 680);
    _caucho_line_map.add(247, 685);
    _caucho_line_map.add("/search/left_up.jsp", 1, 685);
    _caucho_line_map.add(16, 699);
    _caucho_line_map.add(17, 701);
    _caucho_line_map.add(24, 703);
    _caucho_line_map.add(25, 705);
    _caucho_line_map.add(26, 707);
    _caucho_line_map.add(29, 709);
    _caucho_line_map.add(33, 714);
    _caucho_line_map.add("/user/left_up.jsp", 1, 714);
    _caucho_line_map.add(9, 724);
    _caucho_line_map.add(10, 726);
    _caucho_line_map.add(18, 733);
    _caucho_line_map.add(25, 737);
    _caucho_line_map.add(45, 739);
    _caucho_line_map.add(53, 741);
    _caucho_line_map.add(54, 743);
    _caucho_line_map.add(54, 745);
    _caucho_line_map.add(58, 748);
    _caucho_line_map.add(64, 756);
    _caucho_line_map.add(65, 758);
    _caucho_line_map.add(66, 760);
    _caucho_line_map.add(67, 762);
    _caucho_line_map.add(67, 764);
    _caucho_line_map.add(68, 766);
    _caucho_line_map.add(68, 768);
    _caucho_line_map.add("/search/left_up.jsp", 34, 772);
    _caucho_line_map.add("/usr/local/apache/htdocs/ntvmir/page.jsp", 248, 774);
    _caucho_line_map.add(253, 780);
    _caucho_line_map.add("/user/left_up.jsp", 1, 780);
    _caucho_line_map.add(9, 790);
    _caucho_line_map.add(10, 792);
    _caucho_line_map.add(18, 799);
    _caucho_line_map.add(25, 803);
    _caucho_line_map.add(45, 805);
    _caucho_line_map.add(53, 807);
    _caucho_line_map.add(54, 809);
    _caucho_line_map.add(54, 811);
    _caucho_line_map.add(58, 814);
    _caucho_line_map.add(64, 822);
    _caucho_line_map.add(65, 824);
    _caucho_line_map.add(66, 826);
    _caucho_line_map.add(67, 828);
    _caucho_line_map.add(67, 830);
    _caucho_line_map.add(68, 832);
    _caucho_line_map.add(68, 834);
    _caucho_line_map.add("/usr/local/apache/htdocs/ntvmir/page.jsp", 254, 838);
    _caucho_line_map.add(259, 844);
    _caucho_line_map.add("/left_up.jsp", 1, 844);
    _caucho_line_map.add(31, 845);
    _caucho_line_map.add("/usr/local/apache/htdocs/ntvmir/page.jsp", 260, 856);
    _caucho_line_map.add(271, 861);
    _caucho_line_map.add(281, 863);
    _caucho_line_map.add("/vote/vote.jsp", 2, 864);
    _caucho_line_map.add(18, 881);
    _caucho_line_map.add(20, 885);
    _caucho_line_map.add(21, 887);
    _caucho_line_map.add(32, 899);
    _caucho_line_map.add(33, 901);
    _caucho_line_map.add(33, 903);
    _caucho_line_map.add(33, 905);
    _caucho_line_map.add(33, 907);
    _caucho_line_map.add(33, 909);
    _caucho_line_map.add(36, 913);
    _caucho_line_map.add(40, 915);
    _caucho_line_map.add(57, 934);
    _caucho_line_map.add(58, 936);
    _caucho_line_map.add(63, 938);
    _caucho_line_map.add(70, 942);
    _caucho_line_map.add(77, 944);
    _caucho_line_map.add(91, 959);
    _caucho_line_map.add(91, 961);
    _caucho_line_map.add(96, 963);
    _caucho_line_map.add(96, 965);
    _caucho_line_map.add(100, 967);
    _caucho_line_map.add(103, 969);
    _caucho_line_map.add(110, 971);
    _caucho_line_map.add("/usr/local/apache/htdocs/ntvmir/page.jsp", 283, 979);
    _caucho_line_map.add(286, 984);
    _caucho_line_map.add(286, 986);
    _caucho_line_map.add(292, 993);
    _caucho_line_map.add("/forum/left_down.jsp", 3, 994);
    _caucho_line_map.add(7, 996);
    _caucho_line_map.add(11, 998);
    _caucho_line_map.add("/usr/local/apache/htdocs/ntvmir/page.jsp", 293, 1000);
    _caucho_line_map.add(297, 1005);
    _caucho_line_map.add(310, 1011);
    _caucho_line_map.add(327, 1018);
    _caucho_line_map.add(330, 1020);
    _caucho_line_map.add(346, 1026);
    _caucho_line_map.add(350, 1028);
    _caucho_line_map.add(351, 1030);
    _caucho_line_map.add(356, 1033);
    _caucho_line_map.add(357, 1035);
    _caucho_line_map.add(359, 1038);
    _caucho_line_map.add(359, 1040);
    _caucho_line_map.add(359, 1042);
    _caucho_line_map.add(359, 1044);
    _caucho_line_map.add(364, 1048);
    _caucho_line_map.add(367, 1050);
    _caucho_line_map.add(368, 1052);
    _caucho_line_map.add(369, 1054);
    _caucho_line_map.add(374, 1057);
    _caucho_line_map.add(375, 1059);
    _caucho_line_map.add(382, 1062);
    com.caucho.vfs.Depend depend;
    depend = new com.caucho.vfs.Depend(mergePath.lookup("file:/usr/local/apache/htdocs/ntvmir/inc/page_init.jsp"), 1043927512000L, 3527L);
    _caucho_depends.add(depend);
    depend = new com.caucho.vfs.Depend(mergePath.lookup("file:/usr/local/apache/htdocs/ntvmir/inc/init_global.jsp"), 1043852040000L, 1646L);
    _caucho_depends.add(depend);
    depend = new com.caucho.vfs.Depend(mergePath.lookup("file:/usr/local/apache/htdocs/ntvmir/inc/set_cookies.jsp"), 1042816072000L, 696L);
    _caucho_depends.add(depend);
    depend = new com.caucho.vfs.Depend(mergePath.lookup("file:/usr/local/apache/htdocs/ntvmir/user/left_up.jsp"), 1044277909000L, 3109L);
    _caucho_depends.add(depend);
    depend = new com.caucho.vfs.Depend(mergePath.lookup("file:/usr/local/apache/htdocs/ntvmir/tvschedule/left_up.jsp"), 1043424270000L, 2092L);
    _caucho_depends.add(depend);
    depend = new com.caucho.vfs.Depend(mergePath.lookup("file:/usr/local/apache/htdocs/ntvmir/search/left_up.jsp"), 1043767003000L, 1713L);
    _caucho_depends.add(depend);
    depend = new com.caucho.vfs.Depend(mergePath.lookup("file:/usr/local/apache/htdocs/ntvmir/left_up.jsp"), 1043765911000L, 1426L);
    _caucho_depends.add(depend);
    depend = new com.caucho.vfs.Depend(mergePath.lookup("file:/usr/local/apache/htdocs/ntvmir/vote/vote.jsp"), 1042722118000L, 4407L);
    _caucho_depends.add(depend);
    depend = new com.caucho.vfs.Depend(mergePath.lookup("file:/usr/local/apache/htdocs/ntvmir/forum/left_down.jsp"), 1043926546000L, 646L);
    _caucho_depends.add(depend);
    depend = new com.caucho.vfs.Depend(mergePath.lookup("file:/usr/local/apache/htdocs/ntvmir/left_down.jsp"), 1043925763000L, 8L);
    _caucho_depends.add(depend);
    depend = new com.caucho.vfs.Depend(mergePath.lookup("file:/usr/local/apache/htdocs/ntvmir/page.jsp"), 1045056903000L, 14819L);
    _caucho_depends.add(depend);
  }

  private static byte []_jsp_string149;
  private static byte []_jsp_string86;
  private static byte []_jsp_string124;
  private static byte []_jsp_string13;
  private static byte []_jsp_string28;
  private static byte []_jsp_string100;
  private static byte []_jsp_string7;
  private static byte []_jsp_string107;
  private static byte []_jsp_string23;
  private static byte []_jsp_string126;
  private static byte []_jsp_string65;
  private static byte []_jsp_string120;
  private static byte []_jsp_string16;
  private static byte []_jsp_string109;
  private static byte []_jsp_string33;
  private static byte []_jsp_string152;
  private static byte []_jsp_string87;
  private static byte []_jsp_string54;
  private static byte []_jsp_string64;
  private static byte []_jsp_string2;
  private static byte []_jsp_string105;
  private static byte []_jsp_string74;
  private static byte []_jsp_string94;
  private static byte []_jsp_string57;
  private static byte []_jsp_string20;
  private static byte []_jsp_string68;
  private static byte []_jsp_string143;
  private static byte []_jsp_string41;
  private static byte []_jsp_string79;
  private static byte []_jsp_string55;
  private static byte []_jsp_string89;
  private static byte []_jsp_string77;
  private static byte []_jsp_string128;
  private static byte []_jsp_string40;
  private static byte []_jsp_string96;
  private static byte []_jsp_string97;
  private static byte []_jsp_string59;
  private static byte []_jsp_string32;
  private static byte []_jsp_string50;
  private static byte []_jsp_string106;
  private static byte []_jsp_string61;
  private static byte []_jsp_string99;
  private static byte []_jsp_string5;
  private static byte []_jsp_string160;
  private static byte []_jsp_string155;
  private static byte []_jsp_string91;
  private static byte []_jsp_string3;
  private static byte []_jsp_string136;
  private static byte []_jsp_string58;
  private static byte []_jsp_string85;
  private static byte []_jsp_string84;
  private static byte []_jsp_string132;
  private static byte []_jsp_string123;
  private static byte []_jsp_string10;
  private static byte []_jsp_string147;
  private static byte []_jsp_string15;
  private static byte []_jsp_string104;
  private static byte []_jsp_string82;
  private static byte []_jsp_string139;
  private static byte []_jsp_string83;
  private static byte []_jsp_string35;
  private static byte []_jsp_string121;
  private static byte []_jsp_string52;
  private static byte []_jsp_string78;
  private static byte []_jsp_string154;
  private static byte []_jsp_string11;
  private static byte []_jsp_string103;
  private static byte []_jsp_string111;
  private static byte []_jsp_string114;
  private static byte []_jsp_string38;
  private static byte []_jsp_string92;
  private static byte []_jsp_string122;
  private static byte []_jsp_string36;
  private static byte []_jsp_string48;
  private static byte []_jsp_string119;
  private static byte []_jsp_string156;
  private static byte []_jsp_string137;
  private static byte []_jsp_string142;
  private static byte []_jsp_string118;
  private static byte []_jsp_string135;
  private static byte []_jsp_string21;
  private static byte []_jsp_string112;
  private static byte []_jsp_string29;
  private static byte []_jsp_string62;
  private static byte []_jsp_string42;
  private static byte []_jsp_string115;
  private static byte []_jsp_string140;
  private static byte []_jsp_string150;
  private static byte []_jsp_string45;
  private static byte []_jsp_string73;
  private static byte []_jsp_string18;
  private static byte []_jsp_string25;
  private static byte []_jsp_string31;
  private static byte []_jsp_string144;
  private static byte []_jsp_string117;
  private static byte []_jsp_string47;
  private static byte []_jsp_string95;
  private static byte []_jsp_string127;
  private static byte []_jsp_string24;
  private static byte []_jsp_string26;
  private static byte []_jsp_string14;
  private static byte []_jsp_string108;
  private static byte []_jsp_string159;
  private static byte []_jsp_string80;
  private static byte []_jsp_string75;
  private static byte []_jsp_string67;
  private static byte []_jsp_string30;
  private static byte []_jsp_string69;
  private static byte []_jsp_string6;
  private static byte []_jsp_string131;
  private static byte []_jsp_string56;
  private static byte []_jsp_string9;
  private static byte []_jsp_string4;
  private static byte []_jsp_string98;
  private static byte []_jsp_string153;
  private static byte []_jsp_string102;
  private static byte []_jsp_string63;
  private static byte []_jsp_string44;
  private static byte []_jsp_string51;
  private static byte []_jsp_string101;
  private static byte []_jsp_string138;
  private static byte []_jsp_string157;
  private static byte []_jsp_string17;
  private static byte []_jsp_string129;
  private static byte []_jsp_string116;
  private static byte []_jsp_string72;
  private static byte []_jsp_string12;
  private static byte []_jsp_string71;
  private static byte []_jsp_string148;
  private static byte []_jsp_string90;
  private static byte []_jsp_string141;
  private static byte []_jsp_string0;
  private static byte []_jsp_string76;
  private static byte []_jsp_string93;
  private static byte []_jsp_string34;
  private static byte []_jsp_string151;
  private static byte []_jsp_string70;
  private static byte []_jsp_string46;
  private static byte []_jsp_string60;
  private static byte []_jsp_string110;
  private static byte []_jsp_string133;
  private static byte []_jsp_string37;
  private static byte []_jsp_string53;
  private static byte []_jsp_string27;
  private static byte []_jsp_string134;
  private static byte []_jsp_string39;
  private static byte []_jsp_string66;
  private static byte []_jsp_string81;
  private static byte []_jsp_string130;
  private static byte []_jsp_string125;
  private static byte []_jsp_string113;
  private static byte []_jsp_string19;
  private static byte []_jsp_string22;
  private static byte []_jsp_string49;
  private static byte []_jsp_string145;
  private static byte []_jsp_string158;
  private static byte []_jsp_string43;
  private static byte []_jsp_string8;
  private static byte []_jsp_string146;
  private static byte []_jsp_string88;
  private static byte []_jsp_string1;
  static {
    try {
      _jsp_string149 = "/about\" style=\"color:#ffffff;\">О компании</a> | <a href=\"/pages/".getBytes("Cp1251");
      _jsp_string86 = "</a></div>\r\n".getBytes("Cp1251");
      _jsp_string124 = "%</B></TD>\r\n		<td><div style=\"width:10px;\"><SPACER TYPE=\"block\" HEIGHT=\"1\" WIDTH=\"10\"></div></td>\r\n		</TR>\r\n".getBytes("Cp1251");
      _jsp_string13 = "\r\n<tr>\r\n	<td colspan=\"6\"><a href=\"/\"><img src=\"".getBytes("Cp1251");
      _jsp_string28 = "/n-frm.gif\" alt=\"Форум\" width=\"60\" height=\"23\" alt=\"\" border=\"0\"></a>".getBytes("Cp1251");
      _jsp_string100 = "\">\r\n<input type=\"hidden\" name=\"vote_id\" value=\"".getBytes("Cp1251");
      _jsp_string7 = "\r\n<tr>\r\n	<td colspan=\"7\" height=\"53\" bgcolor=\"#D1E8FA\" valign=\"top\">\r\n		<table cellpadding=\"0\" cellspacing=\"0\" border=\"0\" width=\"100%\">\r\n		<tr>\r\n		<td><img src=\"".getBytes("Cp1251");
      _jsp_string107 = "px 30px 0px 6px;\" class=\"defFont\">\r\n<input type=\"".getBytes("Cp1251");
      _jsp_string23 = "/tvprogram/n-tvprg.gif\" alt=\"Телепрограмма\" width=\"124\" height=\"23\" border=\"0\">".getBytes("Cp1251");
      _jsp_string126 = "\r\n<tr valign=\"top\">\r\n<td bgcolor=\"#80AFE0\" class=\"smallFont\">".getBytes("Cp1251");
      _jsp_string65 = "/forum/list\"><img src=\"".getBytes("Cp1251");
      _jsp_string120 = "  (".getBytes("Cp1251");
      _jsp_string16 = "/about\"><img src=\"".getBytes("Cp1251");
      _jsp_string109 = "\" id=\"vi_".getBytes("Cp1251");
      _jsp_string33 = "/".getBytes("Cp1251");
      _jsp_string152 = "/forum\" style=\"color:#ffffff;\">Форум</a></div>\r\n	".getBytes("Cp1251");
      _jsp_string87 = "\r\n<div class=\"Lnav\"><a href=\"/pages/".getBytes("Cp1251");
      _jsp_string54 = "/sitemap.gif\" width=\"51\" height=\"9\" border=\"0\"></a><br></NOBR></td>\r\n	<td></td>\r\n<td><div style=\"width:5;\"><SPACER TYPE=\"block\" HEIGHT=\"1\" WIDTH=\"5\"></div></td>	\r\n</tr>\r\n<tr><td height=\"6\"></td></tr>\r\n<tr>\r\n<td><div style=\"width:10;\"><SPACER TYPE=\"block\" HEIGHT=\"1\" WIDTH=\"10\"></div></td>\r\n	<td width=\"100%\"><input type=\"text\" name=\"f_query\" style=\"width:100%;font-size:10px;font-family:Tahoma;\" size=\"15\"></td>\r\n	<td><input type=\"Image\" src=\"".getBytes("Cp1251");
      _jsp_string64 = "\r\n<table width=\"169\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\">\r\n<tr><td width=\"10\"><div style=\"width:10;\"><SPACER TYPE=\"block\" HEIGHT=\"1\" WIDTH=\"10\"></div></td><td colspan=\"2\"><a href=\"/pages/".getBytes("Cp1251");
      _jsp_string2 = "\r\n\r\n\r\n<html>\r\n<head>\r\n\r\n<title>".getBytes("Cp1251");
      _jsp_string105 = "</b><br>\r\n</div>\r\n".getBytes("Cp1251");
      _jsp_string74 = "/auth\"><img src=\"".getBytes("Cp1251");
      _jsp_string94 = " id=\"2\"></TD><TD CLASS=\"XsmallFont\" WIDTH=\"25\"> <LABEL for=\"2\">или</LABEL>&nbsp;&nbsp;</TD>\r\n<TD><INPUT TYPE=\"Radio\" NAME=\"f_mode\" VALUE=\"full\" ".getBytes("Cp1251");
      _jsp_string57 = "/srch.gif\" alt=\"Поиск по сайту\" width=\"67\" height=\"9\" border=\"0\"><img src=\"".getBytes("Cp1251");
      _jsp_string20 = "/n-sprtr.gif\" width=\"6\" height=\"23\" border=\"0\">".getBytes("Cp1251");
      _jsp_string68 = "\r\n<tr>\r\n<td></td>\r\n<td class=\"smallFont\" style=\"color: red;\" colspan=\"2\">".getBytes("Cp1251");
      _jsp_string143 = "/btm-1-txt.gif\" width=\"140\" height=\"42\" border=\"0\"></td>\r\n		<td><img src=\"".getBytes("Cp1251");
      _jsp_string41 = "/lng-eur-rus.gif\" width=\"62\" height=\"19\" alt=\"Europe\" border=\"0\"></a><a href=\"".getBytes("Cp1251");
      _jsp_string79 = "/2lev/lft-ln.gif\" width=\"169\" height=\"1\" alt=\"\" border=\"0\" vspace=\"8\"></td></tr>\r\n	<tr><td></td><td class=\"smallFont\">Текущий участник &#151; <b>".getBytes("Cp1251");
      _jsp_string55 = "/btn-arr-blu.gif\" width=\"18\" height=\"18\" border=\"0\" hspace=\"5\"></td>\r\n<td><div style=\"width:5;\"><SPACER TYPE=\"block\" HEIGHT=\"1\" WIDTH=\"5\"></div></td>	\r\n</tr>\r\n<tr><td height=\"9\"></td></tr>\r\n</table>\r\n</td>\r\n</form>\r\n</tr>\r\n".getBytes("Cp1251");
      _jsp_string89 = "\">".getBytes("Cp1251");
      _jsp_string77 = "\r\n<table width=\"169\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\">\r\n	<tr><td width=\"10\"><div style=\"width:10;\"><SPACER TYPE=\"block\" HEIGHT=\"1\" WIDTH=\"10\"></div></td><td width=\"159\"><a href=\"/pages/".getBytes("Cp1251");
      _jsp_string128 = "<table border=\"0\" cellpadding=\"0\" cellspacing=\"8\" bgcolor=\"#80AFE0\" style=\"margin-top:5;\">\r\n<tr>\r\n<td align=\"center\"><img src=\"".getBytes("Cp1251");
      _jsp_string40 = "\"><img src=\"".getBytes("Cp1251");
      _jsp_string96 = "\r\n</td>\r\n</tr>\r\n</table>\r\n\r\n".getBytes("Cp1251");
      _jsp_string97 = "\r\n\r\n<table width=\"100%\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\">\r\n	<tr>\r\n	<td bgcolor=\"#E5E5E5\" align=\"right\"><img src=\"".getBytes("Cp1251");
      _jsp_string59 = "/sitemap.gif\" alt=\"Карта сайта\" width=\"51\" height=\"9\" border=\"0\"></a><br></NOBR></td>\r\n	<td></td>\r\n<td><div style=\"width:5;\"><SPACER TYPE=\"block\" HEIGHT=\"1\" WIDTH=\"5\"></div></td>	\r\n</tr>\r\n<tr><td height=\"8\"></td></tr>\r\n</table>\r\n</td>\r\n</tr>\r\n".getBytes("Cp1251");
      _jsp_string32 = "\r\n<tr>\r\n	<td width=\"21%\" bgcolor=\"#ffffff\"><SPACER TYPE=\"block\" HEIGHT=\"1\" WIDTH=\"1\"></td>\r\n	<td bgcolor=\"#ffffff\" rowspan=\"3\"><SPACER TYPE=\"block\" HEIGHT=\"1\" WIDTH=\"1\"></td>\r\n	<td width=\"38%\" bgcolor=\"#ffffff\"><SPACER TYPE=\"block\" HEIGHT=\"1\" WIDTH=\"1\"></td>\r\n	<td width=\"23%\" bgcolor=\"#ffffff\" align=\"right\"><img src=\"".getBytes("Cp1251");
      _jsp_string50 = "/search\"><img src=\"".getBytes("Cp1251");
      _jsp_string106 = "\r\n<div style=\"margin:".getBytes("Cp1251");
      _jsp_string61 = "/2lev/lft-n-tr.gif\" width=\"10\" height=\"10\" border=\"0\"></td>\r\n</tr>\r\n\r\n<tr valign=\"top\">\r\n<td class=\"smallFont\">\r\n".getBytes("Cp1251");
      _jsp_string99 = "\r\n<form action=\"/vote/xt_vote.jsp\" method=\"post\">\r\n<input type=\"hidden\" name=\"id\" value=\"".getBytes("Cp1251");
      _jsp_string5 = "/bg-grn-ln.gif\">\r\n<table width=\"100%\" cellpadding=\"0\" cellspacing=\"0\" border=\"0\" height=\"100%\">\r\n<tr>\r\n	<td colspan=\"6\" height=\"7\" bgcolor=\"#FF1515\"><img src=\"".getBytes("Cp1251");
      _jsp_string160 = "\r\n</table>\r\n</NOINDEX>\r\n</body>\r\n</html>\r\n".getBytes("Cp1251");
      _jsp_string155 = "/bg-bot.gif\" bgcolor=\"#0D3A89\" width=\"23%\" valign=\"top\">\r\n		<table border=\"0\" cellpadding=\"0\" cellspacing=\"0\" width=\"100%\" background=\"\" style=\"margin-top:8px;\">\r\n		<tr>\r\n		<td bgcolor=\"#477FBB\"><img src=\"".getBytes("Cp1251");
      _jsp_string91 = "\"></td>\r\n<TD><input type=\"Image\" src=\"".getBytes("Cp1251");
      _jsp_string3 = "</title>\r\n<NOINDEX>\r\n<link rel=\"STYLESHEET\" type=\"text/css\" href=\"/inc/css.css\">\r\n</head>\r\n\r\n<SCRIPT LANGUAGE=\"JavaScript\">(document.layers)?document.write('<style>.SELnn{font-size:11px;}</style>'):document.write('<style>body {background:#1DAF38 url(".getBytes("Cp1251");
      _jsp_string136 = "\r\n<tr>\r\n<td width=\"21%\" align=\"right\" bgcolor=\"#ffffff\"><div style=\"position:relative;top:-10;left:0;\"><img src=\"".getBytes("Cp1251");
      _jsp_string58 = "/dvder.gif\" width=\"9\" height=\"9\" border=\"0\"><a href=\"\"><img src=\"".getBytes("Cp1251");
      _jsp_string85 = "\r\n<div class=\"Lnav\"><a class=\"cur\">".getBytes("Cp1251");
      _jsp_string84 = "\r\n<div><img src=\"".getBytes("Cp1251");
      _jsp_string132 = "<!-- -->\r\n".getBytes("Cp1251");
      _jsp_string123 = "%\"><SPACER TYPE=\"block\" HEIGHT=\"1\" WIDTH=\"1\"></TD></TR></TABLE>\r\n				</TD></TR></TABLE></TD></TR></TABLE><DIV STYLE=\"margin:1px 0px 0px 0px;\"><SPACER TYPE=\"block\" HEIGHT=\"1\" WIDTH=\"1\"></DIV>\r\n			<!----//графический индикатор процента голосов  ----->\r\n		</TD>\r\n		<TD align=\"right\" class=\"bluTtl\"><B CLASS=\"XsmallFont\">".getBytes("Cp1251");
      _jsp_string10 = "/t-2.gif\" width=\"271\" height=\"52\" alt=\"\" border=\"0\"></td>\r\n		<td bgcolor=\"#2E516F\"><img src=\"".getBytes("Cp1251");
      _jsp_string147 = "/bg-bot.gif\" bgcolor=\"#0D3A89\" width=\"38%\" align=\"center\">\r\n	".getBytes("Cp1251");
      _jsp_string15 = "<a href=\"/pages/".getBytes("Cp1251");
      _jsp_string104 = "/ttl-vote.gif\" width=\"37\" height=\"7\" border=\"0\" hspace=\"10\" vspace=\"11\"><br>\r\n<div style=\"margin:0px 30px 0px 10px;\" class=\"defFont\">\r\n<b class=\"bluTtl\">".getBytes("Cp1251");
      _jsp_string82 = "&action=out\"><img src=\"".getBytes("Cp1251");
      _jsp_string139 = "\r\n<tr>\r\n<td height=\"5\" colspan=\"6\"><SPACER TYPE=\"block\" HEIGHT=\"5\" WIDTH=\"1\"></td>\r\n</tr>\r\n".getBytes("Cp1251");
      _jsp_string83 = "/forum/btn-out.gif\" height=\"18\" alt=\"Выход\" border=\"0\"></a></td></tr>\r\n</table>\r\n".getBytes("Cp1251");
      _jsp_string35 = "/tp-r.gif\" width=\"10\" height=\"9\" border=\"0\"></td>\r\n	<td width=\"18%\"><SPACER TYPE=\"block\" HEIGHT=\"1\" WIDTH=\"1\"></td>\r\n</tr>\r\n".getBytes("Cp1251");
      _jsp_string121 = ")</SPAN></TD></TR>\r\n		<TR VALIGN=\"bottom\">\r\n		<TD height=\"14\" WIDTH=\"90%\">\r\n		<!---- графический индикатор процента голосов   ----->\r\n				<TABLE BORDER=\"0\" CELLPADDING=\"1\" CELLSPACING=\"0\" BGCOLOR=\"#CCCCCC\" WIDTH=\"95%\" background=\"\"><TR><TD><TABLE BORDER=\"0\" CELLPADDING=\"1\" CELLSPACING=\"0\" BGCOLOR=\"#4F76A9\" WIDTH=\"100%\" background=\"\"><TR><TD>\r\n				<!--меняем проценты ячеек таблицы что бы в сумме было 100%--><TABLE BORDER=\"0\" CELLPADDING=\"0\" CELLSPACING=\"0\" WIDTH=\"100%\" background=\"\"><TR><TD WIDTH=\"".getBytes("Cp1251");
      _jsp_string52 = "/dvder.gif\" width=\"9\" height=\"9\" border=\"0\"><a href=\"/pages/".getBytes("Cp1251");
      _jsp_string78 = "/forum/btn-usr-list.gif\" width=\"120\" height=\"18\" alt=\"Список пользователей\" border=\"0\"></a></td></tr>\r\n	<tr><td colspan=\"2\"><img src=\"".getBytes("Cp1251");
      _jsp_string154 = "<div style=\"width:372;\"><SPACER TYPE=\"block\" HEIGHT=\"1\" WIDTH=\"372\"></div>\r\n	</td>\r\n\r\n	<td background=\"".getBytes("Cp1251");
      _jsp_string11 = "/t-3.gif\" width=\"90\" height=\"52\" alt=\"\" border=\"0\"></td>\r\n		<td width=\"100%\"><img src=\"".getBytes("Cp1251");
      _jsp_string103 = "/lft-tn-tr.gif\" width=\"10\" height=\"10\" border=\"0\" align=\"right\" hspace=\"0\">\r\n<img src=\"".getBytes("Cp1251");
      _jsp_string111 = "</LABEL>\r\n</div>\r\n".getBytes("Cp1251");
      _jsp_string114 = "\r\n<tr valign=\"top\">\r\n<td height=\"180\" bgcolor=\"#80AFE0\" style=\"background-image:url(".getBytes("Cp1251");
      _jsp_string38 = "/lng-bg.gif\">\r\n<tr align=\"right\">\r\n".getBytes("Cp1251");
      _jsp_string92 = "/btn-arr-blu.gif\" width=\"18\" height=\"18\" border=\"0\" hspace=\"5\"></TD>\r\n<td><div style=\"width:1;\"><SPACER TYPE=\"block\" HEIGHT=\"1\" WIDTH=\"1\"></div></td>\r\n</tr>\r\n</table>\r\n<table BORDER=\"0\" CELLPADDING=\"0\" CELLSPACING=\"2\" BACKGROUND=\"\" STYLE=\"margin-top:2px;\" width=\"100%\">\r\n<TR>\r\n<td><div style=\"width:2;\"><SPACER TYPE=\"block\" HEIGHT=\"1\" WIDTH=\"2\"></div></td>\r\n<TD><INPUT TYPE=\"Radio\" NAME=\"f_mode\" VALUE=\"and\" ".getBytes("Cp1251");
      _jsp_string122 = "%\" HEIGHT=\"4\" BGCOLOR=\"#8cda9c\"><SPACER TYPE=\"block\" HEIGHT=\"1\" WIDTH=\"1\"></TD><TD WIDTH=\"".getBytes("Cp1251");
      _jsp_string36 = "\r\n<tr valign=\"top\">\r\n<td bgcolor=\"#80AFE0\" width=\"21%\">\r\n\r\n".getBytes("Cp1251");
      _jsp_string48 = "\r\n<tr bgcolor=\"#ffffff\">\r\n<form action=\"/pages/".getBytes("Cp1251");
      _jsp_string119 = "\r\n		<TR VALIGN=\"bottom\"><TD COLSPAN=\"3\" WIDTH=\"100%\" height=\"20\"><SPAN CLASS=\"XsmallFont\" STYLE=\"color:#FFFFFF\">".getBytes("Cp1251");
      _jsp_string156 = "/btm-2-l.gif\" width=\"7\" height=\"42\" border=\"0\"></td>\r\n		<td bgcolor=\"#477FBB\" width=\"100%\" align=\"center\"><img src=\"".getBytes("Cp1251");
      _jsp_string137 = "/lft-tn-br.gif\" width=\"10\" height=\"10\" border=\"0\"></div></td>\r\n<td width=\"38%\" bgcolor=\"#ffffff\"><SPACER TYPE=\"block\" HEIGHT=\"1\" WIDTH=\"1\"></td>\r\n<td width=\"23%\" bgcolor=\"#ffffff\"><SPACER TYPE=\"block\" HEIGHT=\"1\" WIDTH=\"1\"></td>\r\n<td align=\"right\"><img src=\"".getBytes("Cp1251");
      _jsp_string142 = "/bg-bot.gif\" bgcolor=\"#0D3A89\" width=\"21%\" valign=\"top\">\r\n		<table border=\"0\" cellpadding=\"0\" cellspacing=\"0\" width=\"100%\" background=\"\" style=\"margin-top:8px;\" bgcolor=\"#477FBB\">\r\n		<tr>\r\n		<td><div style=\"width:13;\"><SPACER TYPE=\"block\" HEIGHT=\"1\" WIDTH=\"13\"></div></td>\r\n		<td width=\"100%\"><img src=\"".getBytes("Cp1251");
      _jsp_string118 = "</B> человек</SPAN>\r\n</div>\r\n	\r\n\r\n			\r\n<div style=\"width:100%; padding:12px 0px 0px 10px;\">\r\n		<TABLE BORDER=\"0\" CELLPADDING=\"0\" CELLSPACING=\"0\" background=\"\">\r\n".getBytes("Cp1251");
      _jsp_string135 = "\r\n\r\n\r\n\r\n\r\n\r\n".getBytes("Cp1251");
      _jsp_string21 = "/tvschedule\"><img src=\"".getBytes("Cp1251");
      _jsp_string112 = "\r\n<div  style=\"text-align:right;\"><input type=\"Image\" src=\"".getBytes("Cp1251");
      _jsp_string29 = "/forum/n-frm.gif\" alt=\"Форум\" width=\"72\" height=\"23\" alt=\"\" border=\"0\">".getBytes("Cp1251");
      _jsp_string62 = "\r\n<div class=\"Lnav\"><a href=\"javascript:window.close();\"><b>Закрыть окно.</b></a></div>\r\n<div><img src=\"".getBytes("Cp1251");
      _jsp_string42 = "/lng-usa-cur-rus.gif\" width=\"37\" height=\"19\" alt=\"USA\" border=\"0\" hspace=\"8\"></a></td>\r\n".getBytes("Cp1251");
      _jsp_string115 = "/ttl-vote.gif\" width=\"37\" height=\"7\" border=\"0\" hspace=\"10\" vspace=\"11\"><br>\r\n\r\n<!---- ОПРОС РЕЗУЛЬТАТЫ----->\r\n\r\n<div style=\"margin:0px 30px 10px 10px;\" class=\"defFont\">\r\n<b class=\"bluTtl\">".getBytes("Cp1251");
      _jsp_string140 = "\r\n\r\n\r\n\r\n".getBytes("Cp1251");
      _jsp_string150 = "/tvschedule\" style=\"color:#ffffff;\">Телепрограмма</a> | <a href=\"/pages/".getBytes("Cp1251");
      _jsp_string45 = "/lng-eur-cur-rus.gif\" width=\"62\" height=\"19\" alt=\"Europe\" border=\"0\" hspace=\"8\"></a></td>\r\n".getBytes("Cp1251");
      _jsp_string73 = "/2lev/lft-ln.gif\" width=\"169\" height=\"1\" alt=\"\" border=\"0\" vspace=\"8\"></td></tr>\r\n<tr><td></td><td colspan=\"2\"><a href=\"/pages/".getBytes("Cp1251");
      _jsp_string18 = "<img src=\"".getBytes("Cp1251");
      _jsp_string25 = "/n-sprt.gif\" alt=\"Служба поддержки\" width=\"138\" height=\"23\" border=\"0\"></a>".getBytes("Cp1251");
      _jsp_string31 = "\r\n\r\n\r\n".getBytes("Cp1251");
      _jsp_string144 = "/btm-1-r.gif\" width=\"7\" height=\"42\" border=\"0\"></td>\r\n		</tr>\r\n		</table>\r\n	".getBytes("Cp1251");
      _jsp_string117 = "/t-poll-rslt.gif\" width=\"71\" height=\"24\" alt=\"\" border=\"0\" hspace=\"10\"><br>\r\n\r\n\r\n\r\n<div style=\"margin:0px 10px 0px 10px;\" class=\"smallFont\">\r\n<SPAN class=\"bluTtl\">Проголосовало - <B>".getBytes("Cp1251");
      _jsp_string47 = "/lng-r.gif\" width=\"8\" height=\"19\" alt=\"\" border=\"0\"></td>\r\n</tr>\r\n</table>\r\n</td>\r\n</tr>\r\n".getBytes("Cp1251");
      _jsp_string95 = " id=\"3\"></TD><TD CLASS=\"XsmallFont\" nowrap> <LABEL for=\"3\">фраза целиком</LABEL>&nbsp;&nbsp;</TD>\r\n</form></TR>\r\n</TABLE>\r\n".getBytes("Cp1251");
      _jsp_string127 = "/2lev/lft-b-tr.gif\" width=\"10\" height=\"10\" border=\"0\" align=\"right\" hspace=\"0\">".getBytes("Cp1251");
      _jsp_string24 = "/support\"><img src=\"".getBytes("Cp1251");
      _jsp_string26 = "/support/n-sprt.gif\" alt=\"Служба поддержки\" width=\"150\" height=\"23\" border=\"0\">".getBytes("Cp1251");
      _jsp_string14 = "/logo-mir.gif\" width=\"96\" height=\"23\" border=\"0\"></a>".getBytes("Cp1251");
      _jsp_string108 = "\" name=\"vote_item_id\" value=\"".getBytes("Cp1251");
      _jsp_string159 = "/bg-bot.gif\" bgcolor=\"#0D3A89\" width=\"18%\"><div style=\"width:1;\"><SPACER TYPE=\"block\" HEIGHT=\"1\" WIDTH=\"1\"></div></td>\r\n</tr>\r\n".getBytes("Cp1251");
      _jsp_string80 = "</b></td></tr>\r\n	<tr><td></td><td><a href=\"/pages/".getBytes("Cp1251");
      _jsp_string75 = "/forum/btn-reg.gif\" width=\"108\" height=\"18\" alt=\"Зарегестрироваться\" border=\"0\"></a></td></tr>\r\n</form>\r\n".getBytes("Cp1251");
      _jsp_string67 = "/2lev/lft-ln.gif\" width=\"169\" height=\"1\" alt=\"\" border=\"0\" vspace=\"8\"></td></tr>\r\n".getBytes("Cp1251");
      _jsp_string30 = "/n-r.gif\" width=\"250\" height=\"23\" border=\"0\"></td>\r\n</tr>\r\n\r\n".getBytes("Cp1251");
      _jsp_string69 = "<br>&nbsp;</td>\r\n</tr>\r\n".getBytes("Cp1251");
      _jsp_string6 = "/t-red.jpg\" width=\"770\" height=\"7\" alt=\"\" border=\"0\"></td>\r\n</tr>\r\n\r\n".getBytes("Cp1251");
      _jsp_string131 = "/forum/ico-frm-lock.gif\" width=\"13\" height=\"15\" alt=\"\" border=\"0\"></td>\r\n<td bgcolor=\"#80AFE0\" class=\"smallFont\">Тема закрыта</td>\r\n</tr>\r\n</table>\r\n\r\n".getBytes("Cp1251");
      _jsp_string56 = "\r\n<tr bgcolor=\"#ffffff\">\r\n<td>\r\n<table border=\"0\" cellpadding=\"0\" cellspacing=\"0\">\r\n<tr><td height=\"11\"></td></tr>\r\n<tr valign=\"bottom\">\r\n<td><div style=\"width:10;\"><SPACER TYPE=\"block\" HEIGHT=\"1\" WIDTH=\"10\"></div></td>\r\n	<td width=\"67\"><NOBR><img src=\"".getBytes("Cp1251");
      _jsp_string9 = "/t-1.gif\" width=\"158\" height=\"52\" alt=\"\" border=\"0\"></td>\r\n		<td bgcolor=\"#0F3E8C\"><img src=\"".getBytes("Cp1251");
      _jsp_string4 = "/bg-grn-ln.gif) repeat-y;} SELECT{font-family: Geneva CY, Verdana, Tahoma, Arial, sans-serif;font-size: 65%;}</style>');</SCRIPT>\r\n<body topmargin=\"0\" leftmargin=\"0\" marginheight=\"0\" marginwidth=\"0\" bgcolor=\"#80AFE0\" background=\"".getBytes("Cp1251");
      _jsp_string98 = "/2lev/lft-n-br.gif\" width=\"10\" height=\"10\" border=\"0\"></td>\r\n	</tr>\r\n	<tr>\r\n	<td height=\"10\" bgcolor=\"#ffffff\"><SPACER TYPE=\"block\" HEIGHT=\"1\" WIDTH=\"1\"></td>\r\n	</tr>	\r\n</table>\r\n\r\n\r\n\r\n<table width=\"100%\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" bgcolor=\"#80AFE0\">\r\n".getBytes("Cp1251");
      _jsp_string153 = "	\r\n	".getBytes("Cp1251");
      _jsp_string102 = "/lft-vt-bg.gif);background-repeat:repeat-x;\"><img src=\"".getBytes("Cp1251");
      _jsp_string63 = "/2lev/lft-ln.gif\" width=\"169\" height=\"1\" alt=\"\" border=\"0\" vspace=\"6\"></div>\r\n".getBytes("Cp1251");
      _jsp_string44 = "/lng-usa-rus.gif\" width=\"37\" height=\"19\" alt=\"USA\" border=\"0\"></a><a href=\"".getBytes("Cp1251");
      _jsp_string51 = "/srch.gif\" width=\"67\" height=\"9\" border=\"0\"></a><img src=\"".getBytes("Cp1251");
      _jsp_string101 = "\">\r\n<tr valign=\"top\">\r\n<td bgcolor=\"#80AFE0\" style=\"background-image:url(".getBytes("Cp1251");
      _jsp_string138 = "/bt-r.gif\" width=\"10\" height=\"10\" border=\"0\"></td>\r\n<td width=\"18%\"><SPACER TYPE=\"block\" HEIGHT=\"1\" WIDTH=\"1\"></td>\r\n</tr>\r\n".getBytes("Cp1251");
      _jsp_string157 = "/btm-2-txt.gif\" width=\"180\" height=\"42\" border=\"0\"></td>\r\n		<td bgcolor=\"#477FBB\"><img src=\"".getBytes("Cp1251");
      _jsp_string17 = "/n-abt.gif\" alt=\"О компании\" width=\"92\" height=\"23\" border=\"0\"></a>".getBytes("Cp1251");
      _jsp_string129 = "/forum/ico-new-ms.gif\" width=\"9\" height=\"7\" alt=\"\" border=\"0\"></td>\r\n<td bgcolor=\"#80AFE0\" class=\"smallFont\">Новые сообщения</td>\r\n</tr>\r\n<tr>\r\n<td align=\"center\"><img src=\"".getBytes("Cp1251");
      _jsp_string116 = "</b><br>\r\n</div>\r\n<img src=\"".getBytes("Cp1251");
      _jsp_string72 = "/forum/btn-entr.gif\" width=\"43\" height=\"18\" border=\"0\" hspace=\"10\" alt=\"Вход\"></td>\r\n</tr>\r\n\r\n<tr>\r\n<td></td>\r\n<td class=\"smallFont\" colspan=\"2\"><input type=\"checkbox\" name=\"quick_auth\" value=\"1\" id=\"quick_auth_id\"> &#151; <label for=\"quick_auth_id\">запомнить пароль</label>&nbsp;</td>\r\n</tr>\r\n\r\n<tr><td colspan=\"3\"><img src=\"".getBytes("Cp1251");
      _jsp_string12 = "/t-4.jpg\" width=\"165\" height=\"52\" alt=\"\" border=\"0\"></td>\r\n		</tr>\r\n		<tr>\r\n		<td height=\"1\" bgcolor=\"#ffffff\" colspan=\"5\"><SPACER TYPE=\"block\" HEIGHT=\"1\" WIDTH=\"1\"></td>\r\n		</tr>\r\n		</table>\r\n	</td>\r\n</tr>\r\n".getBytes("Cp1251");
      _jsp_string71 = "\">\r\n<input type=\"hidden\" name=\"action\" value=\"login\">\r\n<td></td>\r\n<td class=\"smallFont\" colspan=\"2\">Имя:&nbsp;</td>\r\n</tr>\r\n\r\n<tr>\r\n<td></td>\r\n<td valign=\"top\" height=\"20\"><input type=\"text\" name=\"login\" style=\"width:90;font-size:10px;font-family:Tahoma;\" size=\"8\"></td>\r\n<td></td>\r\n</tr>\r\n\r\n<tr>\r\n<td></td>\r\n<td class=\"smallFont\" colspan=\"2\">Пароль:&nbsp;</td>\r\n</tr>\r\n\r\n<tr>\r\n<td></td>\r\n<td width=\"80\"><input type=\"password\" style=\"width:90;font-size:10px;font-family:Tahoma;\" size=\"8\" name=\"password\"></td>\r\n<td width=\"79\"><input type=\"Image\"src=\"".getBytes("Cp1251");
      _jsp_string148 = "	\r\n	<div style=\"color:#ffffff;font-size:10px;font-family: Tahoma, Verdana, Arial, sans-serif;\"><a href=\"/\" style=\"color:#ffffff;\">Главная</a> | <a href=\"/pages/".getBytes("Cp1251");
      _jsp_string90 = "\r\n<TABLE BORDER=\"0\" CELLPADDING=\"0\" CELLSPACING=\"2\" BACKGROUND=\"\" STYLE=\"margin-top:8px;\" width=\"100%\">\r\n<tr><form action=\"\"><td><div style=\"width:6;\"><SPACER TYPE=\"block\" HEIGHT=\"1\" WIDTH=\"6\"></div></td>\r\n<td width=\"100%\"><INPUT TYPE=\"Text\" NAME=\"f_query\" SIZE=\"15\" STYLE=\"width:139;\" VALUE=\"".getBytes("Cp1251");
      _jsp_string141 = "\r\n<tr>\r\n	<td height=\"60\" background=\"".getBytes("Cp1251");
      _jsp_string0 = "\r\n".getBytes("Cp1251");
      _jsp_string76 = "\r\n</table>\r\n".getBytes("Cp1251");
      _jsp_string93 = " id=\"1\"></TD><TD CLASS=\"XsmallFont\" WIDTH=\"15\"> <LABEL for=\"1\">и</LABEL>&nbsp;&nbsp;</TD>\r\n<TD><INPUT TYPE=\"Radio\" NAME=\"f_mode\" VALUE=\"or\" ".getBytes("Cp1251");
      _jsp_string34 = "/top-ttl.gif\" height=\"9\" alt=\"\" border=\"0\"></td>\r\n	<td align=\"right\"><img src=\"".getBytes("Cp1251");
      _jsp_string151 = "/support\" style=\"color:#ffffff;\">Служба поддержки</a> | <a href=\"/pages/".getBytes("Cp1251");
      _jsp_string70 = "\r\n\r\n\r\n<tr>\r\n<form action=\"/user/xt_auth.jsp\" method=\"post\">\r\n<input type=\"hidden\" name=\"id\" value=\"".getBytes("Cp1251");
      _jsp_string46 = "\r\n	<td><img src=\"".getBytes("Cp1251");
      _jsp_string60 = "\r\n<tr>\r\n<td align=\"right\"><img src=\"".getBytes("Cp1251");
      _jsp_string110 = "\" NAME=\"qwestion\"><LABEL for=\"vi_".getBytes("Cp1251");
      _jsp_string133 = "\r\n</td>\r\n</tr>\r\n</table>\r\n\r\n</td>\r\n<td width=\"61%\" colspan=\"2\" bgcolor=\"#ffffff\" height=\"100%\">\r\n".getBytes("Cp1251");
      _jsp_string37 = "\r\n<table width=\"100%\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" bgcolor=\"#E5E5E5\">\r\n<tr bgcolor=\"#ffffff\">\r\n<td>\r\n<table width=\"100%\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" background=\"".getBytes("Cp1251");
      _jsp_string53 = "/map\"><img src=\"".getBytes("Cp1251");
      _jsp_string27 = "/forum\"><img src=\"".getBytes("Cp1251");
      _jsp_string134 = "\r\n\r\n</td>\r\n<td bgcolor=\"#ffffff\"><SPACER TYPE=\"block\" HEIGHT=\"1\" WIDTH=\"1\"></td>\r\n<td width=\"18%\"><SPACER TYPE=\"block\" HEIGHT=\"1\" WIDTH=\"1\"></td>\r\n</tr>\r\n".getBytes("Cp1251");
      _jsp_string39 = "\r\n    <td width=\"100%\"><a href=\"".getBytes("Cp1251");
      _jsp_string66 = "/forum/btn-usr-list.gif\" width=\"120\" height=\"18\" alt=\"Список пользователей\" border=\"0\"></a></td></tr>\r\n<tr><td colspan=\"3\"><img src=\"".getBytes("Cp1251");
      _jsp_string81 = "/forum/btn-profile.gif\" height=\"18\" alt=\"Личные данные\" border=\"0\" vspace=\"10\"></a></td></tr>\r\n	<tr><td></td><td><a href=\"/user/xt_auth.jsp?id=".getBytes("Cp1251");
      _jsp_string130 = "/forum/ico-frm-hot.gif\" width=\"13\" height=\"15\" alt=\"\" border=\"0\"></td>\r\n<td bgcolor=\"#80AFE0\" class=\"smallFont\">Горячая тема</td>\r\n</tr>\r\n<tr>\r\n<td align=\"center\"><img src=\"".getBytes("Cp1251");
      _jsp_string125 = "\r\n		</TABLE>\r\n</div>\r\n<BR>\r\n		<!----//ОПРОС РЕЗУЛЬТАТЫ----->\r\n</td>\r\n</tr>\r\n".getBytes("Cp1251");
      _jsp_string113 = "/btn-vote.gif\" width=\"78\" height=\"18\" border=\"0\" hspace=\"10\"></div>\r\n</form>\r\n</td>\r\n</tr>\r\n".getBytes("Cp1251");
      _jsp_string19 = "/company/n-abt.gif\" alt=\"О компании\" width=\"98\" height=\"23\" border=\"0\">".getBytes("Cp1251");
      _jsp_string22 = "/n-tvprg.gif\" alt=\"Телепрограмма\" width=\"112\" height=\"23\" border=\"0\"></a>".getBytes("Cp1251");
      _jsp_string49 = "/search\">\r\n<td>\r\n<table width=\"100%\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\">\r\n<tr><td height=\"12\"></td></tr>\r\n<tr valign=\"bottom\">\r\n<td><div style=\"width:10;\"><SPACER TYPE=\"block\" HEIGHT=\"1\" WIDTH=\"10\"></div></td>\r\n	<td width=\"100%\"><NOBR><a href=\"/pages/".getBytes("Cp1251");
      _jsp_string145 = "<div style=\"width:184;\"><SPACER TYPE=\"block\" HEIGHT=\"1\" WIDTH=\"184\"></div>\r\n	</td>\r\n	<td background=\"".getBytes("Cp1251");
      _jsp_string158 = "<div style=\"width:195;\"><SPACER TYPE=\"block\" HEIGHT=\"1\" WIDTH=\"195\"></div>\r\n	</td>\r\n	<td background=\"".getBytes("Cp1251");
      _jsp_string43 = "\r\n	<td width=\"100%\"><a href=\"".getBytes("Cp1251");
      _jsp_string8 = "/logo-ntv.gif\" width=\"88\" height=\"52\" alt=\"\" border=\"0\"></td>\r\n		<td bgcolor=\"#4991D3\"><img src=\"".getBytes("Cp1251");
      _jsp_string146 = "/bg-bot.gif\" bgcolor=\"#0D3A89\"><div style=\"width:10;\"><SPACER TYPE=\"block\" HEIGHT=\"1\" WIDTH=\"10\"></div></td>\r\n	<td background=\"".getBytes("Cp1251");
      _jsp_string88 = "/tvschedule?date=".getBytes("Cp1251");
      _jsp_string1 = "\r\n\r\n".getBytes("Cp1251");
    } catch (java.io.UnsupportedEncodingException e) {
      e.printStackTrace();
    }
  }
}
