/*
 * JSP generated by Resin 2.0.5 (built Thu Jan 10 21:43:38 PST 2002)
 */

package _admin._upload;
import javax.servlet.*;
import javax.servlet.jsp.*;
import javax.servlet.http.*;
import java.util.*;
import java.text.SimpleDateFormat;
import java.io.*;
import tengry.cms.*;
import tengry.cms.core.*;
import tengry.cms.db.*;
import tengry.cms.user.*;
import tengry.cms.tender.*;
import tengry.cms.press.*;
import tengry.cms.product.*;
import tengry.cms.dict.*;
import tengry.cms.vote.*;
import tengry.cms.faq.*;
import tengry.cms.forum.*;
import tengry.cms.mailer.*;

public class _upload__jsp extends com.caucho.jsp.JavaPage{
  private boolean _caucho_isDead;
  
	private final String	separator	= File.separator;
	
	private void drawFolders( JspWriter out, String folder, String rootPath, String folderPath, String parentFolder ) throws IOException
	{
		boolean	isEmpty	= false;
		try
		{
			out.println("<TABLE BORDER=\"0\" CELLSPACING=\"1\" CELLPADDING=\"1\" WIDTH=\"700\">");
			out.println("<TR>");
			out.print("<TD COLSPAN=\"3\" HEIGHT=\"20\" CLASS=\"titnew\" ALIGN=\"center\"><DIV STYLE=\"padding-left:6px;padding-right:6px\" CLASS=\"titnew\"><B>");
			out.print("Директории ");
			out.print("<A HREF=\"upload.jsp?mode=add_folder&folder="+folder+"\">(создать поддиректорию)</A>");
			out.println("</B></DIV></TD>");
			out.println("</TR>");
			out.println("<TR CLASS=\"c1\">");
			out.println("<TD HEIGHT=\"20\" CLASS=\"c2\"><DIV STYLE=\"padding-left:6px;padding-right:6px\"><B>");
			out.println("директория");
			out.println("</B></DIV></TD>");
			out.println("<TD COLSPAN=\"2\" CLASS=\"c2\"><DIV STYLE=\"padding-left:6px;padding-right:6px\"><B>");
			out.println("действия");
			out.println("</B></DIV></TD>");
			out.println("</TR>");

			if ( parentFolder.length() > 0 || folder.length() > 0 )
			{
				out.println("<TR>");
				out.println("<TD COLSPAN=\"3\" HEIGHT=\"20\" CLASS=\"c1\"><DIV STYLE=\"padding-left:6px;padding-right:6px\">");
				out.println( "<A HREF=\"upload.jsp?folder="+parentFolder+"\">"+separator+"..</A><BR>" );
				out.println("</DIV></TD>");
				out.println("</TR>");
			}

			File	file	= new File( folderPath );
			File[]	files	= file.listFiles();

			if ( files != null && files.length != 0 )
			{
				for( int i=0; i < files.length ; i++ )
				{
					if ( files[i].isDirectory() )
					{
						isEmpty	= true;
						out.println("<TR>");
						out.println("<TD HEIGHT=\"20\" CLASS=\"c1\"><DIV STYLE=\"padding-left:6px;padding-right:6px\">");
						out.println( "<A HREF=\"upload.jsp?folder="+folder+(folder.length()>0?"/":"")+files[i].getName()+"\">"+rootPath+folder+(folder.length()>0?"/":"")+files[i].getName()+separator+"</A><BR>" );
						out.println("</DIV></TD>");
						out.println("<TD HEIGHT=\"20\" WIDTH=\"1%\" CLASS=\"c1\"><DIV STYLE=\"padding-left:6px;padding-right:6px\">");
						out.print("<A HREF=\"upload.jsp?mode=edit_folder&folder="+folder+"&folderName="+files[i].getName()+"\">");
						out.println("переименовать");
						out.println("</A>");
						out.println("</DIV></TD>");
						out.println("<TD HEIGHT=\"20\" WIDTH=\"1%\" CLASS=\"c1\"><DIV STYLE=\"padding-left:6px;padding-right:6px\">");
						out.print("<A HREF=\"xt_upload.jsp?action=delete&folder="+folder+"&fileName="+files[i].getName()+"\" onClick=\"return confirm('Вы уверены?');\">");
						out.println("удалить");
						out.println("</A>");
						out.println("</DIV></TD>");
						out.println("</TR>");
					}
				}
			}
			if ( !isEmpty )
			{
				out.println("<TR>");
				out.println("<TD COLSPAN=\"3\" HEIGHT=\"20\" CLASS=\"c1\"><DIV STYLE=\"padding-left:6px;padding-right:6px\">");
				out.println( "нет поддиректорий" );
				out.println("</DIV></TD>");
				out.println("</TR>");
			}
			out.println("</TABLE>");
		}catch( Exception e )
		{}
	}

	private void showFiles( JspWriter out, String folder, String folderPath, String rootPath,String parentFolder ) throws IOException
	{
		drawFolders( out, folder, rootPath, folderPath, parentFolder );
		
		try
		{
			File	file	= new File( folderPath );
			File[]	files	= file.listFiles();

			out.println("<TABLE BORDER=\"0\" CELLSPACING=\"1\" CELLPADDING=\"1\" WIDTH=\"700\">");
			out.println("<TR>");
			out.println("<TD HEIGHT=\"20\" COLSPAN=\"6\" CLASS=\"titnew\" ALIGN=\"center\"><DIV STYLE=\"padding-left:6px;padding-right:6px\" CLASS=\"titnew\"><B>");
			out.println("Директория \""+rootPath+folder+"\"");
			out.println("</B></DIV></TD>");
			out.println("</TR>");

			out.println("<TR>");
			out.println("<TD HEIGHT=\"20\" CLASS=\"c2\"><DIV STYLE=\"padding-left:6px;padding-right:6px\"><B>");
			out.println("имя файла");
			out.println("</B></DIV></TD>");
			out.println("<TD CLASS=\"c2\"><DIV STYLE=\"padding-left:6px;padding-right:6px\"><B>");
			out.println("обновлен");
			out.println("</B></DIV></TD>");
			out.println("<TD CLASS=\"c2\"><DIV STYLE=\"padding-left:6px;padding-right:6px\"><B>");
			out.println("размер");
			out.println("</B></DIV></TD>");
			out.println("<TD CLASS=\"c2\" COLSPAN=\"3\"><DIV STYLE=\"padding-left:6px;padding-right:6px\"><B>");
			out.println("действия");
			out.println("</B></DIV></TD>");
			out.println("</TR>");
			if ( files != null && files.length != 0 )
			{
				for( int i=0; i < files.length ; i++ )
				{
					if ( !files[i].isDirectory() )
					{
						java.util.Date	theDate	= new java.util.Date( files[i].lastModified() );
						java.util.Calendar	date	= java.util.Calendar.getInstance();
						date.setTime( theDate );
						String	year	= String.valueOf( date.get( java.util.Calendar.YEAR ) );
						String	month	= String.valueOf( date.get( java.util.Calendar.MONTH )+1 );
						if ( month.length() == 1 ) month	= "0"+month;
						String	day		= String.valueOf( date.get( java.util.Calendar.DAY_OF_MONTH ) );
						if ( day.length() == 1 ) day	= "0"+day;
						String	hour		= String.valueOf( date.get( java.util.Calendar.HOUR_OF_DAY ) );
						if ( hour.length() == 1 ) hour	= "0"+hour;
						String	minute		= String.valueOf( date.get( java.util.Calendar.MINUTE ) );
						if ( minute.length() == 1 ) minute	= "0"+minute;
						String	recordDate	= day+"."+month+"."+year+" "+hour+":"+minute;

						out.println("<TR>");
						out.println("<TD HEIGHT=\"20\" CLASS=\"c1\"><DIV STYLE=\"padding-left:6px;padding-right:6px\">");
						out.print("<A HREF=\"/servlet/tengry.servlet.FILEServlet?folder="+folder+"&fileName="+files[i].getName()+"\">");
						out.print( files[i].getName() );
						out.println("</A>");
						out.println("</DIV></TD>");
						out.println("<TD HEIGHT=\"20\" CLASS=\"c1\"><DIV STYLE=\"padding-left:6px;padding-right:6px\">");
						out.println( recordDate );
						out.println("</DIV></TD>");
						out.println("<TD HEIGHT=\"20\" CLASS=\"c1\"><DIV STYLE=\"padding-left:6px;padding-right:6px\">");
						out.println( files[i].length()+" bytes" );
						out.println("</DIV></TD>");
						out.println("<TD HEIGHT=\"20\" WIDTH=\"1%\" CLASS=\"c1\"><DIV STYLE=\"padding-left:6px;padding-right:6px\">");
						out.print("<A HREF=\"upload.jsp?mode=edit_file&folder="+folder+"&fileName="+files[i].getName()+"\">");
						out.println("переименовать");
						out.println("</A>");
						out.println("</DIV></TD>");
						out.println("<TD HEIGHT=\"20\" WIDTH=\"1%\" CLASS=\"c1\"><DIV STYLE=\"padding-left:6px;padding-right:6px\">");
						out.print("<A HREF=\"xt_upload.jsp?action=delete&folder="+folder+"&fileName="+files[i].getName()+"\" onClick=\"return confirm('Вы уверены?');\">");
						out.println("удалить");
						out.println("</A>");
						out.println("</DIV></TD>");
						out.println( "<TD CLASS=\"c1\"><A HREF=\"/upload"+(folder.length()>0?"/"+folder:"")+"/"+files[i].getName()+"\"><IMG SRC=\"/admin/img/ico10.gif\" WIDTH=25 HEIGHT=20 ALT=\"ссылка на файл\" BORDER=\"0\"></A><BR></TD>" );
						out.println("</TR>");
					}
				}
			}
			else
			{
				out.println("<TR>");
				out.println("<TD HEIGHT=\"20\" COLSPAN=\"6\" CLASS=\"c1\"><DIV STYLE=\"padding-left:6px;padding-right:6px\">");
				out.println( "каталог пуст" );
				out.println("</DIV></TD>");
				out.println("</TR>");
			}
	
			out.println("</TABLE>");
		}catch( Exception e )
		{
			out.println( "There was an Exception: "+e );
		}
	}

  
  public void
  _jspService(javax.servlet.http.HttpServletRequest request,
              javax.servlet.http.HttpServletResponse response)
    throws java.io.IOException, javax.servlet.ServletException
  {
    com.caucho.jsp.QPageContext pageContext = (com.caucho.jsp.QPageContext) com.caucho.jsp.QJspFactory.create().getPageContext(this, request, response, null, true, 8192, true);
    javax.servlet.jsp.JspWriter out = (javax.servlet.jsp.JspWriter) pageContext.getOut();
    javax.servlet.ServletConfig config = getServletConfig();
    javax.servlet.Servlet page = this;
    javax.servlet.http.HttpSession session = pageContext.getSession();
    javax.servlet.ServletContext application = pageContext.getServletContext();
    response.setContentType("text/html; charset=windows-1251");
    request.setCharacterEncoding("CP1251");
    try {
      pageContext.write(_jsp_string0, 0, _jsp_string0.length);
      pageContext.write(_jsp_string0, 0, _jsp_string0.length);
      
	// set the Service name for authorization
	String pageId = FileObject.SERVICE_CODE;

      pageContext.write(_jsp_string0, 0, _jsp_string0.length);
      pageContext.write(_jsp_string0, 0, _jsp_string0.length);
      pageContext.write(_jsp_string0, 0, _jsp_string0.length);
      pageContext.write(_jsp_string0, 0, _jsp_string0.length);
      pageContext.write(_jsp_string0, 0, _jsp_string0.length);
      pageContext.write(_jsp_string0, 0, _jsp_string0.length);
      pageContext.write(_jsp_string0, 0, _jsp_string0.length);
      pageContext.write(_jsp_string0, 0, _jsp_string0.length);
      pageContext.write(_jsp_string0, 0, _jsp_string0.length);
      pageContext.write(_jsp_string0, 0, _jsp_string0.length);
      pageContext.write(_jsp_string0, 0, _jsp_string0.length);
      pageContext.write(_jsp_string0, 0, _jsp_string0.length);
      pageContext.write(_jsp_string0, 0, _jsp_string0.length);
      pageContext.write(_jsp_string0, 0, _jsp_string0.length);
      pageContext.write(_jsp_string0, 0, _jsp_string0.length);
      pageContext.write(_jsp_string0, 0, _jsp_string0.length);
      
tengry.cms.core.Admin currentAdmin = (tengry.cms.core.Admin)session.getValue( "admin.user" );
int pageAccessCode = 0;
if( currentAdmin == null )
{
	response.sendRedirect( "/admin/login.jsp" );
	return;
}
else pageAccessCode = currentAdmin.getAccessCode(pageId);

if( ! tengry.cms.core.Admin.isR(pageAccessCode) && ! "admin.index".equals(pageId))
{
	response .sendRedirect( "/admin/index.jsp?err=" + tengry.cms.CMSApplication.PAGE_ERROR_ACCESS_DENIED );
	return;
}

      pageContext.write(_jsp_string1, 0, _jsp_string1.length);
        response.setHeader("Pragma","no-cache"); 
      pageContext.write(_jsp_string0, 0, _jsp_string0.length);
      
    String langCode = request.getParameter("lang_code");
    if(langCode == null || langCode.trim().length() == 0)
        langCode = CMSApplication.getApplication().getPrimaryLangCode();

      pageContext.write(_jsp_string0, 0, _jsp_string0.length);
      
	String	rootPath	= request.getServerName()+separator+"upload"+separator;
	
	String	mode	= request.getParameter("mode");
	if ( mode == null ) mode	= "";

	String	folder	= "";
	folder	= request.getParameter( "folder" );
	if ( folder == null ) folder	= "";


	if( (( mode.equalsIgnoreCase("upload") || mode.equalsIgnoreCase("add_folder")) && ! Admin.isC( pageAccessCode )) ||
		(( mode.equalsIgnoreCase("edit_file") || mode.equalsIgnoreCase("edit_folder")) && ! Admin.isW( pageAccessCode )))
	{
		response.sendRedirect( "upload.jsp?folder=" + folder + "&err=" + CMSApplication.PAGE_ERROR_NO_PERMISSIONS );
		return;
	}
	

      pageContext.write(_jsp_string0, 0, _jsp_string0.length);
      pageContext.write(_jsp_string0, 0, _jsp_string0.length);
      
	String actionDone = request.getParameter("action_done");
	String message = "";
	if("upload".equals(actionDone))
		message = "Файл загружен.";
	else if("edit".equals(actionDone))
		message = "Имя изменено.";
	else if("new_folder".equals(actionDone))
		message = "Директория создана.";
	else if("dir_del".equals(actionDone))
		message = "Директория удалена.";
	else if("file_del".equals(actionDone))
		message = "Файл удален.";


      pageContext.write(_jsp_string0, 0, _jsp_string0.length);
      out.flush();
      pageContext.include("/admin/inc/page_start.jsp"+ '?'+ "title="+ "Работа с файлами"+ '&'+ "header="+ "Работа с файлами"+ '&'+ "message="+ (message)+ '&'+ "width="+ "700"+ '&'+ "err="+ (request.getParameter("err")));
      pageContext.write(_jsp_string0, 0, _jsp_string0.length);
      
	String	folderPath	= CMSApplication.getApplication().getProperty( "upload.dir" );
	
	String	parentFolder	= "";
	
	int index	= folder.lastIndexOf( separator.charAt( 0 ) );
	if ( index != -1 )	parentFolder = folder.substring( 0, index );

	
	if  ( mode.equalsIgnoreCase("upload") )
	{
		
      pageContext.write(_jsp_string2, 0, _jsp_string2.length);
      out.print((folder));
      pageContext.write(_jsp_string3, 0, _jsp_string3.length);
      out.print((rootPath+folder));
      pageContext.write(_jsp_string4, 0, _jsp_string4.length);
      
	}
	else if  ( mode.equalsIgnoreCase("edit_file") )
	{
		String	fileName	= request.getParameter( "fileName" );
		
		if ( folder.length() > 0 )
		{
			folderPath	+= separator+folder+separator;
		}
		else
		{
			folderPath	+= separator;
		}
		fileName	= folderPath+fileName;
		File	file	= null;
		try
		{
			file	= new File( fileName );
			if ( file.exists() )
			{
				String	name	= file.getName();
				
      pageContext.write(_jsp_string5, 0, _jsp_string5.length);
      out.print((folder));
      pageContext.write(_jsp_string6, 0, _jsp_string6.length);
      out.print((name));
      pageContext.write(_jsp_string7, 0, _jsp_string7.length);
      out.print((rootPath+folder));
      pageContext.write(_jsp_string8, 0, _jsp_string8.length);
      out.print((name));
      pageContext.write(_jsp_string9, 0, _jsp_string9.length);
      
			}
			else
			{
				out.println( "<B STYLE=\"color: red;\">Файл не найден.</B><BR>" );
			}
		}catch( Exception e )
		{
			out.println( "<B STYLE=\"color: red;\">Произошла ошибка при чтении файла.</B><BR>" );
		}
	}
	else if  ( mode.equalsIgnoreCase("edit_folder") )
	{
		String	folderName	= request.getParameter( "folderName" );
		
		if ( folder.length() > 0 )
		{
			folderPath	+= separator+folder+separator;
		}
		else
		{
			folderPath	+= separator;
		}
		folderName	= folderPath+folderName;
		File	file	= null;
		try
		{
			file	= new File( folderName );
			if ( file.exists() )
			{
				String	name	= file.getName();
				
      pageContext.write(_jsp_string10, 0, _jsp_string10.length);
      out.print((folder));
      pageContext.write(_jsp_string6, 0, _jsp_string6.length);
      out.print((name));
      pageContext.write(_jsp_string7, 0, _jsp_string7.length);
      out.print((rootPath+folder));
      pageContext.write(_jsp_string11, 0, _jsp_string11.length);
      out.print((name));
      pageContext.write(_jsp_string12, 0, _jsp_string12.length);
      
			}
			else
			{
				out.println( "<B STYLE=\"color: red;\">Поддиректория не найдена.</B><BR>" );
			}
		}catch( Exception e )
		{
			out.println( "<B STYLE=\"color: red;\">Произошла ошибка при чтении файла.</B><BR>" );
		}
	}
	else if  ( mode.equalsIgnoreCase("add_folder") )
	{
		if ( folder.length() > 0 )
		{
			folderPath	+= separator+folder+separator;
		}
		else
		{
			folderPath	+= separator;
		}
		
      pageContext.write(_jsp_string13, 0, _jsp_string13.length);
      out.print((folder));
      pageContext.write(_jsp_string14, 0, _jsp_string14.length);
      out.print((rootPath+folder));
      pageContext.write(_jsp_string15, 0, _jsp_string15.length);
      
	}
	else
	{
		if  ( mode.equalsIgnoreCase("error") )
		{
			
      pageContext.write(_jsp_string16, 0, _jsp_string16.length);
      
			String	res	= request.getParameter( "res" );
			if ( res != null && res.equals( "notEmpty" ) )
			{
			
      pageContext.write(_jsp_string17, 0, _jsp_string17.length);
      
			}
		}
		if  ( mode.equalsIgnoreCase("isExist") )
		{
			
      pageContext.write(_jsp_string18, 0, _jsp_string18.length);
      
		}
		if ( folder.length() > 0 )
		{
			folderPath	+= separator+folder+separator;
		}

      pageContext.write(_jsp_string19, 0, _jsp_string19.length);
      out.print((folder));
      pageContext.write(_jsp_string20, 0, _jsp_string20.length);
      
	showFiles( out, folder, folderPath, rootPath, parentFolder );

      pageContext.write(_jsp_string21, 0, _jsp_string21.length);
      out.print((folder));
      pageContext.write(_jsp_string22, 0, _jsp_string22.length);
      	} 
      pageContext.write(_jsp_string0, 0, _jsp_string0.length);
      out.flush();
      pageContext.include("/admin/inc/page_finish.jsp");
      pageContext.write(_jsp_string1, 0, _jsp_string1.length);
    } catch (java.lang.Throwable _jsp_e) {
      pageContext.handlePageException(_jsp_e);
    } finally {
      JspFactory.getDefaultFactory().releasePageContext(pageContext);
    }
  }

  private com.caucho.java.LineMap _caucho_line_map;
  private java.util.ArrayList _caucho_depends = new java.util.ArrayList();

  public boolean _caucho_isModified()
  {
    if (_caucho_isDead)
      return true;
    if (com.caucho.util.CauchoSystem.getVersionId() != 2058990002)
      return true;
    for (int i = _caucho_depends.size() - 1; i >= 0; i--) {
      com.caucho.vfs.Depend depend;
      depend = (com.caucho.vfs.Depend) _caucho_depends.get(i);
      if (depend.isModified())
        return true;
    }
    return false;
  }

  public long _caucho_lastModified()
  {
    return 0;
  }

  public com.caucho.java.LineMap _caucho_getLineMap()
  {
    return _caucho_line_map;
  }

  public void destroy()
  {
      _caucho_isDead = true;
      super.destroy();
  }

  public void init(com.caucho.java.LineMap lineMap,
                   com.caucho.vfs.Path appDir)
    throws javax.servlet.ServletException
  {
    com.caucho.vfs.Path resinHome = com.caucho.util.CauchoSystem.getResinHome();
    com.caucho.vfs.MergePath mergePath = new com.caucho.vfs.MergePath();
    mergePath.addMergePath(appDir);
    mergePath.addMergePath(resinHome);
    mergePath.addClassPath(getClass().getClassLoader());
    _caucho_line_map = new com.caucho.java.LineMap("_upload__jsp.java", "/usr/local/apache/htdocs/ntvmir/admin/upload/upload.jsp");
    _caucho_line_map.add("/admin/upload/upload.jsp", 1, 1);
    _caucho_line_map.add("/admin/inc/page_init.jsp", 1, 1);
    _caucho_line_map.add("/usr/local/apache/htdocs/ntvmir/admin/upload/upload.jsp", 27, 27);
    _caucho_line_map.add("/admin/upload/upload.jsp", 1, 209);
    _caucho_line_map.add(7, 216);
    _caucho_line_map.add("/admin/inc/page_init.jsp", 1, 216);
    _caucho_line_map.add("/admin/inc/authorize.jsp", 1, 231);
    _caucho_line_map.add("/admin/inc/page_init.jsp", 17, 248);
    _caucho_line_map.add(18, 250);
    _caucho_line_map.add("/usr/local/apache/htdocs/ntvmir/admin/upload/upload.jsp", 8, 256);
    _caucho_line_map.add(27, 276);
    _caucho_line_map.add(194, 277);
    _caucho_line_map.add(209, 293);
    _caucho_line_map.add(216, 296);
    _caucho_line_map.add(228, 309);
    _caucho_line_map.add(233, 311);
    _caucho_line_map.add(254, 313);
    _caucho_line_map.add(285, 341);
    _caucho_line_map.add(299, 343);
    _caucho_line_map.add(306, 345);
    _caucho_line_map.add(346, 382);
    _caucho_line_map.add(360, 384);
    _caucho_line_map.add(367, 386);
    _caucho_line_map.add(396, 411);
    _caucho_line_map.add(417, 413);
    _caucho_line_map.add(447, 442);
    _caucho_line_map.add(448, 444);
    _caucho_line_map.add(451, 448);
    _caucho_line_map.add(454, 452);
    com.caucho.vfs.Depend depend;
    depend = new com.caucho.vfs.Depend(mergePath.lookup("file:/usr/local/apache/htdocs/ntvmir/admin/inc/page_init.jsp"), 1043089496000L, 877L);
    _caucho_depends.add(depend);
    depend = new com.caucho.vfs.Depend(mergePath.lookup("file:/usr/local/apache/htdocs/ntvmir/admin/inc/authorize.jsp"), 1019117520000L, 486L);
    _caucho_depends.add(depend);
    depend = new com.caucho.vfs.Depend(mergePath.lookup("file:/usr/local/apache/htdocs/ntvmir/admin/upload/upload.jsp"), 1039607994000L, 16974L);
    _caucho_depends.add(depend);
  }

  private static byte []_jsp_string22;
  private static byte []_jsp_string14;
  private static byte []_jsp_string7;
  private static byte []_jsp_string9;
  private static byte []_jsp_string15;
  private static byte []_jsp_string4;
  private static byte []_jsp_string8;
  private static byte []_jsp_string2;
  private static byte []_jsp_string19;
  private static byte []_jsp_string16;
  private static byte []_jsp_string5;
  private static byte []_jsp_string21;
  private static byte []_jsp_string17;
  private static byte []_jsp_string0;
  private static byte []_jsp_string3;
  private static byte []_jsp_string11;
  private static byte []_jsp_string13;
  private static byte []_jsp_string10;
  private static byte []_jsp_string12;
  private static byte []_jsp_string18;
  private static byte []_jsp_string20;
  private static byte []_jsp_string1;
  private static byte []_jsp_string6;
  static {
    try {
      _jsp_string22 = "\">загрузить новый файл</A><BR>\r\n</FORM>\r\n".getBytes("Cp1251");
      _jsp_string14 = "\">\r\n		<INPUT TYPE=\"Hidden\" NAME=\"action\" VALUE=\"add_folder\">\r\n		<TABLE WIDTH=\"700\" BORDER=\"0\" CELLSPACING=\"1\" CELLPADDING=\"1\">\r\n		<TR>\r\n		<TD CLASS=\"c2\" HEIGHT=\"20\">\r\n		<DIV STYLE=\"padding-left:6px;padding-right:6px\">\r\n		<B>Директория \"".getBytes("Cp1251");
      _jsp_string7 = "\">\r\n				<TABLE WIDTH=\"700\" BORDER=\"0\" CELLSPACING=\"1\" CELLPADDING=\"1\">\r\n				<TR>\r\n				<TD CLASS=\"c2\" HEIGHT=\"20\">\r\n				<DIV STYLE=\"padding-left:6px;padding-right:6px\">\r\n				<B>Директория \"".getBytes("Cp1251");
      _jsp_string9 = "\">\r\n				</DIV>\r\n				</TD>\r\n				</TR>\r\n				</TABLE>\r\n				<INPUT TYPE=\"button\" VALUE=\"переименовать\" ONCLICK=\"if(confirm('Переименовать?')){ if (document.FORM3.fileName.value=='') {alert('Укажите имя файла!');}else{document.FORM3.submit();}}\">\r\n				</FORM>\r\n				".getBytes("Cp1251");
      _jsp_string15 = "\"</B>\r\n		</DIV>\r\n		</TD>\r\n		</TR>\r\n		<TR>\r\n		<TD CLASS=\"c2\" HEIGHT=\"20\">\r\n		<DIV STYLE=\"padding-left:6px;padding-right:6px\">\r\n		<B>Имя поддиректории:</B>\r\n		</DIV>\r\n		</TD>\r\n		</TR>\r\n		<TR>\r\n		<TD CLASS=\"c1\" HEIGHT=\"20\">\r\n		<DIV STYLE=\"padding-left:6px;padding-right:6px\">\r\n		<INPUT TYPE=\"text\" NAME=\"folderName\" STYLE=\"width:700\" SIZE=\"34\" VALUE=\"\">\r\n		</DIV>\r\n		</TD>\r\n		</TR>\r\n		</TABLE>\r\n		<INPUT TYPE=\"button\" VALUE=\"Сохранить\" ONCLICK=\"if(confirm('Сохранить')){ if (document.FORM3.folderName.value=='') {alert('Укажите имя поддиректории!');}else{document.FORM3.submit();}}\">\r\n		</FORM>\r\n		".getBytes("Cp1251");
      _jsp_string4 = "\"</B>\r\n		</DIV>\r\n		</TD>\r\n		</TR>\r\n		<TR>\r\n		<TD CLASS=\"c2\" HEIGHT=\"20\">\r\n		<DIV STYLE=\"padding-left:6px;padding-right:6px\">\r\n		<B>Имя локального файла(для отправки его на сервер):</B>\r\n		</DIV>\r\n		</TD>\r\n		</TR>\r\n		<TR>\r\n		<TD CLASS=\"c1\" HEIGHT=\"20\">\r\n		<DIV STYLE=\"padding-left:6px;padding-right:6px\">\r\n		<INPUT TYPE=\"File\" NAME=\"file\" STYLE=\"width:470\" SIZE=\"34\">\r\n		</DIV>\r\n		</TD>\r\n		</TR>\r\n		</TABLE>\r\n		<INPUT TYPE=\"button\" VALUE=\"Закачать\" ONCLICK=\"if(confirm('Закачать файл')) { if (document.FORM3.file.value=='') {alert('Укажите файл для закачки!');}else{document.FORM3.submit();}}\">\r\n		</FORM>\r\n		".getBytes("Cp1251");
      _jsp_string8 = "\"</B>\r\n				</DIV>\r\n				</TD>\r\n				</TR>\r\n				<TR>\r\n				<TD CLASS=\"c2\" HEIGHT=\"20\">\r\n				<DIV STYLE=\"padding-left:6px;padding-right:6px\">\r\n				<B>Имя файла:</B>\r\n				</DIV>\r\n				</TD>\r\n				</TR>\r\n				<TR>\r\n				<TD CLASS=\"c1\" HEIGHT=\"20\">\r\n				<DIV STYLE=\"padding-left:6px;padding-right:6px\">\r\n				<INPUT TYPE=\"text\" NAME=\"fileName\" STYLE=\"width:700\" SIZE=\"34\" VALUE=\"".getBytes("Cp1251");
      _jsp_string2 = "\r\n		<FORM NAME=\"FORM3\" ACTION=\"xt_upload.jsp?action=upload&folder=".getBytes("Cp1251");
      _jsp_string19 = "\r\n<FORM NAME=\"FORM1\" ACTION=\"xt_upload.jsp\" METHOD=\"post\">\r\n<INPUT TYPE=\"Hidden\" NAME=\"action\" VALUE=\"del_messages\">\r\n<INPUT TYPE=\"Hidden\" NAME=\"folder\" VALUE=\"".getBytes("Cp1251");
      _jsp_string16 = "\r\n			<B STYLE=\"color: red;\">Произошла ошибка. Попробуйте еще раз.</B><BR>\r\n			".getBytes("Cp1251");
      _jsp_string5 = "\r\n				<FORM NAME=\"FORM3\" ACTION=\"xt_upload.jsp\" METHOD=\"post\" onSubmit=\"if(confirm('Переименовать?')){ if (document.FORM3.fileName.value=='') {alert('Укажите имя файла!'); return false;}else{return true;}}else {return false;}\">\r\n				<INPUT TYPE=\"Hidden\" NAME=\"folder\" VALUE=\"".getBytes("Cp1251");
      _jsp_string21 = "\r\n<BR><A HREF=\"upload.jsp?mode=upload&folder=".getBytes("Cp1251");
      _jsp_string17 = "\r\n			<B STYLE=\"color: red;\">Возможно директория содержит файлы или поддиректории.</B><BR>\r\n			".getBytes("Cp1251");
      _jsp_string0 = "\r\n".getBytes("Cp1251");
      _jsp_string3 = "\" METHOD=\"post\" ENCTYPE=\"multipart/form-data\" onSubmit=\"if(confirm('Закачать файл')) { if (document.FORM3.file.value=='') {alert('Укажите файл для закачки!'); return false;}else{ return true;}}else return false;\">\r\n		<TABLE WIDTH=\"700\" BORDER=\"0\" CELLSPACING=\"1\" CELLPADDING=\"1\">\r\n		<TR>\r\n		<TD CLASS=\"c2\" HEIGHT=\"20\">\r\n		<DIV STYLE=\"padding-left:6px;padding-right:6px\">\r\n		<B>Директория \"".getBytes("Cp1251");
      _jsp_string11 = "\"</B>\r\n				</DIV>\r\n				</TD>\r\n				</TR>\r\n				<TR>\r\n				<TD CLASS=\"c2\" HEIGHT=\"20\">\r\n				<DIV STYLE=\"padding-left:6px;padding-right:6px\">\r\n				<B>Имя поддиректории:</B>\r\n				</DIV>\r\n				</TD>\r\n				</TR>\r\n				<TR>\r\n				<TD CLASS=\"c1\" HEIGHT=\"20\">\r\n				<DIV STYLE=\"padding-left:6px;padding-right:6px\">\r\n				<INPUT TYPE=\"text\" NAME=\"fileName\" STYLE=\"width:700\" SIZE=\"34\" VALUE=\"".getBytes("Cp1251");
      _jsp_string13 = "\r\n		<FORM NAME=\"FORM3\" ACTION=\"xt_upload.jsp\" METHOD=\"post\" onSubmit=\"if(confirm('Сохранить')){ if (document.FORM3.folderName.value=='') {alert('Укажите имя поддиректории!'); return false;}else{return true;}} else return false;\">\r\n		<INPUT TYPE=\"Hidden\" NAME=\"folder\" VALUE=\"".getBytes("Cp1251");
      _jsp_string10 = "\r\n				<FORM NAME=\"FORM3\" ACTION=\"xt_upload.jsp\" METHOD=\"post\" onSubmit=\"if(confirm('Переименовать?')){ if (document.FORM3.fileName.value=='') {alert('Укажите имя поддиректории!'); return false;}else{return true;}}else {return false;}\">\r\n				<INPUT TYPE=\"Hidden\" NAME=\"folder\" VALUE=\"".getBytes("Cp1251");
      _jsp_string12 = "\">\r\n				</DIV>\r\n				</TD>\r\n				</TR>\r\n				</TABLE>\r\n				<INPUT TYPE=\"button\" VALUE=\"переименовать\" ONCLICK=\"if(confirm('Переименовать?')){ if (document.FORM3.fileName.value=='') {alert('Укажите имя поддиректории!');}else{document.FORM3.submit();}}\">\r\n				</FORM>\r\n				".getBytes("Cp1251");
      _jsp_string18 = "\r\n			<B STYLE=\"color: red;\">Файл с таким именем уже существует. Удалите одноименный файл, если вы хотите заменить его на новый.</B><BR><BR>\r\n			".getBytes("Cp1251");
      _jsp_string20 = "\">\r\n".getBytes("Cp1251");
      _jsp_string1 = "\r\n\r\n".getBytes("Cp1251");
      _jsp_string6 = "\">\r\n				<INPUT TYPE=\"Hidden\" NAME=\"action\" VALUE=\"edit\">\r\n				<INPUT TYPE=\"Hidden\" NAME=\"oldName\" VALUE=\"".getBytes("Cp1251");
    } catch (java.io.UnsupportedEncodingException e) {
      e.printStackTrace();
    }
  }
}
